### ISSUE TITLE
Virtual Machine or WinXP - Make compatible with WinXP

### ISSUE THREAD

**Issue by JonKaruzu** [rerrahkr/BambooTracker#1]
I opened BambooTracker and still getting this message.
" The procedure entry point "CancelIoEx" could not located in the dynamic link library "Kernel32.dll" "

I should not work on Older machines. :(

Sorry for my old pcc And I didn't get new one

**Comment by rerrahkr** [comment]
Hi, thank you for your report.
It seems that the current Qt library does not support windows XP or earlier.
I will try to drop the version of the library and run it on my XP.

**Comment by JonKaruzu** [comment]
Oh. Thanks.
I use Acer aspire 3680
512mb ram
1.6Ghz Intel Celeron

**Comment by rerrahkr** [comment]
When I tried dropping the version of the library, I got some part I could not change without rewriting the code.
I think that it will take time, but I will try it.

**Comment by OPNA2608** [comment]
While this doesn't fix the apparent compatibility issue with old Windows versions, you could [look around](https://fossbytes.com/best-lightweight-linux-distros/) and install a up-to-date, lightweight Linux version, if you're not too dependent on super proprietary Windows or other XP-only applications.
Although it'd require some getting-used-to to Linuxisms, [BambooTracker appears to work just fine](https://github.com/rerrahkr/BambooTracker/blob/5129529e6da5bd6529bd332cc8636b52cba326c7/README.md#build-on-linux) if you get a Ubuntu-based Linux distribution.

**Comment by JonKaruzu** [comment]
Some compatibility issues won't work on the lastest version. And some a lot people worked fine on Windows 10.
I will switch to Linux because my laptop doesn't enough space for install Linux OS 
I'll try to buy my PC. 
This program now requires Windows 7 or higher to work.

Now please close this issue.

Just kidding.

There is a compile from MinGW-32 or whatever.
I am using Windows XP SP3 and never helps. Or I'll wait.

Sorry for apologise this older machine.

Also I have Intel Celeron x86 1.60Ghz 1 core

**Comment by JonKaruzu** [comment]
I forgot. It was Linux version lol

**Comment by rerrahkr** [comment]
Since I modified the code ([e40ed99](https://github.com/rerrahkr/BambooTracker/commit/e40ed996a1be3e03b23fa0480fd548dbb95d5386)), I will publish the binary in the next release.

**Comment by rerrahkr** [comment]
Now I published XP version in the new release ([v0.1.2](https://github.com/rerrahkr/BambooTracker/releases/tag/v0.1.2)).

**Comment by JonKaruzu** [comment]
It works 😴
And now let's test. If found a error I could report
