### ISSUE TITLE
Accelerate vgm/s98 export

### ISSUE THREAD

**Issue by jpcima** [rerrahkr/BambooTracker#100]
The task is a bit slow, especially on Nuked which is heavy on the CPU.
Since we don't need the sound output, it's great if these exports can bypass the generation when they are exporting a register dump. Then, the export is going to be nearly instantaneous.

**Comment by rerrahkr** [comment]
Thanks for request. I fix export process to skip register writing to the emulation core and sample generation at 4bc08cd83d87f0403f83df858305c3f52d2b9344.

**Comment by jpcima** [comment]
Nice. Can I rewrite `isNeedSampleGeneration` as virtual method in `ExportContainerInterface` ?
The core guidelines recommend against `dynamic_cast` which has usually slow implementations.
Second, a future export container will be forced to think of implementing the method.

**Comment by rerrahkr** [comment]
Thanks, your idea is better than mine.

**Comment by jpcima** [comment]
Great :+1:
