### ISSUE TITLE
Specific pitch sequence crashes the tracker when played

### ISSUE THREAD

**Issue by emninem** [rerrahkr/BambooTracker#11]
I was working on a module yesterday, and decided to book it and work on it later. When I loaded the module earlier today, it kept crashing after it got to a specific part in the song.

A friend and I have determined that it is the pitch sequence on instrument 03 (the snare drum) -- It would crash the tracker if played by itself only, and would not crash if the pitch sequence was changed.

Attached below is the module with the bug (in a .zip file, because Github doesn't accept .BTM files), I'm not sure if this is an adequate bug report or if this has been reported before - if it has, my apologies.

[TEST.zip](https://github.com/rerrahkr/BambooTracker/files/2625909/TEST.zip)

**Comment by rerrahkr** [comment]
When analyzing the file, an release was specified in Arpeggio / Pitch sequence of Instrument 03. But release point was set to 0xff that it was unexpected value. When I deleted them, the tracker doesn't crash.
I attached the fixed file.
[TEST_FIXED.zip](https://github.com/rerrahkr/BambooTracker/files/2634041/TEST_FIXED.zip)

Have you edited the release with Instrument 03 arpeggio or pitch?

**Comment by emninem** [comment]
I think I edited the release by accident when I meant to loop it, and removed it afterwards? I don't exactly remember what I did, but I'll keep that in mind for future endeavours.

Thanks for looking into it!

**Comment by rerrahkr** [comment]
I finally resolve this bug at 03e0c35. It reasons that I forgot initialization of release type.
Thanks for your report!
