### ISSUE TITLE
Suggestion: Having a help window listing effect commands

### ISSUE THREAD

**Issue by attilaM68K** [rerrahkr/BambooTracker#112]
In a similar way to how Impulse Tracker (or Schism Tracker) has an info page dedicated to listing all effect commands, BambooTracker could have one as well, maybe under the help menu. Also, F1 could be used to quickly access it, since it is a standard way of opening (sometimes contextual) help menus under trackers.

**Comment by OPNA2608** [comment]
This could either be a plain table/window listing all commands and what they do and leave it at that, or we could also add a search box to filter the listing for entries that contain matches. (plaintext, regex?)

A small combobox-like dialogue when attempting to edit an effect to search and pick whatever you need on-the-fly would be thinkable too perhaps…

**Comment by rerrahkr** [comment]
Thanks for your request. I will try to make a plain list dialog similar to the keyboard shotcut one mentioned in [#79](https://github.com/rerrahkr/BambooTracker/issues/79#issuecomment-473652495)

**Comment by rerrahkr** [comment]
I add effect table view at a6d070c36a16003f686fe5b40ffe4e559912bd6d. Pressed F1, it is opened.
