### ISSUE TITLE
Can't resize FM instrument window

### ISSUE THREAD

**Issue by Delta-Psi** [rerrahkr/BambooTracker#119]
The FM instrument editor window overflows my screen (1366x768 resolution), making it impossible to modify the parameters of the fourth operator:

![screenshot of the window](https://i.imgur.com/0AmWyP6.png)

There's no vertical scroll bar or any way to resize this window. I've built the program from the current master branch on Manjaro Linux.

**Comment by rerrahkr** [comment]
Thanks for your request. I changed FM instrument editor scrollable at 597105723718344a07088372f192a674d4fbc6a0.
