### ISSUE TITLE
Right-clicking order editor leads to disabled menu

### ISSUE THREAD

**Issue by jimbo1qaz** [rerrahkr/BambooTracker#12]
Kubuntu 18.04 x64, Qt 5.9.5.

I cannot add new orders by right-clicking the black space around the orders. Instead the menu is grayed out without an indication as to what's wrong.

Instead, I have to click the actual numbers. I find this unintuitive.

-------

Is there a keyboard shortcut to switch between order and pattern editor?

**Comment by rerrahkr** [comment]
Thanks you for your advice.
I will try to fix it.

Currently there is no shortcut to switch between order list and pattern editor.

**Comment by rerrahkr** [comment]
I fixed order menu ([7449c20](https://github.com/rerrahkr/BambooTracker/commit/7449c2089ce6cacb7f38d10d13c470a1e4a30ec2)) and added keyboard shortcuts to focus order list and pattern editor ([353ce35](https://github.com/rerrahkr/BambooTracker/commit/353ce359ec5efa3e0652d7f870f8e02b6fd54506)).
