### ISSUE TITLE
Minor issues on opening files.

### ISSUE THREAD

**Issue by ImATrackMan** [rerrahkr/BambooTracker#127]
If a file uses more than one effect column, on saving and reopening, the expanded effect columns do not appear. They are present and function properly, but the user has to manually expand the effect columns again to see them.

A file with a custom refresh rate, for example, 64 Hz, will play at the proper speed when being worked on. After it's saved and reopened, the file will play back slowly, but the refresh rate will be saved. Changing and resetting the refresh rate will restore the file to its proper speed, but it will be slow again on the next load operation.

**Comment by rerrahkr** [comment]
Thanks for your reports.
I had forgotten changing the tick frequency when a module opened, so I fixed it in d31d7aac5fb689cf03f59d0d55e1fb6755e6f2a1.
On the effect columns, since its status needs to be saved in the module file, I will revise the file spec and then fix it.

**Comment by rerrahkr** [comment]
I added effect display width settings to a module in ea4b6276ee6d111ba889e5d991c0d131a1f2e01f.
