### ISSUE TITLE
Problems with importing plain text instruments 

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#128]
I know it's not a bug, rather I am doing something wrong, but when I try to paste istrument data from OPM format, it always results in error `Did not match the clipboard text format with VOPM`

For example, contents of .opm file like that:

`@:52 Gs_03.M2 - @007
LFO: 0 0 0 0 0
CH: 64 5 4 0 0 120 0
M1:  31   9   0   0   4  20   0   1   3 0 0
C1:  31  11   3   9   1   0   0   2   7 0 0
M2:  31   0   0   0   0  40   0   2   3 0 0
C2:  31  11   3   9   1   0   0   1   7 0 0`

result in mentioned error. PMD and NRTDRV .mmls work... but imported instruments sound off at first, I have to play with sliders back and forth to give them proper timbre 🤔 
[pc98.zip](https://github.com/rerrahkr/BambooTracker/files/3194391/pc98.zip) - plain text files that might help to show problems

**Comment by jpcima** [comment]
I think, try to erase digits from the name `Gs_03.M2`.
It's possible it will try to extract these and interpret them as a value.

**Comment by papiezak** [comment]
That worked, however it's the same as with rest formats- upon importing, it sounds like fusion of previous and current loaded instruments, like every parameter except FB and ALG isn't uptaded...

**Comment by rerrahkr** [comment]
Thanks for report.
I found that it didn't works not only envelope paste from MML but also simple envelope paste.
This bug is fixed in a947fa33120429a9b48e7e141587ccfb865ab160 by removing a wrong event blocking.

**Comment by papiezak** [comment]
Now it's fine, thanks for the fix!
