### ISSUE TITLE
A couple of midi keyboard related bugs

### ISSUE THREAD

**Issue by galap-1** [rerrahkr/BambooTracker#129]
In general, the midi keyboard support works great, but I'd like to report a couple of bugs I've discovered with it:

- when using the keyboard in jam mode polyphony does not work correctly when the interval between notes is an octave (or also two octaves etc.)

- when in FM3ch expanded mode there is a lot of inconsistent behavior when using the midi keyboard-- for example after pressing multiple keys notes will often get 'stuck' and won't play for a while.

**Comment by rerrahkr** [comment]
Thanks for your report, I will check it.

**Comment by rerrahkr** [comment]
I fixed MIDI keyboard entries that interval is an octave at 6cae4d2eade7a74c2052f23e0f82d96fd131e207, and jam-mode in FM 3ch expanded mode at 1b1b394e290a053f0d7867f1067749bbaf9c562a. This change makes all operators of FM 3ch to trigger key on/off concurrently during jam-mode.
