### ISSUE TITLE
Improvements to cursor movement

### ISSUE THREAD

**Issue by jimbo1qaz** [rerrahkr/BambooTracker#13]
- Move cursor to right, not down, after entering effect type (possibly effect param as well)
- Shortcut to "jump up/down to next highlighted beat"?
- Editable step? 0 or greater.

**Comment by rerrahkr** [comment]
I will change the cursor movement for the effect part.
If "Page jump length" in Configulation matches the number of "step highlight", you can jump with PageUp / PageDown.
Sorry, what does "Editable step" mean?

**Comment by jimbo1qaz** [comment]
Do you think that moving cursor to right is better behavior? I don't want to force a change. (I added it to a branch of 0cc but never merged it since you can't restore old behavior)

Editable step allows cursor to move down by 2 or 4 or etc. steps per note.

In FT, many actions result in no longer being aligned with highlight:
- move down 1 step per note
- stop playback
- press End key (workaround by pressing Down arrow, but takes up time)
pageup/down will not restore alignment.

I was requesting am alternative pageup/down shortcut to align to grid.

**Comment by rerrahkr** [comment]
I did not think about moving in highlight units, so I will try to do it.
I'll also try moving cursor to right.

**Comment by rerrahkr** [comment]
I added in e10980de20fbde5849b606eb5cd5a61bda44a61f and 447abc1f2b3eb72b33f8b8c6022198509551f63b.
Please substitute highlighted step jump etc. for editable step.

**Comment by jimbo1qaz** [comment]
Thank you, I'll try it out if I ever try BambooTracker again :(

**Comment by rerrahkr** [comment]
Sorry, that was my own check mistake.
Had just checked 0CC-FT, I realized that "Step" in "Edit settings" corresponds to that.
To be honest, I rarely create music with FT, so I never used it before.
I will try it since I want to implement as many functions as possible.
