### ISSUE TITLE
Trouble with song export

### ISSUE THREAD

**Issue by AoiMimi** [rerrahkr/BambooTracker#130]
Trying to export in any of the available formats (WAV, VGM, S98) makes the exported file immediately delete itself.
I tested this with the demo songs as well, and ran into the same problem.

**Comment by papiezak** [comment]
That's weird, I can't replicate this problem, at least on Windows 10. Tried all demo songs, even my own one, every format, no success.
What OS are you using? Did you compiled tracker from source, or downloaded dev build from AppVeyor/0.2 release?

**Comment by AoiMimi** [comment]
I'm using Windows 10 Home, and I've downloaded version 0.2.0 from the Releases tab.
Sorry I can't figure out what might be causing this either...

**Comment by rerrahkr** [comment]
Thanks for your report. I could not replicated on my Windows 10. I should not have written the code to delete the file...

**Comment by papiezak** [comment]
It can be a problem on the OS side, try running BambooTracker as an admin, exporting to several other directories or even flash drives, etc..
What about saving instrument or module files? They aren't being deleted after save?

**Comment by AoiMimi** [comment]
Saving and loading instrument files works fine.
I tried running the program and exporting as admin, but still had the same issue, even with exporting to different directories.

**Comment by papiezak** [comment]
Last thing you can do is trying on another PC or HDD/SSD, if you have access to it...

**Comment by AoiMimi** [comment]
Until another solution is found, I will try that. Thank you!

**Comment by scarletbullgon** [comment]
I have this same exact issue myself, but not only it occurs when the program isn't running under administration privileges, but also when the folder you're trying to export into has special characters with diacritics in them (for example; acutes such as á, ó, and diaeresis like ü).

**Comment by jpcima** [comment]
Oh there is an encoding anomaly for Windows. It's dubious why it would remove files though.
BT passes utf-8 strings to file opening functions but this doesn't work, it takes a conversion to Utf-16 and calling the widechar variant. It's only Windows which needs having this workaround.

**Comment by jpcima** [comment]
Can you report whether the version here helps solve the problem?
https://ci.appveyor.com/project/rerrahkr/bambootracker/builds/25017454/job/iev9gb9kjupmgh6b/artifacts

**Comment by papiezak** [comment]
>when the folder you're trying to export into has special characters with diacritics in them

Now I'm able to replicate it, and #133 seems to fix it; thanks @jpcima!

**Comment by rerrahkr** [comment]
I merged #133. Thanks all for reports and helps!
