### ISSUE TITLE
Incorrect bit set for FM 3ch expanded mode

### ISSUE THREAD

**Issue by rerrahkr** [rerrahkr/BambooTracker#131]
@jpcima I find that the tone of FM 3ch is different from the tone of other channels when using Nuked OPN-Mod added at #94.
[fm3chex.zip](https://github.com/rerrahkr/BambooTracker/files/3243828/fm3chex.zip)

Changing some envelope parameters, I also notice that it will not update TL in 3ch, so there may be a mistake in writing to the register.

**Comment by jpcima** [comment]
I'm going to check it, feel free to assign me this one.
Apologies for the delay noticing, my mail provider had some trouble during this week.

**Comment by jpcima** [comment]
Hi @nukeykt, I believe @rerrahkr has possibly discovered some very strange behavior in Nuked OPN2.
Here are sound samples and VGM.
[nukedfm3ch.zip](https://github.com/rerrahkr/BambooTracker/files/3263580/nukedfm3ch.zip)

(for a short introduction, Bambootracker is an OPNA tracker, and NukedOPN-Mod is a work over NukedOPN2 which added some OPNA features and raised channel clipping levels ; but, I have also checked in VGMPlay where Nuked is vanilla)

For comparison, we have YM2612 and YM2608 recordings of one note played.
1. BambooTracker, MAME YM2608 (or VGMPlay, it's same)
2. BambooTracker, Nuked(Mod) OPNA-ish
3. VGMPlay, Nuked OPN2
4. VGMPlay, Genesis Plus GX
5. VGMPlay, Gens
 
We have (1) as comparison reference.  
In VGMPlay, (4) and (5) output similar waveform (clipping of YM2612 aside), which suggest correct operation.  
Nuked (2) and (3) generate completely different tone. (The OPN2 makes a ton of clipping also)

- MAME has produced **this wave (without clipping)**

![Capture du 2019-06-06 23-52-49](https://user-images.githubusercontent.com/17614485/59069053-4dab2d00-88b6-11e9-8f86-92db8d95e7db.png)

- and Nuked has produced **this wave (without clipping)**

![Capture du 2019-06-06 23-54-15](https://user-images.githubusercontent.com/17614485/59069078-69aece80-88b6-11e9-8dd6-3096375b21f4.png)

Do you have an idea about this?

**Comment by nukeykt** [comment]
VGM writes 0x80 to 0x27 register which enables CSM mode, so may be this is reason of weird sound? Neither MAME and Gens don't emulate CSM mode accurately AFAIK. Also according to YM2608 datasheet YM2608 CSM mode is activated a bit differently: you need to write 0x40 to 0x27 register. Anyway i'm going to test this VGM on real MegaDrive to make sure later today

**Comment by nukeykt** [comment]
Hm, according to MAME YM2608 code CSM mode is enabled using 0x80 data just like YM2612, so i guess datasheet is wrong. Would be nice if someone could verify this on real YM2608 as well

**Comment by nukeykt** [comment]
Sample from real YM2612, aside from tonal difference it's matches to Nuked OPN2 sample. I guess your VGM sets YM2612 rate at 8 MHz?
[realym2612.zip](https://github.com/rerrahkr/BambooTracker/files/3263978/realym2612.zip)

**Comment by jpcima** [comment]
Oh you are correct about CSM, it's an accidental CSM Enable. Thanks.

I came to the same conclusion as you looking at MAME and YM2608 manual.
It's likely specification of register $27 has data bits 6-7 mixed.

The MAME source notes
```
	/* b7 = CSM MODE */
	/* b6 = 3 slot mode */
```

Judging from this, probably BT needs to set $40 not $80 for FM3ch.

@rerrahkr can you check behavior on real chip?

>Sample from real YM2612, aside from tonal difference it's matches to Nuked OPN2 sample. I guess your VGM sets YM2612 rate at 8 MHz?

Yes BambooTracker uses clock defined as `3993600 * 2`.

**Comment by rerrahkr** [comment]
[wav.zip](https://github.com/rerrahkr/BambooTracker/files/3266556/wav.zip)
I checked on real YM2608 and found Nuked is right (real_0x80.wav).
I'm sorry I didn't try it with real chips.

I also check the sounds in setting 0x40 to 0x27 register, and they sound the same.
(mame_0x40.wav, nuked_0x40.wav, real_0x40.wav)

I did not know the datasheet is wrong, I will fix it soon. Thanks @nukeykt and @jpcima!

**Comment by rerrahkr** [comment]
I fixed it at 729c56cf86a5fc86853afb93cc8b0832a5987923. Closed.

**Comment by jotego** [comment]
Hi @rerrahkr , could you please attach the VGM file you to produce this effect to issue #85, please?

**Comment by rerrahkr** [comment]
@jotego [tests.zip](https://github.com/rerrahkr/BambooTracker/files/4792667/tests.zip) - this contains 2 vgms that set 0x40 (actually 0x42) or 0x80 (0x82) to register 0x27.
