### ISSUE TITLE
Issues regarding effect 0Sxx.

### ISSUE THREAD

**Issue by scarletbullgon** [rerrahkr/BambooTracker#134]
Basically, if xx has a number which is equal or higher than the value set in the song's speed, the effect basically won't cut the note. This problem also affects the 0Gxx effect.

Here's the module to test the issue:
[SxxEffectProblem.zip](https://github.com/rerrahkr/BambooTracker/files/3263289/SxxEffectProblem.zip)

As shown in here, the speed in this module is set to 4; any notes which have the effect set as 0S03 or lower than the aforementioned value will cut off normally.

**Comment by rerrahkr** [comment]
Thanks for your report. Delay effects (0Gxx, 0Sxx, 0Txx, Mxyy) is valid only at declared step. If you want to specify the delay length beyond the range of the step, please change the declared position of the effect.

However, I feel a bit inconvenient at present, I will fix it if possible.

**Comment by rerrahkr** [comment]
I changed effect execution routine at 591a6695a9c4a2193f70e604e323c8d8f21e2f57 and 01ef15393671d4b4e6ae8b999a41a50037db049d, that 0Sxx, 0Txx, Mxyy can execute over steps.
