### ISSUE TITLE
vector::_M_range_check error when trying to open file

### ISSUE THREAD

**Issue by elohimf** [rerrahkr/BambooTracker#135]
After opening one of the demos (lotus I believe), I tried to create a simple pattern, with a single FM instrument, along with Bass Drum and Snare channel instruments. I then saved the file. I got no errors and BambooTracker didn't crash. However, when I try to open the file again, I get this error 
![error_screen](https://user-images.githubusercontent.com/18728302/59092575-7e4f8e80-88d7-11e9-80dc-2925943de177.png)

I'm not exactly sure what caused it, as BambooTracker didn't crash, and closing the error and opening another file works fine. I tried to create an empty module, saving it and opening it again. This empty module works without issues, so maybe there was an issue with the instrument?

For reference, here is the file:
[Waiting..zip](https://github.com/rerrahkr/BambooTracker/files/3265180/Waiting.zip)

I'm using BambooTracker 2.0 compiled from master (just checked out today), 
Linux Kernel 5.1.7-arch1-1-ARCH, Archlinux.

**Comment by jpcima** [comment]
@rerrahkr a hint to save you some debugging time,

it seems the loader is loading 2 bytes here (version condition not matched);

https://github.com/rerrahkr/BambooTracker/blob/96642fca1af314263c2ff1d23493f19f4457c63c/BambooTracker/io/module_io.cpp#L1799-L1801

on the saving routine side, it writes 4 bytes.

https://github.com/rerrahkr/BambooTracker/blob/96642fca1af314263c2ff1d23493f19f4457c63c/BambooTracker/io/module_io.cpp#L249-L250

It seemed to advance by the wrong offset for this block.

**Comment by OPNA2608** [comment]
Judging by the [message of the commit that added the version check and removed alot of the com.data writes](https://github.com/rerrahkr/BambooTracker/commit/034a4b2e4b7bf9263bf86fef78b56b3bb84f93e9), it appears the FM Envelope Parameter section was forgotten.

It's prolly best to fix this in a new format subversion, fix the loading procedure for the affected versions to deal with this and update the format documentation of the affected versions to point out the mistake then, for the sake of compatibility?

**Comment by rerrahkr** [comment]
Thanks for reports.

> it appears the FM Envelope Parameter section was forgotten.

Yes, I missed to delete the line. Sorry, it's my mistake.

> It's prolly best to fix this in a new format subversion, fix the loading procedure for the affected versions to deal with this and update the format documentation of the affected versions to point out the mistake then, for the sake of compatibility

I agree, I will fix it and change the module format version to v1.2.2.

**Comment by rerrahkr** [comment]
I fixed it at b4c011ef299852f9b485df31ec529c954e1e7e1e.

**Comment by elohimf** [comment]
Thank you! I can confirm it works, I'll close the issue.
