### ISSUE TITLE
[Idea] Support for more instrument bank formats?

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#136]
Currently, only WOPN bank format is supported.
But I think, it would be possible to implement loading instruments from VGMs, S98s or MUCOM88 .dat files and maybe more?

**Comment by rerrahkr** [comment]
Thanks for your request. It would not be difficult to implement it.
I think that I make the tracker's own bank file at the same time.

**Comment by jpcima** [comment]
When I have implemented the banks initially, I have thought of `AbstractBank` to permit future formats.
It's especially because WOPN does FM only whereas BTI permits a lot more, but beyond that I have not thought necessarily beneficial to add every format under the sun.

With regards to instrument collections I thought of ideas which I considered as useful.
- allowing to hear a preview of an instrument from the set before importing it,
- shipping an example set of FM instruments

**Comment by papiezak** [comment]
>With regards to instrument collections I thought of ideas which I considered as useful.
shipping an example set of FM instruments

I have a huge collection of FM instruments, so I assembled a small set of examples, both FM and SSG - 
[examples.zip](https://github.com/rerrahkr/BambooTracker/files/3317220/examples.zip), @rerrahkr if you like that idea, you can take it 😉

**Comment by rerrahkr** [comment]
I made the BambooTracker bank file format at 9a41efe5ea71ce0516f9d7bc9b143e7684fba1c1.
@papiezak thanks your instruments! I will make a bank from them.

**Comment by rerrahkr** [comment]
I created bank files and confirmed that it works well.
And @papiezak , would you mind me distributing banks created from your instruments as sample data?

**Comment by papiezak** [comment]
@rerrahkr Feel free to do whatever you want with it.

**Comment by rerrahkr** [comment]
Thank you for letting me use it!

**Comment by papiezak** [comment]
There is a problem with my SSG bank, one of instruments (named "SSG" seems to be corrupted and it prevents loading the rest of instruments. 
`Could not load the instrument. It may be corrupted.`
However the rest of instruments when chosen separately load and work fine.

**Comment by rerrahkr** [comment]
Thanks for your report.
"SSG" uses the wave form sequence without changing it from default. The tracker skips exporting the sequence to the bank if there is no change in it. On importing the bank, the tracker cannot find the sequence from the file, so throws an error. I will fix it soon.

**Comment by rerrahkr** [comment]
I fixed the function checking whether instrument properties are edited or not at c91dfbe5b4a7bb1da11f69f5c00f8019a1f957d4.

**Comment by papiezak** [comment]
That fixed the problem, thanks!

**Comment by freq-mod** [comment]
Hello, now that ADPCM is finally supported, would you be intersted in demonstrational .btb ADPCM instrument bank?
[ADPCM.zip](https://github.com/rerrahkr/BambooTracker/files/4557121/ADPCM.zip) -17 instruments (11 drums + 6 melodic). bank size is rather big, mainly because BT doesn't support sample loop points yet, which would allow me to shorten some samples and apply envelope to some. All of them are 16 KhZ as well.

**Comment by rerrahkr** [comment]
> BT doesn't support sample loop points yet

Are you assuming something like OpenMPT's Sample editor?
YM2608 cannot set a loop point in the middle of a sample. It is  only possible to choose whether loop the entire sample or not. Also, changing the sample start address during playback is unstable.
It could be possible to create a loop point in software and then expand and store the looped sequence in the actual sample memory, however, this complicates the management of the sample memory by the user.

**Comment by freq-mod** [comment]
>Are you assuming something like OpenMPT's Sample editor?

For example. But if it's impossible, then OK, nevermind.

**Comment by Technomancer00** [comment]
Speaking about instrument bank formats again; one format I would love to see support for is VOPM.

**Comment by freq-mod** [comment]
@Technomancer00, partial support for VOPM is already here, since .OPM files are textual, you can:
- open one of these in any text editor, 
- copy an instrument data (only one at the time), 
- open BambooTracker and create new FM instrument
- in instrument editor, paste your VOPM patch data with right click -> "paste envelope data from" -> VOPM

**Comment by rerrahkr** [comment]
and [BambooCopy](https://github.com/nobuyukinyuu/bambooCopy) also helps well to import instruments from .opm files.

**Comment by Technomancer00** [comment]
I have tried both of those methods and neither of them seem to work for .OPM files ripped from Hoot Voice Ripper.  Here I have linked a few files that show an error when pasting an instrument from text into BT and crashes BambooCopy when I try to copy.
[Sol-Feace YM2151.zip](https://github.com/rerrahkr/BambooTracker/files/4669331/Sol-Feace.YM2151.zip)

**Comment by freq-mod** [comment]
.OPMs generated by hoot voice ripper must have comments removed from them:
@:0
LFO:   0  64  64  0    0
CH: 64  7   0   0   0  127  0
M1: 24   8   0 10   3  27  0   1   4   0      0
C1: 26   8   0 10  15   7  0   1   4   0      0
M2: 26   8   0 10  15  17  0   1   5   0      0
C2: 26   0   4 10   0   2  0   2   1   0      0

Maybe it is possible for BambooTracker to detect and ignore comment lines, so there will be less hassle when importing presets.
As for BambooCopy, the same - when removed comments, where was no crash. I think one should open the issue ticket about that bug.

**Comment by Technomancer00** [comment]
THANK YOU SO MUCH!  This solves a lot of issues for me!

**Comment by OPNA2608** [comment]
I'd like to ask for PMD's .FF bank format to be added. Should be incredibly easy to implement, but I fiddled around with it awhile ago and wasn't quite able to add it to BambooTracker myself.

You can find (unofficial) specs [here](https://raw.githubusercontent.com/OPNA2608/libopenpmd/master/docs/ff.txt).
(What's not mentioned there: Completely blank instrument entries [all `0x00`s] means the ID is unset and could be ignored by BT, and the instrument label is right-padded with `0x00`s if required)

And [here](https://cdn.discordapp.com/attachments/592900670391189528/643985700831625231/TOHO.FF)'s a sample.

**Comment by rerrahkr** [comment]
BambooTracker supports PMD .FF file from 9645951a961570d07d29cb5d61f961a1f9a107eb.

**Comment by rerrahkr** [comment]
> implement loading instruments from VGMs, S98s or MUCOM88 .dat files

It's been a while, but BambooTracker supports the import of MUCOM88 voice files from 70f9e614fdbb5197a31d7e57f200098a5a3dffd6.

With regard to VGM and S98, they are sound log file and not instrument bank, so I think it is inappropriate to support them as a "bank import". It is desirable to create a separate tool for the purpose of extracting voices from song data.

**Comment by freq-mod** [comment]
Well, you may be right... There are already programs that extract FM data from VGMs (OPN Bank Editor, for example)

**Comment by rerrahkr** [comment]
> There are already programs that extract FM data from VGMs

Is there a tool to do that for OPNA songs? It didn't exist as far as I could see, so I was thinking of making a new one.

**Comment by freq-mod** [comment]
OPN Bank Editor, as I mentioned. It's veeery far from perfect, doesn't work with YM2203 VGMs, but YM2608 FM kinda works.
Also, @kuma4649 MDPLayer allows you to see FM parameters during playback

**Comment by rerrahkr** [comment]
Now I plan to make YM2608 Tone Editor import instruments from VGM, S98, etc. with a bank support and features mentioned in #150. How about this?

**Comment by freq-mod** [comment]
Sounds nice. Is there going to be support for SSG and ADPCM instruments?

**Comment by rerrahkr** [comment]
YM2608 Tone Editor is intended for general-purpose applications not limited to trackers, so we will be able to edit only FM envelope, considering MML users.
Since the processing to change per tick such as FM arpeggiator requires rewriting the audio routine significantly, implementation is postponed (of course for the above reasons).

**Comment by freq-mod** [comment]
Still, considering MML, editing SSG envelopes would be desirable feature

As for ADPCM, maybe a possibility to create and edit .PVI, .PPC or other sample banks in the future
