### ISSUE TITLE
Panning is reversed

### ISSUE THREAD

**Issue by rerrahkr** [rerrahkr/BambooTracker#138]
I noticed `0801` (pan right) executes as pan left, and `0802` (pan right) does as pan right. These effects behave correctly in real chip through SCCI, however, they are reversed in MAME and Nuked emulations.

**Comment by jpcima** [comment]
It's curious, but this was not the case for me. I have tried on FM and drum columns.
`0801` has panned right and `0802` left, same as the Effect list window indicates.
I have reverified at software-level using a signal analyzer program, and it has confirmed the observation.

**Comment by rerrahkr** [comment]
I checked panning to export to vgm and play on [WebVGM](http://www.wothke.ch/webvgm/),  its behavior was correct. It seems WebVGM uses the source code of VGMPlay like BambooTracker, so I would make some mistake during sample mixing. I will check more.

**Comment by rerrahkr** [comment]
This bug was caused by insufficient stream buffer initialization. I fixed it at bf12cb2fe953fa8bf8f70622c5975513fc254f14, thanks for your help.
