### ISSUE TITLE
Inheritance-based UI for instrument and pattern reuse?

### ISSUE THREAD

**Issue by nyanpasu64** [rerrahkr/BambooTracker#14]
Currently bambootracker, like ft, seems to use per-channel pattern indexing. If I use the same pattern in multiple order-rows, I frequently end up changing music I wrote previously (almost universally *above my current position*) and did not intend to change.

I also sometimes make the same mistake when reusing instrument sequences.

## BambooTracker

- Pressing Insert multiple times in order editor results in pattern numbers "0,6,5,4,3,2,1". Maybe Insert should move to next order-row.
- All instruments default to sequence 0. (At least I appreciate the "Users: ..." field)
- Pressing Esc doesn't close instrument editor (bug or intentional?)

## Inheritance

(Basically these are ideas I wanted to implement into j0cc-ft, but never got around to doing the refactoring. Hopefully this codebase is newer and easier to work with. I can help write the code if you want.)

You can substitute order/instrument and pattern/sequence:

My ideas is that each order `orders[i0]` "owns" an array of patterns/sequences. To reuse one order's pattern, the other order `orders[i1]` "inherits" the pattern `orders[i0][chan]`.

My concept for inheritance/references is that `orders[i1][chan]` is a `Union[pattern, another order]` (tagged union, sum type, std::variant, etc).

- Simple approach: Set `orders[i1][chan] = Ref(i0)` for some optional `Ref` wrapper class.
- To allow for reordering `orders[]`, maybe `orders[i0] == uuid0` and refers to `patterns[uuid0][chan]` for all chan.
    - `patterns` is a `hashmap[uuid] -> hashmap/list[chan] -> pattern`. IDK if you use enums or strings/etc. as channel numbers.
    - If (for specific chan) pattern `[i1, chan]` inherits from `[i0, chan]`, `orders[i1] == uuid1` and `patterns[uuid1][chan] == uuid0` and points to `orders[uuid0][chan]`

### My experiences with FT

This solves the issue where I create several instruments which all share sequence 0, then I enable/edit sequence 0 multiple instruments. (In 0CC, I can workaround by pressing "select next empty" whenever enabling a checkbox.)

This also solves the issue where adding an expansion chip defaults to all `order[row][chan] = 0`. (Which could be solved easily by setting `order[row][chan] = row`.)

0CC has "populate unique patterns" and "merge duplicate patterns". Often I reuse pattern 0 (with volume/effects) in multiple places, populate unique, then only change volume/effects in 1 place but not all copies. (I just did this a few days ago).

## Avoid automatically modifying parent when editing child

When writing patterns, I often edit a lower pattern and accidentally mangle a higher one (earlier in time, composed earlier). (I don't know if I often edit an above pattern and accidentally mangle a lower one).

When copying instruments, I used to shallow-clone an instrument and edit the copy, mangling the parent. (Now I *usually* deep-clone, but sometimes I still make this mistake and open the file in another 0cc window to recover my unmodified instrument. I wish instrument undo existed.)

- Solution: Clearly mark inherited patterns using a different background color (both in order table and pattern editor?).
    - Idea: Should parent patterns be marked as well? I don't know if accidentally editing the parent and mangling a child happens often, or if deliberately editing all similar tracks is more likely.

Editing children should not change the parent. Choices:
- Copy on write? Any change to child pattern creates a distinct pattern.
- Extensible children? (more applicable to patterns than instrument seqs)
    - Append extra effects into existing rows. Effects only exist in child, and add to (do not overwrite) existing effects.
    - Erase specific cells (effects).
    - Alter notes (I don't like this idea).

**Comment by pinobatch** [comment]
Minimal viable change: "Clearly mark inherited patterns" + keyboard shortcut for converting a pattern column or instrument to a unique copy would do a lot of help by itself.

**Comment by jimbo1qaz** [comment]
What happens when you delete a parent instrument/etc.? Or "deparent" it so you can change it without altering others?

- Use numerically first instrument as first-parent.
- Detach all children

**Comment by rerrahkr** [comment]
I'm sorry to reply after a long time too.

> * Pressing Insert multiple times in order editor results in pattern numbers "0,6,5,4,3,2,1". Maybe Insert should move to next order-row.

Basically, I was aiming for "FamiTracker of YM2608", so the operation is intentionally the same as FamiTracker.

> * All instruments default to sequence 0. (At least I appreciate the "Users: ..." field)
> * Pressing Esc doesn't close instrument editor (bug or intentional?)

These two proposals have been adopted.

The idea of inheritance was not adopted because it was expected to be difficult to manage internally.
