### ISSUE TITLE
Wrong values for Detune when importing DMP instruments?

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#140]
Very similar to #88, DT values in Deflemask's instruments are translated when loaded in BambooTacker like this: 
![dt defle](https://user-images.githubusercontent.com/32672779/59973372-7a8e5e00-959f-11e9-884f-0f086b1f3aaf.PNG)
Shouldn't "(+)3" value be translated to 3 rather than "6"?

**Comment by jpcima** [comment]
You can tick the configuration option "Show FM detune as signed".

**Comment by papiezak** [comment]
Ah, I forgot about this one, sorry.
Now, Deflemask's +3 is "-2" and Defle's "-3" is 0...

**Comment by OPNA2608** [comment]
Yep, it seems .DMP (file is version `0x0A`, version-dependent?) needs its DT values converted like .TFI does.

**Comment by jpcima** [comment]
It's a correct observation, `convertTFIVGMDT` fixes it.
OPN2 bank editor converts TFI/DMP detune by the same mapping.

**Comment by rerrahkr** [comment]
Ah, I forget applying `convertTFIVGMDT` to dmp's DT. Thanks for reports, I will fix it.

**Comment by papiezak** [comment]
895ea7e fixed it, thanks!
