### ISSUE TITLE
Tracker crashes if Gxx is used with no note

### ISSUE THREAD

**Issue by ImATrackMan** [rerrahkr/BambooTracker#143]
--- -- 0E G02, for example, will crash the tracker instantly.

**Comment by ImATrackMan** [comment]
It also happens if you use it with an effect. --- -- -- P81 G03 also crashes it.

**Comment by rerrahkr** [comment]
Thanks for your report. I fixed note delay effect without note on at 1303a3aa5e0e7bdcd859ceb0d3c31f01e698cfb9.
