### ISSUE TITLE
No volume macro for SSG instruments

### ISSUE THREAD

**Issue by marysiamzawka** [rerrahkr/BambooTracker#144]
When editing an SSG instrument, you're not able to change its volume. This usually can be done when using Tone and Noise waves in other trackers.

**Comment by rerrahkr** [comment]
SSG Envelope controls its volume. Since BambooTracker executes software envelope by changing the value of volume register, you could edit volume sequence macro in "Envelope" tag in SSG instrument editor.

**Comment by rerrahkr** [comment]
I added jam volume settings in sub toolbar at 3595b56fa3b5d6a7e46af011ff27f9dab3af13ad. This set auto-filled value of a step volume, but enable to change an instrument volume used during key jamming (also editing an instrument).
