### ISSUE TITLE
Changing font used for pattern/order editor?

### ISSUE THREAD

**Issue by jimbo1qaz** [rerrahkr/BambooTracker#145]
Low-priority feature request, given that I don't really use BambooTracker. I noticed that the pattern and order font is hard-coded as `QFont("Monospace", 10)`, rather than being configurable in the settings. Do you agree that configurability should be added?

**Comment by rerrahkr** [comment]
Yes, I will try to implement the settings of font and skin in the future.

**Comment by rerrahkr** [comment]
About this issue, the font configuration was added at db4219697c7cd6c4ab135816eb42ff75c802b935.
Thank you for your request.

**Comment by papiezak** [comment]
Tested it a bit, on several occasions this error popup was displayed:
![idk](https://user-images.githubusercontent.com/32672779/67506855-1fc05c80-f68e-11e9-91f1-bfbe26ebc1d0.PNG)
Right now I can't definitely tell how to consistently reproduce this error.

**Comment by rerrahkr** [comment]
> on several occasions this error popup was displayed after font change
I fixed it at ac47b3b9 since I forgot to update some size settings of the pattern editor after font change.
