### ISSUE TITLE
Glitch out while hitting play button on the end of the song

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#146]
Rather minor bug, but anyways:
1. Create a new song
2. Place an 0Cxx (song end) effect at any place in a song
3. Hit play
4. When a song reaches the end, hit play button once again
5. Result is `vector::_M_range_check:__n(which is 4294967295) >= this-size() (which is 2)`
    App doesn't crash, but you can't replay the song, and you can't jam the keyboard (there is no sound).

**Comment by rerrahkr** [comment]
Thanks for your report. I fixed it at 999994ae7d9860c8f9e3e44dd228a4a925c9f75b.

**Comment by papiezak** [comment]
Thanks for the fix!
