### ISSUE TITLE
Unexpected behavior in FM3ch expanded mode

### ISSUE THREAD

**Issue by CommodoreKulor** [rerrahkr/BambooTracker#149]
Awesome tracker, loving it so far. I've noticed some unexpected behavior pertaining new note triggers in FM3ch expanded mode. Attached two files demonstrating the oddities: [Oddities.zip](https://github.com/rerrahkr/BambooTracker/files/3570647/Oddities.zip)

MysteryPorta.btm - Demonstrates a small jingle, first played on a normal FM channel and then on op 1 on channel 3. I would expect the two to sound the same, but on channel 3 the notes seem to be changing frequency but not retriggering.

RetriggerOnNoteChange.btm - Splits channel 3 into two 2op parts, however the frequency changing in one part appears to retrigger the second part inexplicably. Would expect the "bell" not to retrigger.

**Comment by rerrahkr** [comment]
Thanks for your report. I will check them.

**Comment by rerrahkr** [comment]
They were caused by incorrect mask definitions for controlling key off before key on in extended FM channels. I fixed them at c6be6e338b7d6b28fa1203b4ee31cf0f9a0de0fe.
