### ISSUE TITLE
Idea: Early Note effect, variable row density, and multiple rows at same time?

### ISSUE THREAD

**Issue by nyanpasu64** [rerrahkr/BambooTracker#15]
More unused j0CC ideas:

- Early Note effect `^xx` similar to 0Gxx but reversed
- Define regions where row density is increased *= 2 (for 1/8 beat) or 3 (triplets) or 3/2 (triplets but possibly harder to implement and keep aligned when the region ends)
- Multiple rows at the same time, but affected independently by 0Gxx or ^xx.
    - unsure if useful in bambootracker. definitely would be useful for manipulating nes dpcm delta-counter.

**Comment by Pigu-A** [comment]
Those changes will require a lot of CPU time for lookaheads in the player routine, are you sure about that?

**Comment by jimbo1qaz** [comment]
If the author doesn't like the ideas they doesn't have to include them.

Are you planning a native-code driver, not just vgm export? What cpu model do you emulate?

You could precompute MIDI-style "event, nticks until event" tuples when exporting (which could even save space on sparsely-populated regions) which should reduce cpu overhead to one decrement+check per channel*tick (if no events). Though this idea doesn't handle "early note" effects occuring at the start of a pattern (which is a scenario I wanted to use on 0ccft, https://youtu.be/hfbfl0MlIAU has lots of early guitar).

**Comment by Pigu-A** [comment]
Yeah, I'm planning to write a driver for MSX, PC-88 and PC-98 once the tracker is more established. I also wanted it to directly take .btm files because those computers already have DOS for this.

**Comment by rerrahkr** [comment]
I'm sorry I got a reply after a long time.
I tried to implement the early note effect, but I gave it up because the step size was variable depending on the tempo and it was very difficult to calculate the trigger position in real time.
Also, since BambooTracker is designed to behave as much as possible with existing FamiTrackers, the rows have a fixed (partially variable) density.
