### ISSUE TITLE
[Idea] Option to remove duplicate instruments 

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#150]
It would be useful to me, given the support of banked formats.
Currently, there are no .btb bank managers, OPN Bank Editor doesn't support it yet.
For example - right now I'm dumping instruments from certain PC-98 game and making a .btb bank out of it. That game has many tracks, instrument count already surpassed 60, it starts to get hard to keep track of what was already dumped. So, if there are any duplicates it would be much easier to deal with them with such feature.

**Comment by rerrahkr** [comment]
Thanks for your request.
Whether is its editing performed on the bank file or the instrument list? If you want to edit a bank file, the purpose of the application is different, so I think it is better to create a new bank editor separately from the tracker. If editing in the instrument list, it may be implemented as a module optimization function.

**Comment by papiezak** [comment]
>Whether is its editing performed on the bank file or the instrument list?

To be honest, I was thinking about both options, yet I would be fine with just in-tracker instrument list function. Creating a new bank editor is also a neat idea, though.

**Comment by papiezak** [comment]
Regarding a separate bank editor, I have a question - do you plan further development of your YM2608 Tone Editor? If yes, would it be possible to add .btb support into it, together with this option?

**Comment by rerrahkr** [comment]
There are currently no plans to develop YM2608 Tone Editor, but it is technically possible to support bti and btb.
Now I have a plan that removing duplicate instruments is implemented as the instrument optimization in the tracker.

**Comment by rerrahkr** [comment]
I added this feature at 285ae558d35ad33fec9cc23f2f51f169ffb57db6. You can remove duplicate instruments in the menu bar Module → Cleanup → Remove Duplicate Instruments.

**Comment by papiezak** [comment]
Tested and works very well. Thank you!
