### ISSUE TITLE
std::weak_ptr::lock() called repeatedly while drawing patterns, performance issue?

### ISSUE THREAD

**Issue by jimbo1qaz** [rerrahkr/BambooTracker#151]
I'm writing my own tracker, possibly in C++ and Qt. I'm currently writing my own pattern editor, and was studying BambooTracker's codebase when I found some unusual code.

`PatternEditorPanel::palette_` is a `std::weak_ptr<ColorPalette>`. The PatternEditorPanel implementation repeatedly calls `palette_.lock()`, multiple times in drawRow() and in drawStep().

I'm not sure what's the speed impact of calling `palette_.lock()` repeatedly is. You're probably creating and destroying shared_ptr every time you call that method, and twiddling refcounts every time, which could be Python levels of slow?

Would it be better to make it a shared_ptr? Or call `palette_.lock()` in `PatternEditorPanel::drawPattern` so you only need to twiddle the refcounts once per full-screen redraw?

**Comment by rerrahkr** [comment]
Thanks for your advice.
I haven't measured the cost time, but as you said, I think it was a waste of time to generate `std::shared_ptr` using `std::weak_ptr` whenever calling `palette_`.
`ColorPalette` is refered from pattern editor, order list, instrument list and instrument editor. In these parts, it is inconsistent whether to hold the palette as `std::shared_ptr` or `std::weak_ptr`.  I will change all references to the palette to `std::shared_ptr`.

**Comment by rerrahkr** [comment]
I fixed them at 136f6d510e899413bebe6977bb13af3aba6a76c8. Thanks.
