### ISSUE TITLE
Timbre of certain SSG instruments change between key-ons

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#153]
Maybe it's not a bug, but still...
While playing around with SSG instrument editor, I accidentally created an instrument that displays somewhat bizarre behaviour - while jamming, most of the time it is a square wave going down in pitch, but on some occasions it will produce a vibrating, pseudo triangular wave-like sound. Tested on `master` branch only so far.
[ssg.zip](https://github.com/rerrahkr/BambooTracker/files/3665744/ssg.zip) - zip file that contains instrument in question, module displaying alternating timbre behaviour and wav sample in case of problems with reproducing issue.

**Comment by rerrahkr** [comment]
Thank you for your report.
This was the reason that the hardware envelope was not set correctly under certain circumstances. I fixed it at 32d2f2708bd35405f2183507f97032d867d0815e.

Probably I forgot to describe the execution of sequences: if you use buzzer effect waveform (triangle, saw, ...) and hardware envelope, only waveform sequence is executed, because buzzer effect uses SSG hardware envelope and has the priority to use it.

**Comment by papiezak** [comment]
Tested it, now it doesn't occur in module, but when jamming keyboard, it's still here. Instead of vibrating triangle buzzer, it produces either vibrating square or some weird, phaser like sound.
(audio recording - https://vocaroo.com/i/s1jxAEiBga7j)

**Comment by rerrahkr** [comment]
It does not occurred in my Windows 10... 🤔 
I checked your audio waveform, and I found it was like square-masked triangle. It seems that the switching process of hardware envelope is not working properly.

**Comment by rerrahkr** [comment]
Are you doing key on with multiple keys while jamming? Since Only 1 note can uses hardware envelope, if you key on multiple notes, the sounds will interfere and the waveform and envelope sequence will not work properly.

**Comment by papiezak** [comment]
No, waveform gets glitched even when pressing only one key repeatedly.

**Comment by papiezak** [comment]
Forgot to give feedback, but just changing hard envelope flag clear (abb9aab) was enough to fix that issue, key-ons give now the consistent, same result. Thanks!
