### ISSUE TITLE
[Bug] Songs are not played from beginning if previous song was loaded. 

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#154]
This bug doesn't happen all the time, but:
1. Load a song (for example "Lotus.btm", then, again for example go to order 07)
2. While song plays, load another song
3. With any luck: either song after pressing play button will start from order 01, or even the same order the previous song was at. Results vary between takes, it's random.

**Comment by rerrahkr** [comment]
Thank you for your report.
That was happened because the audio thread changed the cursor position at the wrong time. I fixed that at 88da2d8c12ec86c7d0b7f34ace7661b05c5509a4.

**Comment by papiezak** [comment]
Thanks for the fix!
