### ISSUE TITLE
Low latency audio

### ISSUE THREAD

**Issue by Kashouryo** [rerrahkr/BambooTracker#157]
Currently, when using a midi keyboard on Windows, I can notice a slight delay between keypress and audio. This is because of the delay of windows default audio. It will be nice to have ASIO or WASAPI support on Windows builds to decrease the audio latency.

ASIO and WASAPI on OpenMPT:
![image](https://user-images.githubusercontent.com/37679684/67155458-0c07a580-f2de-11e9-8c50-1df5ec006dda.png)

**Comment by rerrahkr** [comment]
Thank you for your request.
BambooTracker uses RtMIDI for MIDI input, but it supports only Multimedia Library on Windows. To make WASAPI or ASIO available, it is necessary to change to another API.

**Comment by Kashouryo** [comment]
Looks like a big change is required to make this happens! The audio lanetcy of Windows 10 was already around a few ms(that's a huge improvement compares to Windows 8). And I found that bambootracker is still usable under that latency. Thank you for the information!
