### ISSUE TITLE
Pattern no. 00 gets duplicated in the order list

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#158]
Cosmetic bug that seems to be intruduced recently, I don't remember encountering it previously:
1. Create a song that is two patterns long
2. Play it, after it is done second pattern instead going to beginning duplicates first pattern as the third one, at least in the order list. When it plays that duplicated pattern, it goes to pattern 01, and order list displays everything correctly once again - two patterns.

Hovering the mouse cursor over order list when duplicated pattern 00 is played, makes it disappear.
[fury.zip](https://github.com/rerrahkr/BambooTracker/files/3760926/fury.zip) - early WIP song remix that shows the bug and screenshot of duplicated pattern.

**Comment by rerrahkr** [comment]
Thank you for your report.
There were an insufficient check of repaint type in the order list. I fixed it at 387c6e6f467555a80815d0289998be480e921d32.

**Comment by papiezak** [comment]
Thanks for the fix!
