### ISSUE TITLE
Crash to desktop when solo'ing track during playback

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#159]
Another bug, this time more severe - when playing song, and double-clicking on any channel track head program silently hangs and crashes to desktop.
OS is Windows 10.

**Comment by rerrahkr** [comment]
Thank you for your report again.
Since the null pointer reference was occurred in FM envelope reset check, I fixed it at b72904e8f3a3560b9979778d5e7feee25696e286.

**Comment by papiezak** [comment]
Thanks once again!
