### ISSUE TITLE
White box blocks part of application, minimize, maximize, and exit buttons unworking

### ISSUE THREAD

**Issue by Drillimation** [rerrahkr/BambooTracker#160]
The application was working for just a few days, and then it apparently malfunctioned, now the application is blocked by a white box making the app unusable. Also, in that case, the minimize and exit buttons also don't work when this happens.

Also, I want a note retrigger effect in a future update.

**Comment by rerrahkr** [comment]
Thank you for your report and request.

> the application is blocked by a white box making the app unusable.

I have never seen such a bug in my Windows 10. Could you tell me what tracker version and OS you are using? And if you remember, could you tell me what you were doing on the tracker before the bug happened?

> I want a note retrigger effect

I interpret a note retrigger effect as the effect that does key-on the previous note again, is this right?

**Comment by Drillimation** [comment]
Nevermind, I solved the problem. Restarting the machine appeared to fix it. And yes, I want an effect that retriggers based on the number of ticks. Also, I want a tutorial on how to recreate the SSG percussion in the PC-98 Touhou games.

**Comment by rerrahkr** [comment]
If the key is turned on and off in units of ticks smaller than the step, this can be done by reducing the "speed".

About the PC-98 Touhou games, they uses SSG and rhythm channels for percussion prepared by PMD. I used to try to reproduce them from [the source of PMDWin](https://github.com/mistydemeo/pmdmini/blob/2f38a55a8f3a91ca0a7b6aed9b0f35a491da9626/src/pmdwin/table.cpp#L268-L324) and used them ([video](https://youtu.be/K3auYpm1STw)).
Bass drum, Snare drum, Snare drum 2 and Crash cymbal I made was distributed as "Bass Drum 2", "Snare Drum 2", "Snare Drum 3" and "Crash Cymbal" in demos/instruments/Rerrah/SSG.btb.

**Comment by Drillimation** [comment]
But I don't know how to open .btb files.

**Comment by rerrahkr** [comment]
You can open .btb to drag and drop the file. You also choose instruments to load in select instruments dialog displayed after opening .btb.

**Comment by Drillimation** [comment]
Thank you. I don't know how to up the volume in the SSG. Is there any way on doing it?

**Comment by papiezak** [comment]
>how to up the volume in the SSG. Is there any way on doing it?

File => Configuration => Mixer tab, thre are slider for controlling FM and SSG volume attenuation.
Then, Module properties => "Mixer" section, set it to "custom".

**Comment by Drillimation** [comment]
[Lifelight.zip](https://github.com/rerrahkr/BambooTracker/files/3817478/Lifelight.zip)
Thanks for all that advice! In fact, I made my first song cover above using it. The FM instruments were really easy to recreate; I just copied them from the MML based on Touhou music that others have covered.
