### ISSUE TITLE
Repaint-related corruptions (?)

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#161]
Discovered just now.
1. Load any song. Toggle off some tracks (for example, rhythm channels)
2. Some rows won't be blacked out, pattern cursor progressing through the pattern will black them out, but as the next one starts playing, again portion of it will not be blacked out.

Also, sometimes when loading another song with some channels turned off, the "vector" error message will pop up, and order list, or entire pattern editor will be pitch black. Loading yet another song while in this state will freeze the tracker completely. This however doesn't occur every time.

**Comment by rerrahkr** [comment]
Thank you for your reports.
Sorry, I forgot to repaint track masks after changing an order in the playback at 359762f6283dd152a99c5945137c71fb486e4d9f. I fixed it cc5566fdfb7973d96157d4e1068571f7b10538d8.
Next I try to fix the error during opening the module.

**Comment by rerrahkr** [comment]
In 1a1ec48e6df333cbfefa273533205fc6c11c0cdd, I change the current pattern position to be initialized before loading the song. I tested the tracker and it seems to be no problem about loading song.

**Comment by papiezak** [comment]
Looks like it's fixed, thanks!
