### ISSUE TITLE
[Request] Improve pattern/order managing

### ISSUE THREAD

**Issue by pedipanol** [rerrahkr/BambooTracker#162]
I've run across some people on chats thinking Bambootracker for some reason didn't let them add new patterns/orders, and didn't figure out by themselves until I told them that Edit Mode has to be on for that to be allowed.

Kwowing that, I think it should be possible to add/duplicate/remove patterns/orders without Edit Mode on, as most other trackers let you that. It would also be nice to have UI buttons to quickly add/duplicate/remove them (but I don't know if you've already planned that).

Also, since the input order of the number columns has been changed (as of request 3 of issue #2 ), I think this should apply to the pattern/order list as well.

Thanks for your hard work on Bambootracker!

**Comment by rerrahkr** [comment]
Thank you for your requests. I will work on them.

**Comment by rerrahkr** [comment]
The requested features are added until 128ca6ffa1fbd252efe6238ed3fb67061bb84720.
I added 5 order edit icons (Insert order, Remove order, Move order up/down and Duplicate order) to the menu bar. They will work like those of 0CC-FamiTracker, so you don't need to toggle jam/edit mode to change the order list.
After the next release, I will revise the wiki to reflect these changes.

**Comment by pedipanol** [comment]
I've tested the dev build and it's perfect, thanks! Closing the issue.
