### ISSUE TITLE
Bug in instrument list

### ISSUE THREAD

**Issue by galap-1** [rerrahkr/BambooTracker#163]
I've discovered a minor bug involving the instrument lists: if there are exactly 11 instruments (the first column is full; 00-0A), and an instrument is cloned or deep cloned, the cloned instrument won't appear until another new instrument is created, and it will be hidden again if that other instrument is deleted.

**Comment by rerrahkr** [comment]
Thank you for your report.
This bug was happened because I forgot to modify the item size of the instrument list when the scrolling direction of the list was changed. I fixed it at 559ba93a145d6238dcbad8600a9876ef69e9e7c2.
