### ISSUE TITLE
SIGSEGV on interaction with removed instruments

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#167]
How to reproduce:

0. Start BT.
The buttons to clone, delete and save the selected instrument are unavailable - as expected.
1. Add new instrument.
The buttons to clone, delete and save an instrument are made available.
2. Load a fresh module.
The buttons stay active.

Pressing either the clone or save button with abort BT with signal SIGSEGV, most likely because there is no currentItem anymore / its reference has disappeared.

```
Thread 1 "BambooTracker" received signal SIGSEGV, Segmentation fault.
0x00005555555a033a in MainWindow::cloneInstrument (this=0x555555bff2a0) at gui/mainwindow.cpp:835
835        int refNum = ui->instrumentListWidget->currentItem()->data(Qt::UserRole).toInt();
```

**Comment by rerrahkr** [comment]
Thank you for your report.
The icon control was not work well after clearing the instrument list, so I fixed it at 297c1d9.
