### ISSUE TITLE
Rendering glitches during low performance

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#168]
On systems / in environments with poor performance (I think), rendering will start to become buggy during playback:

- The active element cursor might get duplicated across several lines.
- Notes and line indices appear at / get cloned to the wrong positions.

Audio stays unaffected by the wrong notes, it is merely the display that is off.

Examples:

- Windows: (VM)
https://cdn.discordapp.com/attachments/519164281518948372/648887164695740426/2019-11-26_21-02-54.mp4
- macOS: (native performance apparently, older macOS version. unrelated crash near end, i think fixed by https://github.com/rerrahkr/BambooTracker/commit/1a1ec48e6df333cbfefa273533205fc6c11c0cdd ?)
https://www.youtube.com/watch?v=UkCGQHE53AA
- Linux: (caused by debugging with valgrind, _very_ slow)
https://cdn.discordapp.com/attachments/519164281518948372/648823980773474307/Peek_2019-11-26_10-49.webm

**Comment by YuzuMSX** [comment]
I have Windows 7 Pro and Decent GPU.

BambooTracker Works but "Still Rendering glitches during Playback for some reason"

Sorry about that

**Comment by rerrahkr** [comment]
Sorry for my late reply.
It seems that asynchronous of the cursor position update and quick pattern drawing.
The glitches happens rarely in my environment, so it seems to take some time to fix it.

**Comment by rerrahkr** [comment]
I fixed pattern drawing method at 020b1e4f9345fc8a1a76a76c08ddc4d3268633c4, which could resolve this issue.

**Comment by OPNA2608** [comment]
It looks like that fixed it in my `valgrind`ed setup, gonna try asking some Windows users to test the AppVeyor build next. I don't have access to a macOS system anymore, I'd ask those folks once the next version gets released if it's fixed for them too.

**Comment by YuzuMSX** [comment]
I tested on my dev Build, now it works without rendering glitches.
a few problems, During playback Still lags then no lag for a couple seconds.

result 61% of cpu

**Comment by rerrahkr** [comment]
Occasionally drawing bugs are issued, but the glitches related to this issue seems to have been resolved since no problem have been reported for half a year. I'll close this issue.

**Comment by OPNA2608** [comment]
Oh sorry, been too busy to remember this. Closing.
