### ISSUE TITLE
Changing font on Windows leads to vector error

### ISSUE THREAD

**Issue by nyanpasu64** [rerrahkr/BambooTracker#169]
I was changing the fonts. I recall I changed both header fonts from "MS Shell Dlg 2" to "Segoe UI" 10. Then I changed both rows fonts from "Courier New" 10 to "Courier Prime Sans" 10, then 11, then Mononoki 10 (which at which point I got the error).

Every time I changed the font, I pressed Apply, not OK. I may have changed the pattern/order fonts not at the same time. I initially used the dropdown and "type to complete". Just before the error occurred, I typed directly into the text box and copy-pasted `mononoki` from the upper "pattern editor rows" font textbox to the lower "order list rows" font textbox.

>An unknown error occured.
>vector::_M_range_check: __n (which is 15) >= this->size() (which is 15) 

The program continued to run after I closed the dialog. I have been unable to reproduce the error since.

Program: BambooTracker 0.3.1 Windows (not XP), https://github.com/rerrahkr/BambooTracker/releases/download/v0.3.1/BambooTracker-v0.3.1.zip.
OS: Windows 10 x64.

**Comment by rerrahkr** [comment]
Thank you for report.
I confirmed the same error when I set "ADMUI3Sm" and some fonts to the order list row text. 15 is the number of tracks, so it is expected that the condition of `for` or `while` about the module track is wrong.

**Comment by rerrahkr** [comment]
It was because I forgot to update the width of order list after changing font. I fixed it at 8546213.
