### ISSUE TITLE
Error message and missing track editor

### ISSUE THREAD

**Issue by bryc** [rerrahkr/BambooTracker#171]
![image](https://user-images.githubusercontent.com/1408749/70869869-2adf8c80-1f5b-11ea-945b-1ea3cce19773.png)

![image](https://user-images.githubusercontent.com/1408749/70869881-3fbc2000-1f5b-11ea-8cd2-3ad5a137643e.png)

Just downloaded latest v0.3.2. Using Windows 7.
I'm not sure what happened, I had the window minimized for less than 5 minutes playing demo song. When I returned, the error message appeared, and the track editor disappeared. The program froze when trying to load a different module.  I also had the SSG instrument editor window open during this.

Seems to reproduce when left alone running.

**Comment by rerrahkr** [comment]
Thank you for your report.
The tracker failed to calculate the pattern drawing position after the window is minimized and showed, I fixed it at e55b46df5865e5d707a3f701c25ce86a535525df.

**Comment by bryc** [comment]
Ok seems fixed to me.
