### ISSUE TITLE
Can't open this file, says it's unsupported even though I'm using a newer version

### ISSUE THREAD

**Issue by Drillimation** [rerrahkr/BambooTracker#174]
I am unable to open the file below, it says the file was made in 1.3.2 and I'm using version 0.3.0.
[Dim. Dream.zip](https://github.com/rerrahkr/BambooTracker/files/4007247/Dim.Dream.zip)

**Comment by bryc** [comment]
It loads fine in latest v0.3.3, but not v0.3.2. You sure it was not made with v0.3.3?

> BambooTracker v0.3.2 does not support module that its file version is 1.3.2.

I think this is an issue of information not being very clear:
- 1.3.2 btm format is not loading on v0.3.2 program version
- Confusion between 1.x.x btm format and 0.x.x program version in message

**Comment by rerrahkr** [comment]
> It loads fine in latest v0.3.3, but not v0.3.2. I think it was made in v0.3.3, but it still saves using BTM v1.3.2 header, but then this file does not load in v0.3.2.

Yes, to open that module, please update the tracker to the latest version.

> I think this is an issue of version information not being very clear

You only need to update the tracker to the latest version, but various types of versions are displayed in the dialog and confusing.
I will change the text of the file version error as `Couldn't load the module properly. Please make sure that you have the latest version of BambooTracker.`

**Comment by bryc** [comment]
@rerrakhr why does it not open in v0.3.2 if the BTM version says v1.3.2?

**Comment by rerrahkr** [comment]
Because BambooTracker v0.3.2 is set to read .btm until v1.3.1.

https://github.com/rerrahkr/BambooTracker/blob/82d0e8cc27a3e99b696a3d2b99cfdd937bf577cd/BambooTracker/version.hpp#L26-L34

The reason why I revised the module specification from 1.3.1 to 1.3.2 is that the tracker needs to change module loading processes considering bugs in old modules (The issue #170).
