### ISSUE TITLE
Unable to lay a C8 note

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#175]
The highest note you can put in a pattern is B7, hovewer with a keyboard you can play an even higher note, C8, but you can't put it in a pattern. When an octave 7 is selected, entire upper row of keys when pressed play that C8 note that you can't lay in editor.

**Comment by rerrahkr** [comment]
Thanks for your report.
Strictly, the highest note on the tracker is B7+pitch 31, not C8. When a higher pitch is input, the tracker rounds pitch to B7+31.
So it seems that I need to fix the highest note to B7 during keyboard entry.

**Comment by papiezak** [comment]
I see. Also, when using 01xx "portamento up" effect, it stops at B7+31 rather than B7.

**Comment by rerrahkr** [comment]
I set the upper limit of pitch B7+31, to perform some pitch effects like detune and vibrato correctly even at B7.

**Comment by papiezak** [comment]
Fixed with  576e0a6, thanks!
