### ISSUE TITLE
[Feature request] Make it possible for the horizontal pattern scrollbar to scroll the view instead of move cursor

### ISSUE THREAD

**Issue by Midi-In** [rerrahkr/BambooTracker#178]
Currently scrolling the horizontal bar under the pattern view does affect the cursor instead of the whole viewport, which is very unintuitive for me. My proposition is to add an option to make the scrollbar behave like a regular view scrollbar.

**Comment by rerrahkr** [comment]
Thanks for your request.
It will scroll by the track due to the implementation.
And the question about the cursor, should the cursor also move when scrolling the screen?

**Comment by rerrahkr** [comment]
I added this feature until 1837e0043a0bc30d91ea95103d0570da6d0cff7a.
View-based scroll is available by unchecking "Move cursor by horizontal scroll" in configuration.

**Comment by Midi-In** [comment]
Thank you!
