### ISSUE TITLE
[Feature request] Jump to next/previous pattern using mouse button 4 and 5 (navigational thumb buttons)

### ISSUE THREAD

**Issue by Midi-In** [rerrahkr/BambooTracker#179]
Pretty much what the title says, jumping back and forth through the sequence order using the navigational mouse buttons woild come in very handy (the same way OpenMPT does that)

**Comment by rerrahkr** [comment]
Thanks for your request.
I have no mouse with XBUTTON (like forward, back button) now, but guessing from the OpenMPT source, XBUTTON1 (back button) is assigned as jumping to the previous order, and XBUTTON2 (forward button) is set as jumping to the next order, is this right?
I'd like to know where is the pattern cursor after jumping (the same number step, head of pattern or other place...)

**Comment by rerrahkr** [comment]
I added this feature at 4e34ed8d7d7e47a8a2598f81514a9975848df0bd.

**Comment by Midi-In** [comment]
Sorry for late reply, i don't check issues that often but to elaborate on this: OpenMPT's behaviour depends on whether the track is being played or not - during playback it will always jump to the beginning of the target pattern, whereas while the song is stopped it will retain the current vertical position, which seems to be the most sane choice for me. Horizonal position (channel) is always retained.

**Comment by rerrahkr** [comment]
Thanks for reply! I also changed the tracker to keep vertical position in changing order at f8e7a51510ca6ef293f7f18acf8a8cf17ebd78e4.
I will test the button behavior with 5 button mouse at a later date.

**Comment by Midi-In** [comment]
Thanks a lot for taking this into consideration!
