### ISSUE TITLE
Idea: Copying settings between FM ops?

### ISSUE THREAD

**Issue by jimbo1qaz** [rerrahkr/BambooTracker#18]
I'm fairly new to FM, just tried using bambootracker, now I'm trying to switch algorithms. Currently alg4 has op2 as one output, but many other algorithms only support op4 as output. Is it useful for people other than me to be able to switch operator settings around?

Solutions:

- Ability to copy all FM envelopes as text: global settings on first line, 4 ops on subsequent lines
    - open text editor and move lines to move operators around
- copy/paste buttons for individual ops?

**Comment by OPNA2608** [comment]
> Ability to copy all FM envelopes as text

![image](https://user-images.githubusercontent.com/23431373/49278670-be940700-f485-11e8-965d-f78e13e07351.png)
> FM_ENVELOPE:0,0,31,0,0,7,0,32,0,0,0,-1,31,0,0,10,0,0,0,0,0,-1,31,0,0,7,0,32,0,0,0,-1,31,0,0,7,0,0,0,0,0,-1

**Comment by jimbo1qaz** [comment]
This does not split separate ops into separate lines or separate them in any way, so I cannot move settings between ops.

**Comment by jimbo1qaz** [comment]
I pushed #20

**Comment by rerrahkr** [comment]
Copy/paste operator was added in 8b80936a7c8f2ad34fd61c5246c99426b55fc817.
