### ISSUE TITLE
Crash to desktop while editing SSG instruments

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#181]
Minor one, but anyway, steps to replicate:
1. Create a SSG intrument
2. Set an envelope, with at least 10 steps
3. Now start jamming keyboard, pressing repeatedly one key while shortening envelope lenght
4. Tracker will hang, then crash to desktop

Works also with waveform, tone/noise and arpeggio sequences as well. Discovered accidentally while checking envelope behaviour after 6177e5c

**Comment by rerrahkr** [comment]
Thanks for your report. There were illegal memory accesses to instrument sequences, so I add the index check before accessing at 4629bd2697ba5481e8913c3c91607545fb751eae.

**Comment by papiezak** [comment]
Thanks for the fix!
