### ISSUE TITLE
Mouse/keyboard shortcut to change multiple volume or effect values by step?

### ISSUE THREAD

**Issue by nyanpasu64** [rerrahkr/BambooTracker#189]
In 0CC-FamiTracker (possibly FamiTracker too), you can select volumes or effects, then shift+scroll to change all volume/instrument/effect values (not effect names) within your selection. On my computer, you can also press Shift+F1/F2 to decrease or increase by 1, or Shift+F3/F4 to decrease or increase by 0x10.

As far as I can tell, BambooTracker lacks such a feature, with no mouse or keyboard binding to do this. It does have Alt+S to reassign many instruments at once. But when remapping many effects or volumes at once, the absence of this feature requires me to manually change every single volume individually.

Can such a feature be added?

**Comment by rerrahkr** [comment]
Thanks for your request. I didn't know 0CC-FT has such a useful feature, I will add it to BT.

**Comment by rerrahkr** [comment]
I added your request at 469ec74158e373fcbe29a55a399ecd95c0ac4823. I also added Ctrl+scroll to transpose notes at a74a2d16a013b3ad41a6c6f3b69449e0401705f7 that works like 0CC-FT.

**Comment by nyanpasu64** [comment]
If "Reverse FM volume order" is enabled, and you're adjusting volumes, shift+scroll down and shift+f1 increases the number shown on-screen. I don't know the best solution to this.

**Comment by rerrahkr** [comment]
I forgot that the values of FM volume is reversed. Sorry, my mistake. It was fixed at 3fa1609efaefb2aa49773bf4465f094b96ae1d3d.
