### ISSUE TITLE
When "Show FM detune as signed" enabled, instruments with negative detune are copied incorrectly

### ISSUE THREAD

**Issue by nyanpasu64** [rerrahkr/BambooTracker#190]
Procedure:

- Menu, File -> Configuration to open the Configuration dialog. On the General tab, on the left-hand side, check "Show FM detune as signed".
- Try copying and pasting any FM instrument with one or more negative detunes.

Result:

If "Show FM detune as signed" is checked, any detune with negative values are copied incorrectly, and the clipboard has negative values in the detune slot. Trying to paste this clipboard will do nothing, regardless if "Show FM detune as signed" is checked or unchecked.

BambooTracker-v0.3.5.33-dev on Windows 10 x64.

**Comment by rerrahkr** [comment]
Thanks for your report. It came from #88, DT was not converting to an internal value.  I fixed it at c7c1aee61d116f65fbbcde28f73ecf43d82b0683.
