### ISSUE TITLE
When pattern editor editing is disabled, order editor copy-paste doesn't work

### ISSUE THREAD

**Issue by nyanpasu64** [rerrahkr/BambooTracker#191]
I found a confusing behavior in bambootracker.

If the pattern (bottom) editor edit mode is enabled, you can type into the order editor, and copy-paste selections around.

If the pattern editor edit mode is enabled, you can type into the order editor. However, trying to copy-paste selections around will produce note sounds instead.

This is confusing, because the *order* editor cursor is always red when selected, regardless if the pattern editor is in jam (blue) or edit (red) mode. Maybe the order editor should always allow both typing and selection copy-pasting, whenever it's selected.

**Comment by rerrahkr** [comment]
Thanks for your report. This problem was happened because I had not changed those action behaviors in #162. I fixed it at 05ba866887febef1467930382f9622d36fb595b3.
