### ISSUE TITLE
Keyboard Shortcuts for pattern editing

### ISSUE THREAD

**Issue by Xyz39808** [rerrahkr/BambooTracker#193]
I am requesting 3 shortcuts I keep attempting because I use them constantly in FamiTracker:

Ctrl+Left/Right - Move to previous/next pattern but cursor stays on current row.
Ctrl+Up/Down - Change to previous/next instrument.
Ctrl+Enter - Play current row and only current row.

**Comment by rerrahkr** [comment]
Thanks for your request.
Ctrl+Up/Down is currently used to jump to previous/next 1st highlighted step by default. I'm thinking about good ideas about alternative shortcuts.

With regard to key shortcuts, I try to change how shortcuts are handled (related to #192), and it will allow you to change some shortcuts in key configuration.

**Comment by rerrahkr** [comment]
I added them until 1e3f3fe948844c872595ba3e82e017f352825b1f. Changing to previous/next instrument is assigned as Alt+left/right, but other shortcuts are implemented as your request.

**Comment by Xyz39808** [comment]
ありがとうございます
