### ISSUE TITLE
v0.4.0 release has incorrect qt_en.qm translation

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#196]
Inexplicably, the version in the Releases tab has an incorrect translation file for English system dialogues (`lang/qt_en.qm`). It appears to be a byte-exact copy of the German version `qt_de.qm`.

![grafik](https://user-images.githubusercontent.com/23431373/77785947-3ca5f500-705d-11ea-9a35-d21a47f023c3.png)
![grafik](https://user-images.githubusercontent.com/23431373/77786103-87c00800-705d-11ea-81a5-efad3d7431eb.png)

For anyone looking for a quick fix, the dev version on Appveyor has the correct version.
[Extracted translation file here.](https://github.com/rerrahkr/BambooTracker/files/4395193/BambooTracker_v0.4.0.0-dev_en-i18n.zip)

**Comment by rerrahkr** [comment]
Thanks for your report. In my environment, it was displayed in English so I didn't notice this bug. I've just fixed it, would you mind checking it works correctly?

**Comment by galap-1** [comment]
I noticed this as well. I Redownloaded and it is fixed for me now.
