### ISSUE TITLE
allow higher refresh rates

### ISSUE THREAD

**Issue by djmaximum17** [rerrahkr/BambooTracker#198]
Right now it only lets you go up to 99hz. it would be nice to be able to do higher refresh rates up to 400hz.

**Comment by rerrahkr** [comment]
Thanks for your request. Does "refresh rate" mean gui repainting rate, not playback tick rate?

**Comment by djmaximum17** [comment]
its the custom speed in the module properties

**Comment by rerrahkr** [comment]
At 2688b2e01006ef467ef5217a1c5c058a8596ba8f I changed it to 511Hz, it's a better round number.

**Comment by djmaximum17** [comment]
I wouldn't mind if it gos to 999hz
