### ISSUE TITLE
DC offsets when loading module that contains ADPCM samples

### ISSUE THREAD

**Issue by galap-1** [rerrahkr/BambooTracker#199]
When a module is loaded that contains ADPCM samples, some of the samples when played back often have DC offset popping in them. Loading or creating another ADPCM instrument fixes the issue until the program is closed.

It may only occur for longer samples, or occur more often for them, but I'm not sure. I've attached a module with a sample where it often happens. It doesn't happen every time the program is loaded, and when it does the popping does not have the same timing or magnitude.

[DcOffset.zip](https://github.com/rerrahkr/BambooTracker/files/4397897/DcOffset.zip)

**Comment by rerrahkr** [comment]
Thanks for your report. This bug seems to happen after loading the module.
As far as I checked, that offset no longer occurs after the sample loading timing was changed in 9b6bd57f6f6bef9db06bf0563503282e5a00be61.
