### ISSUE TITLE
A few requests to make the usability better

### ISSUE THREAD

**Issue by pedipanol** [rerrahkr/BambooTracker#2]
You've probably thought about some of them but just to reinforce

**1 - A way to remap key commands**
I use a laptop without a numeric pad, so I don't have access to the default keys to change octaves, also for me it's not intuitive to have - as a key-off

**2 - Volume commands**
While I know that the TL values on FM makes lower numbers louder, most FM editors I know account for that and make reverse this order. I think your tracker would really benefit from it, mainly considering the SSG and RHY have louder values on higher numbers as well.

**3 - Change the order of input for columns that require 2 digits**
Considering the SSG and most effect commands use just "00-0F", I think altering the last digit with the first input would make it faster to use, so one just needs to input 1 digit to achieve the effect. Deflemask handles this well.

**4 - Instrument editor**
I really like how it looks and how it works, but it's hard to input precise numbers on the values that have more of them, like DR/SR and TL. A way to either slow down the cursor (like pressing CTRL on VOPM) or just letting me input directly the numbers would fix it.

As a side note: please make the tracker able to load .OPM and .TFI files, those are the most common FM sound formats, OPM is text-based so it should be the easiest to inplement.

**5 - Envelope Reset**
The OPNA doesn't reset the envelopes by default before key-off so I think this is a nice feature, but turning the option off will just make every note legato, rather than not resetting the envelope. I think legato should be a different option from envelope reset.

-----

I really liked your tracker and I'm surprised on how much it has for a first release, I hope you'll continue to improve even further! (I also hope you plan on making it output a playable format for the PC98, since there's no VGM players for it yet....)

**Comment by DeltaRazero** [comment]
I could provide Rerrah with code for loading .OPM and .TFI. from an unfinished library I made.

I also wouldn't mind to (eventually) write or help Rerrah write a module to PMD or FMP performance file compiler.

**Comment by Pigu-A** [comment]
For number 4 you can just use up/down key to increase/decrease by one. It's a standard UI slider feature.

**Comment by rerrahkr** [comment]
In latest version ([v0.1.3](https://github.com/rerrahkr/BambooTracker/releases/tag/v0.1.3)), these issues were fixed. 
I will work on other requests in future.
