### ISSUE TITLE
Messed-up order list display

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#201]
1) Start playing a module
2) Snap the order list along with the other stuff to the top, making the pattern editor effectively fullscreen
3) Wait for an order transition to happen
4) De-minimise the order list

Might be more fallout from the repaint change, due to it being died to screen updates to the order list components?

https://cdn.discordapp.com/attachments/519164281518948372/694883533348405288/SimpleScreenRecorder-2020-04-01_14.17.34.webm

**Comment by rerrahkr** [comment]
Thanks for your report, I fixed it to redraw all area of the order list at 02e131840a0bf4e8ef44c9898bf3f01cf1663bf3.
