### ISSUE TITLE
BambooTracker closes upon opening a file

### ISSUE THREAD

**Issue by Drillimation** [rerrahkr/BambooTracker#202]
When opening a file through File > Open, the program closes immediately after opening the file. Also, I'm having trouble importing WAV files into the ADPCM channel. What WAV files are supported for conversion?

**Comment by freq-mod** [comment]
>When opening a file through File > Open, the program closes immediately after opening the file.

Unable to replicate with the newest dev build (0.4.0.25). Does this bug occur with any module on your side, or just a specific one?

 >What WAV files are supported for conversion?

Mono 16-bit PCM @ 16000 Hz max.

**Comment by rerrahkr** [comment]
Sorry for the late reply. Does it crash when you open any files?

**Comment by rerrahkr** [comment]
I close it as it's been left without a detailed status.
