### ISSUE TITLE
[suggestion] Instrument load interface suggestions

### ISSUE THREAD

**Issue by Mikejmoffitt** [rerrahkr/BambooTracker#206]
There are two OPNA patch interface improvements I would like to suggest.

1) *Option to replace instrument when loading*

At times, I may have composed a melody, and would like to try listening to it with a selection of different pre-existing patches. Rather than editing the pattern data to reassign instruments (because it may span across multiple patterns) it would be very convenient to load an OPNA patch in the same instrument slot. Right now, I can only do this if I leave a gap in the instrument list intentionally.

2) *Ability to preview OPNA patches while selecting files*

When loading a patch from a directory, I have to rely on a descriptive title (e.g. "DX7 BASS 01") to suppose what the patch will sound like. It would be convenient to "preview" patches before I've committed to loading them as an instrument. Being able to "keyjazz" while selecting, or even just play a basic tone on file select, would reduce the overhead of selecting a patch.

**Comment by rerrahkr** [comment]
Sorry for the late reply. Thanks for your requests.

> 1. Option to replace instrument when loading

I think that replacing an existing instrument when importing an instrument should be avoided as it is difficult to manage the instrument properties. Instead, it may be possible to swap 2 instruments in the instrument list.

> 2. Ability to preview OPNA patches while selecting files

I've thought about it before, but have passed on implementing it because it would be costly to load all the instruments in the patch for keyjazz. I will actually test it out.

**Comment by rerrahkr** [comment]
I added sound preview in bank import at b1caf4e6313563132296220c7110ec998cc5e18b.

**Comment by rerrahkr** [comment]
It is enable to swap instruments at a22c8228ad65b52c6f9aea3d9ecdf0d5305b0425, so you can change instruments without editing patterns to swap between the current instrument and the new instrument imported from the bank.

**Comment by freq-mod** [comment]
Sorry for maybe stupid question, but I can't see any option to swap instruments anywhere - bank import dialog, instrument list options, pattern right-click options, etc..

**Comment by rerrahkr** [comment]
Swapping instruments by dragging one instrument and drop it on another instrument. It's like 0CC-FT.

![swap](https://user-images.githubusercontent.com/26477882/81175254-2f761180-8fde-11ea-9ab6-2e730f5facf3.gif)
