### ISSUE TITLE
Drag-and-dropping file that is not module corrupts the pattern editor

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#207]
1. From a file explorer, drag and drop any type of file that's not a .btm module (.btb bank for example) onto BambooTracker executable
2. Unsurprisingly, error will pop-up
3. After pressing OK, pattern editor will be stretched in size, cursor will be misalligned and ADPCM channels will become impossible to edit.

**Comment by freq-mod** [comment]
Now I also realized, when BT is already running you can drag and drop .btb bank on the window to import it, so there is more to this bug.

**Comment by rerrahkr** [comment]
Thanks for your report. I've tried to reproduce it, but couldn't. I will try it on a different computer than the development environment.

It is expected behavior that BT allow to load only a module on launch. An instrument or a bank cannot be read unless BT is running.

**Comment by freq-mod** [comment]
>I've tried to reproduce it, but couldn't.

That's weird. I made a recording that showcases that problem: https://streamable.com/bowyot

**Comment by freq-mod** [comment]
I also found out that if BT is running in non fullscreen window, bug won't occur. Application window must be maximized for that behaviour. 
Maybe it's screen resolution related and that could be the reason you couldn't have replicated that bug on your side?

**Comment by rerrahkr** [comment]
I can replicate that bug by maximizing the main window. It seems something wrong in first drawing of the pattern editor, maybe a size of painting area.

**Comment by rerrahkr** [comment]
I fixed resolution mismatching between painting area and internal canvas at 6f9c6b275b8e1f8b55ae95567505dc4fde184935. Is it solved this issue?

**Comment by freq-mod** [comment]
It did, thank you!
