### ISSUE TITLE
Corrupted module (speed changes mid-song)

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#208]
I don't know what has happened to it -  [eirin.zip](https://github.com/rerrahkr/BambooTracker/files/4535993/eirin.zip)

On the order list, jump to pattern 04 or later and play the song. Speed will change to just 4.00 BPM and there is no way to change it back to nominal 75 BPM, without restarting the tracker.

**Comment by rerrahkr** [comment]
Thanks for your report. 
At ffc4b89fb94c6b7c38284f28a28d2ee0af0da12e, I fixed speed/tempo states retrieving on starting playback that solved this issue.

**Comment by freq-mod** [comment]
Thanks for the fix!
