### ISSUE TITLE
[macOS] Instrument name editing leaves lingering textboxes

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#210]
![image](https://user-images.githubusercontent.com/23431373/80800735-80cf6c80-8baa-11ea-9522-0858d1c1962b.png)

Since v0.4.0, editing instrument names on macOS (native binary and Wine) appears to be able to leave the textboxes lingering indefinitely.
> 4.0 win version (via Wine) and 4.1 mac
> it doesn't go back afaik after I edit the name
>  oh pressing enter works if I press it right after I edit the name
>  uh if I press it after pressing the edit name button and if I haven't clicked elsewhere on the ui

I'm unable to provide more details about this bug as I'm just passing along the report, sorry.

**Comment by rerrahkr** [comment]
Thanks for your report.
I've already noticed it, and from several tests on Windows I found it was probably Qt issue.
Items in the instrument list use QListWigetItem and the event is set to end the rename when the item loses focus. This issue does not occur in Qt 5.10.1, which is currently used in appveyor, but it does in Qt 5.14.1.

**Comment by rerrahkr** [comment]
I fixed it at def7b45fffa8bd65cdad1f16dbb11ae7d4483df7 and works well on Windows with Qt 5.14.2.
