### ISSUE TITLE
Cannot open ADPCM .BTI after reopening tracker

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#211]
[adpcm bug.zip](https://github.com/rerrahkr/BambooTracker/files/4564822/adpcm.bug.zip) - two files from my ADPCM bank, being saved to .bti files are corrupted and can't be loaded with error:
`Failed to load instrument`
`_Map_base::at`

**Comment by rerrahkr** [comment]
Thanks for your report. It was failed to load ADPCM sample after adding drumkit functions, I fixed at e44746759b74a3629f2ccc6900740a2c986c5800.

**Comment by freq-mod** [comment]
thanks for the fix!
