### ISSUE TITLE
Sample drawing error message

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#213]
![adpcm draw bug](https://user-images.githubusercontent.com/32672779/81826300-ee2eb600-9537-11ea-8993-067799347cdd.JPG)

I saw this message when I was editing the sample, I think when accidentally moved my cursor out of the sample view window.

**Comment by freq-mod** [comment]
Also, when cleared sample: 
`vector::M_range_check:__n (which is 2) >= this ->size() 9which is 2)`

**Comment by rerrahkr** [comment]
Thanks for your reports.
I fixed the first bug at 5f19fd35eb511733be551f9f082436b1fee0c4b6, but I couldn't replicate the second one. Could you tell me more details?

**Comment by freq-mod** [comment]
> but I couldn't replicate the second one.

It seems to be linked with first one, I suppose. 
1. Import a .wav sample
2. Click on a .wav sample to edit it, after you move out of bounds and get an error message, clear sample

**Comment by freq-mod** [comment]
Anyway, 5f19fd3 fixed both problems, thanks!
