### ISSUE TITLE
Sample editor grid view is glitched when zoomed in

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#214]
It's very minor and cosmetic problem, but anyways:
1. Load sample
2. Zoom in
3. Click on the grid wiev button
4. Scroll the waveform wiev to the right, grid will start to disappear at some point
![adpcm](https://user-images.githubusercontent.com/32672779/82070782-86ae6d00-96d5-11ea-8039-f105d3e5051a.JPG)

**Comment by rerrahkr** [comment]
Thanks for your report. I fixed this in b056139b52b498bdcf2000550d56ee9ed451a1cb.

**Comment by freq-mod** [comment]
Thanks for the fix!
