### ISSUE TITLE
v0.4.2 release has incorrect qt_en.qm translation

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#215]
Reoccurrence of #196. Looks like v0.4.1 was affected as well, without anybody noticing.

![grafik](https://user-images.githubusercontent.com/23431373/82097710-bbd1b400-9703-11ea-9149-ae82e90a0a21.png)
![grafik](https://user-images.githubusercontent.com/23431373/82097752-cdb35700-9703-11ea-80a2-aa59a63682a9.png)

**Comment by rerrahkr** [comment]
Thanks for your report.
I find qt_en.qm and qt_de.qm are the same in winXP, but it also happens in macOS?
I checked BambooTracker-v0.4.2-macOS.zip but I couldn't find those translation files.

Sorry for the delay in deploy check on macOS. I don't have mac environment and I need to go out, so it will take a while longer.

**Comment by OPNA2608** [comment]
It doesn't appear in Travis' macOS build afaik, the screenshot shows the Windows build running via Wine (on a MacBook where the macOS build sadly isn't performant enough). Apologies for not clarifying that.

> Sorry for the delay in deploy check on macOS. I don't have mac environment and I need to go out, so it will take a while longer.

If my word is enough for you, I asked someone to test the macOS builds (both the releases & AppVeyor versions) the other day and they said they ran as well as before. (Though still with problems as mentioned above, hence they prefer the Windows build + Wine)

**Comment by rerrahkr** [comment]
I replaced qt_en.qm in BambooTracker-v0.4.2-winXP.zip with that in BambooTracker-v0.4.2.zip, Does it work well? or BambooTracker-v0.4.2.zip is also needed to change the translation file?

> If my word is enough for you, I asked someone to test the macOS builds (both the releases & AppVeyor versions) the other day and they said they ran as well as before. (Though still with problems as mentioned above, hence they prefer the Windows build + Wine)

Thanks for testing. I will check macOS problem as well.

**Comment by OPNA2608** [comment]
Seems to work well, thanks.
