### ISSUE TITLE
Reversed volume entry when starting program with "Reverse FM volume order" unchecked

### ISSUE THREAD

**Issue by nyanpasu64** [rerrahkr/BambooTracker#220]
- Uncheck the setting "Reverse FM volume order".
- Restart the program.
- Type into the volume column.

If you type 00, 7F appears instead.

BambooTracker 0.4.2 on Windows 10 x64.

**Comment by OPNA2608** [comment]
FWIW, I can replicate this with v0.4.2 on Linux… if I *check* the setting & restart instead. Unchecking & restarting works as expected.

**Comment by rerrahkr** [comment]
Thanks for reports. Internal variable for FM volume reverse had not initialized, I fixed it at 43eb4c09ee8ad7d9b969fd253cc28d5eb4729506.

**Comment by nyanpasu64** [comment]
Seems fixed! Thanks!
