### ISSUE TITLE
Visual glitching when resizing window

### ISSUE THREAD

**Issue by nyanpasu64** [rerrahkr/BambooTracker#225]
After commit 8b8b294435b031436c00c25aa2b34652ac28e13f ("Set Qt::WA_OpaquePaintEvent flag in order list and pattern editor"), resizing the BambooTracker window on Linux (KDE Plasma with compositing both on and off) causes the image to glitch out.

Sometimes the image is missing and black. Other times it renders the window's previous appearance (entire window, not just the pattern/order editor) but with the wrong width, causing a diagonal skew.

Video at https://youtu.be/T8SNMjT3o7I.

Maybe the issue is related to your reentrant repaint guard (repaintable_):

https://github.com/rerrahkr/BambooTracker/blob/8b8b294435b031436c00c25aa2b34652ac28e13f/BambooTracker/gui/order_list_editor/order_list_panel.cpp#L251

Or it might be unrelated.

**Comment by rerrahkr** [comment]
Thanks for your report.
I find that this glitch is happened without repaint guard. When I test, the order list may black out on resizing. However, I am not instructing such processing during the paint event.
I'm not sure, but as far as I've tested, Qt::WA_OpaquePaintEvent doesn't seem to keep previous drawing well on resizing. It seems to be better to revert to the painting method before 8b8b294.

**Comment by rerrahkr** [comment]
I fixed at 6c608840d7773922ab92781798d612090163db3a.
