### ISSUE TITLE
Instant Crash when Ordering the Instruments by Drag n drop. (with Duplication of Names Bug)

### ISSUE THREAD

**Issue by YuzuMSX** [rerrahkr/BambooTracker#228]
Hello. 

I have upgraded to the lastest version and the DEV version but i found a couple issues.
That happends. It crashes when Ordering Instruments via Drag n Drop to the different instruments.

and there's no Crash Log for some reason

https://i.imgur.com/4LkBkpX.gifv

also i have a BTM module for testing
[MM7-Wily3.zip](https://github.com/rerrahkr/BambooTracker/files/4842834/MM7-Wily3.zip)

**Comment by rerrahkr** [comment]
Thanks for your report, I confirm the instrument name error and crash. I will take a closer look at the cause.

**Comment by rerrahkr** [comment]
It was because I confused the Instrument ID with the row number in the instrument list.
I fixed it at dd1ec1a27bff228a94a3ba567c9931c952ccec8e.
