### ISSUE TITLE
Bug Cxx Command / Instant Freezes on VGM, S98, WAV Export

### ISSUE THREAD

**Issue by YuzuMSX** [rerrahkr/BambooTracker#229]
Another issue.

I try to add the Cxx command to the current Order before exporting to File (Not the last order)
I put C00 on the First Order list.
![image](https://user-images.githubusercontent.com/32228782/85956246-513ea580-b94a-11ea-88cc-5bef02240903.png)

Then I export a VGM. It frozes the Program.

I have uploaded the BTM file before export to VGM File
[bug_cxx_vgmexport.zip](https://github.com/rerrahkr/BambooTracker/files/4842868/bug_cxx_vgmexport.zip)

**Comment by rerrahkr** [comment]
Thanks for your report.
This bug was happened when the tracker cannot reach the last order by pattern effects in the previous order. I fixed it at 8065562e412d38f72868ea46d0ac495c6a0b4fd5.
