### ISSUE TITLE
SSG looping same pattern when exporting WAV or VGM

### ISSUE THREAD

**Issue by pedipanol** [rerrahkr/BambooTracker#23]
SSG 2 and 3 apparently end up looping the current pattern on editor when exporting to VGM and WAV
Not sure if this happens in all modules but it doesn't seem like there's anything I've done that caused it.

The track is supposed to sound like this (recorded through an external program)
https://dl.dropbox.com/s/qquzuh0ur9khfke/bamboo%20tracker%20recording.mp3
But when exporting to wave while the first pattern is selected, the WAV/VGM output sounds like this
https://dl.dropbox.com/s/zqao8zp1eatozrh/bamboo%20tracker%20wav%20export%201.mp3
When the second pattern is selected, it sounds like this
https://dl.dropbox.com/s/nx6jyoy7rivplw9/bamboo%20tracker%20wav%20export%202.mp3

Here's the module file
[begin bossa.zip](https://github.com/rerrahkr/BambooTracker/files/2636258/begin.bossa.zip)

**Comment by rerrahkr** [comment]
I fixed the bug in [161b24b](https://github.com/rerrahkr/BambooTracker/commit/161b24b3832f708328fbd65507069f622b536fb5).
I will publish the binary in the next release.
