### ISSUE TITLE
SIGSEGV on RtApiCore::getDeviceInfo [macOS]

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#231]
Letting you know that ~~a Catalina user~~ (see follow-up comment) is unable to launch any of the CI-built binaries due to an immediate SIGSEGV. I've attached some crash log he was able to generate. v0.4.2 works for them, v0.4.3 doesn't. SIGSEGV occurs in RtAudio.cpp, in the CoreAudio section, somewhere in `getDeviceInfo`.

[message.txt](https://github.com/rerrahkr/BambooTracker/files/4845982/message.txt)

An excerpt:
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000052000000e9
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb 
Terminating Process:   exc handler [2057]

VM Regions Near 0x52000000e9:
    VM_ALLOCATE            000000012dff2000-000000012dff6000 [   16K] rw-/rwx SM=PRV  
--> 
    MALLOC_NANO            0000600000000000-0000600008000000 [128.0M] rw-/rwx SM=PRV  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.yourcompany.BambooTracker   0x00000001008152db RtApiCore::getDeviceInfo(unsigned int) + 363 
1   com.yourcompany.BambooTracker   0x00000001007171e0 AudioStreamRtAudio::initialize(unsigned int, unsigned int, unsigned int, QString const&, QString const&) + 192 
2   com.yourcompany.BambooTracker   0x000000010065d9b5 MainWindow::MainWindow(std::__1::weak_ptr<Configuration>, QString, QWidget*) + 24037
3   com.yourcompany.BambooTracker   0x0000000100656eda main + 1834
4   libdyld.dylib                   0x00007fff6a7a6cc9 start + 1 
```

 I'll try to debug this with them, just wanted to let you know about it. Maybe you have an idea what could be causing the problem, I sure don't. I guess it might be a problem with our VLA workaround? We'll see when I get down to bisect it with them.

**Comment by OPNA2608** [comment]
Apparently, macOS in general is affected. This is not specific to Catalina, the release builds crash on any supported macOS version from what I was told. Culprit is the VLA fix https://github.com/rerrahkr/BambooTracker/commit/149523abb87973602452e83860d78aba90903d54. I'll open a PR to revert that commit & add back the VLA workaround switch, unless you have an idea for a better fix for those VLAs.

**Comment by rerrahkr** [comment]
Thanks for your report and contribution. I checked PR build is worked on macOS and merged it.
Added information about dev-build to README, so is it better to remove macOS builds from v0.4.3 release page?

**Comment by OPNA2608** [comment]
I think so, yeah.

**Comment by OPNA2608** [comment]
Fixed with https://github.com/rerrahkr/BambooTracker/commit/45346ed99559d44c2e32a5c6138a0835b212e875, hopefully we can find a more sound fix for the VLA warnings in the future with regards to #218.
