### ISSUE TITLE
"Play Pattern" doesn't loop pattern with 0D command

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#232]
When pressing F6 (Play Pattern) on a pattern that ends prematurely with the `0D00` command, playback will continue to the next pattern in the order. This continues until it hits a pattern that doesn't use `0D00`, which will then continue being looped properly.

Tested on NixOS 19.09, BT v0.4.3.

**Comment by rerrahkr** [comment]
Thanks for your report. I find this is also happened with 0B and 0C effect commands. I'll check its playback control.

**Comment by rerrahkr** [comment]
I fixed it at b921a8f5d06a468ca8b209bd7851df33ea39c1e3.
