### ISSUE TITLE
Maximum possible ADPCM sample import rate should be 55.5 kHz instead of 16 kHz

### ISSUE THREAD

**Issue by superctr** [rerrahkr/BambooTracker#234]
It seems like there's been a misunderstanding when reading the YM2608 manual. The 16 kHz limitation refers to encoding/decoding to memory ("analyzing") using the built in A/D converter. This is not done here, instead pre-encoded sample data is uploaded to memory before playback.

When playing back ("synthesizing") ADPCM samples, the maximum frequency is 55.5 kHz. Since we do not emulate encoding using the ADC, the maximum sample frequency [here](https://github.com/rerrahkr/BambooTracker/blob/add4955795a66ee0e5781171e4474397dbe30cfc/BambooTracker/gui/instrument_editor/adpcm_sample_editor.cpp#L313) should be 55467, not 16000.

![2020-07-03_16-53-01](https://user-images.githubusercontent.com/1159409/86481051-85053b00-bd4f-11ea-8746-02c290e23fa3.png)
![2020-07-03_17-10-09](https://user-images.githubusercontent.com/1159409/86481290-052ba080-bd50-11ea-8de2-118fb76a2f09.png)

**Comment by rerrahkr** [comment]
Yes, as you and your manual, the maximum synthetic frequency is 55.5kHz. It works even with a real chip. I don't know why I made a mistake, but I'll fix it.
And one question, why does it set 55467Hz, not 55500Hz as the manual says?

**Comment by superctr** [comment]
It's because ADPCM and FM should use the same clock divider, which is 55467. I don't think the extra 467 Hz matter but @OPNA2608 insisted on it :P

**Comment by OPNA2608** [comment]
Either 466 or 467, didn't remember the exact number.

**Comment by superctr** [comment]
7989200/144 = 55466,66...

So it could be rounded up to 55467, but if the existing code is using 55466, then that would probably be best and most consistent.

**Comment by rerrahkr** [comment]
I see. I fixed it at 2f315a51874e720b0b6a324226942bcf16b7bc65. Thanks for your report and help!
