### ISSUE TITLE
Warnings produced after after updating llvm, clang, compiler-rt, libc++, libunwind, lld, lldb and openmp to 10.0.1 rc1 f79cd71e145

### ISSUE THREAD

**Issue by ehaupt** [rerrahkr/BambooTracker#235]
FreeBSD recently updated llvm, clang, compiler-rt, libc++, libunwind, lld, lldb and openmp to 10.0.1 rc1 f79cd71e145 (see OSREVISION [1300096](https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/versions.html)) on FreeBSD 13.0-CURRENT.

Since BambooTracker uses `-pedantic` compiler flags, some new warnings cause the compiler to fail. When removing the pedantic compiler flags the tracker compiles just fine but I thought I'd share the build log as you might be interested in fixing warnings at some point:

[typescript-bambootracker-llvmorg-10.0.1-rc2-0-g77d76b71d7d.txt](https://github.com/rerrahkr/BambooTracker/files/4870830/typescript-bambootracker-llvmorg-10.0.1-rc2-0-g77d76b71d7d.txt)

This has definitely no priority.

**Comment by OPNA2608** [comment]
> Project MESSAGE: Qt configured with Clang
> Project MESSAGE: Compiler is version 10.0.1

What Qt5 version is this with? The macOS Catalina CI is supposedly on Clang version 11.0.0 and Qt5.15.0 without any such warnings.

**Comment by ehaupt** [comment]
The follwing QT versions are present:

```
$ pkg info | grep -i qt
py37-sphinxcontrib-qthelp-1.0.3 Sphinx extension which outputs QtHelp document
qt5-buildtools-5.14.2          Qt build tools
qt5-core-5.14.2_3              Qt core non-graphical module
qt5-dbus-5.14.2                Qt D-Bus inter-process communication module
qt5-declarative-5.14.2         Qt declarative framework for dynamic user interfaces
qt5-gui-5.14.2                 Qt graphical user interface module
qt5-linguisttools-5.14.2       Qt localization tools
qt5-multimedia-5.14.2          Qt audio, video, radio and camera support module
qt5-network-5.14.2             Qt network module
qt5-opengl-5.14.2              Qt 5-compatible OpenGL support module
qt5-qmake-5.14.2               Qt Makefile generator
qt5-sql-5.14.2                 Qt SQL database integration module
qt5-testlib-5.14.2             Qt unit testing module
qt5-widgets-5.14.2             Qt C++ widgets module
qt5-xml-5.14.2                 Qt SAX and DOM implementations
qt5-xmlpatterns-5.14.2         Qt support for XPath, XQuery, XSLT and XML Schema
qtchooser-66_2                 Qt tool wrapper
```
