### ISSUE TITLE
Some Crash

### ISSUE THREAD

**Issue by JonKaruzu** [rerrahkr/BambooTracker#24]
Hey. Thanks for trying out. So first to all I found the issue
1. Open Bamboo, go instruments, right click to add or loading 2 instruments,  Right click at the first instrument, edit name, when renaming instrument, go to cursor instrument 2, right click on the instrument 2, Select any options and it crash. :(

2. Click ... Or module properties, at the insert song on title write something, and press enter. And it terminated with error code.

English broken. Sorry

**Comment by rerrahkr** [comment]
Thank you for your report.
I will check it on my winXP.

**Comment by rerrahkr** [comment]
I fixed these bugs [v0.1.3](https://github.com/rerrahkr/BambooTracker/releases/tag/v0.1.3) (e025e0f4211ca8768259dd6eb6cc09ea6d58efb3 and d89ae5b4e66f45dd080344390b012feede071bf4).
