### ISSUE TITLE
Feature Request - Estimate Song Length

### ISSUE THREAD

**Issue by Drillimation** [rerrahkr/BambooTracker#242]
Greetings from the developer of _Chuhou Joutai_. I am requesting a feature in BambooTracker to estimate the length of a song like in OpenMPT. As an indie developer who also composes, I want to try and make my songs as long as possible. Also, can you include a note input function based on the one from OpenMPT?

**Comment by rerrahkr** [comment]
Thanks for your requests. I'll work on song length estimation.
Could you tell me more about a note input function? I could not find it in OpenMPT as I've rarely used.

**Comment by Drillimation** [comment]
This is how it works. The row starting from the "Q" key is the first octave and goes to the "]" key (C-4 to B-4), the second row starting from the "A" key is the second octave and goes to the "\" key (C-5 to B-5), and the last row starting from the "Z" key and goes to the "/" key (C-6 to A-6).

To get a better understanding of it, OpenMPT, go to Setup, the Keyboard tab, and choose Pattern Editor - Note Column to understand how it works.

**Comment by YoshiLightStar** [comment]
OpenMPT has custom note input options that's one of the defaults choices (of many to chose from or you can make your own) but making that the default of BambooTracker might not be a good idea so perhaps more keys can be added to the setup in the config screen so people can set it up to their preferences

**Comment by rerrahkr** [comment]
I added song estimation feature at 150825d3e7a8b866053e8ef99d6560d339eb3e62.

About key input, you can change note input by selecting custom in Configuration -> keys -> Note entry layout. I'll skip adding +2 octave notes now because of a key input issue.
