### ISSUE TITLE
AppVeyor CI Windows devbuilds fail

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#244]
`Uploading artifacts...`
`Maximum allowed artifact storage size of 50000 Mb will be exceeded.`

While artifacts are being successfully built, artifacts can't be created due to storage issue (?)

**Comment by OPNA2608** [comment]
AppVeyor has an anti-abuse system involving an artefact upload limit. While artefacts expire and get deleted on their own after 6 months, there doesn't seem to be a way of deleting unneeded artefacts ourselves that i could find while looking through the AppVeyor project settings.

The standard "solution" seems to involve opening a new ticket with AppVeyor Support mentioning the error and build, followed by a bump in the storage size limit. See https://help.appveyor.com/discussions/problems/25101-maximum-allowed-artifact-storage-size-of-50000-mb-will-be-exceeded

I pushed my fork to be on par with current master if you need a new development build in the meantime: https://ci.appveyor.com/project/OPNA2608/bambootracker

**Comment by rerrahkr** [comment]
Sorry for the late report. I've already sent the message to Appveyor in https://github.com/appveyor/ci/issues/3493.

**Comment by rerrahkr** [comment]
The artifact storage size is spread. I rebuilt the latest commit and it was success to create artifacts.

**Comment by freq-mod** [comment]
Thanks a lot!
