### ISSUE TITLE
Incorrect sample rate issue

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#25]
Let's compare for example hi-hat instrument from EVE: burst error. In Hoot player it sound like this:
https://instaud.io/2ZYr
Yet in Bamboo Tracler, the same instrument sounds completely different:
https://instaud.io/2ZYs 

What is the reason of this difference? There are several percussive instrument that sound slightly off, at least compared to Hoot.

Instrument in question:  [Closed Hi-hat.zip](https://github.com/rerrahkr/BambooTracker/files/2637104/Closed.Hi-hat.zip)

**Comment by papiezak** [comment]
I did that. I don't hear any improvement.
OPN Bank Editor usees Neko Project 2 Kai fmgen core, and hihat instrument in question sounds like one in Hoot... is MAME emulation wrong?

**Comment by pedipanol** [comment]
Ah, i meant changing on the code, the sampling rate setting on Bamboo Tracker only seems to change the output rate, not the rate that the instrument is synthesized. If you set Hoot to use MAME it sounds fine as long as the hoot.ini sample rate setting is at 55466.

It really is a sample rate problem, here's how the VGM output sounds on 44100hz "chip rate" on foo_vgm
https://dl.dropbox.com/s/ljzaqy5153drkar/vgm44100.mp3
And here's how it sounds with on 55466hz
https://dl.dropbox.com/s/vzrvo8b5axbvjtc/vgm55466.mp3

**Comment by papiezak** [comment]
Ah, that makes more sense! Let me check that...

**Comment by papiezak** [comment]
ec550a2 fixed it. Thanks @pedipanol and @rerrahkr !
