### ISSUE TITLE
[Windows|macOS] - ***deployqt options in deployment from CI

### ISSUE THREAD

**Issue by rerrahkr** [rerrahkr/BambooTracker#251]
## Requested Feature

https://github.com/rerrahkr/BambooTracker/blob/a83795f12a66a540c7d1a84108f4a25a4d4aa6a9/ci/package_windows.sh#L6

https://github.com/rerrahkr/BambooTracker/blob/a83795f12a66a540c7d1a84108f4a25a4d4aa6a9/ci/package_osx.sh#L6

Currently we set only `-verbose=2` option to **deployqt, but there are some options which seem to help the size of build package smaller.

https://doc.qt.io/qt-5/windows-deployment.html#the-windows-deployment-tool
https://doc.qt.io/qt-5/macos-deployment.html#the-mac-deployment-tool

I tested these options on Windows 10 with Qt 5.15.0, and it seems to work well:

```bash
windeployqt.exe BambooTracker.exe -verbose=2 --no-quick-import \
		--no-system-d3d-compiler --no-virtualkeyboard \
		--no-compiler-runtime --no-webkit2 --no-angle --no-opengl-sw \
		--no-svg
rm -rf imageformats
```

After executing `windeployqt.exe`, the directory `imageformats` is generated which contains some image I/O plugins, but we don't read and write an external image file so they are useless.

I'll search about `macdeployqt`.

**Comment by rerrahkr** [comment]
#238 remove Qt multimedia, that it helps windeployqt to skip  collecting libraries related to network and multimedia.

**Comment by rerrahkr** [comment]
`--no-opengl-sw` option is enabled from Qt 5.6 and `--no-virtualkeyboard` is from Qt 5.15, so we need to switch options by Qt version in ci/package_windows.sh.

It is the one way to get Qt version as the argument of script and test it, but I'll plan to do `windeployqt -h` and test whether the help description contains the option.

**Comment by rerrahkr** [comment]
`macdeployqt` seems to have no option to remove frameworks and plugins, so it is necessary to remove these maually:

#### Frameworks
- QtPdf.framework
- QtQuick.framework
- QtVirtualKeyboard.framework
- QtQmlModels.framework
- QtSvg.framework
- QtQml.framework
- QtOpenGL.framework
- QtMultimediaWidgets.framework

After merged #238, QtOpenGL.framework and QtMultimediaWidgets.framework are not collected by `macdeployqt`, and QtNetwork.framework is removable.

#### Plugins

- platforminputcontexts
- virtualkeyboard
- iconengines
- imageformats
- audio
- bearer
- mediaservice

audio, bearer and mediaservice are not collected by #238 too.

**Comment by OPNA2608** [comment]
I have a [WIP branch](https://github.com/OPNA2608/BambooTracker/tree/linux-appimage) that'd add release packaging as an AppImage on Linux via [linuxdeployqt](https://github.com/probonopd/linuxdeployqt). I'll look if there's any options similar to that, but I don't use AppImages myself.

(I get a confusing build failure about the XP build's MinGW download timing out that's kept me from opening a PR and I don't really know what to do about it)

**Comment by rerrahkr** [comment]
I'll remove libraries of Qt multimedia leaved in #253 after merging #238.

**Comment by rerrahkr** [comment]
#238 is merged which removed Qt multimedia, close.
