### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Newer FF files containing SSG-EG inst. are loaded incorrectly

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#252]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

## Bug Description
[On KAJA's website](https://sites.google.com/site/kajapon/pmd), you can download package with source code, docs, binary files and demo examples. PMD 4.8s, most recent version, contains demo of newly introduced SSG-EG feature, complete with .FF bank containing a couple of such instruments. However they don't seem to be read correctly by BambooTracker.
This .zip file contains .FF file, .MML sequence and .BTI of what first two instruments should be. -  [FF48S.zip](https://github.com/rerrahkr/BambooTracker/files/5046893/FF48S.zip)

**Comment by rerrahkr** [comment]
Thanks for your report. It seems that SSG-EG is represent as MSB of DT/ML byte, MSB of TL byte and 6th and 7th bits of DR byte. I'll fix it.

I also checked that VEDSE, the new tone editor of PMD supporting SSG-EG, exports a tone to MML with comments about SSG-EG value. At the moment there are few PMD tones using SSG-EG, however, it will be necessary to add the new text import format from PMD MML.

**Comment by freq-mod** [comment]
About text import from PMD, this version also can be supported:

; nm alg fbl
`@001` 002 007				=	name
; ar  dr  sr  rr  sl  tl  ks  ml  dt ams   
 031 028 010 015 004 020 000 000 000 000 
 031 029 000 015 015 030 000 010 000 000
 024 018 016 015 002 020 000 000 000 000 
 028 018 013 015 002 000 000 001 000 000

**Comment by rerrahkr** [comment]
I fixed it at 22fb4971f85199eaaa4365dc1088f5c03fd8a5a1.

**Comment by freq-mod** [comment]
That is fixed, thanks. Yet there is one small problem. In that .FF file, second instrument behaves weirdly - between key ons and even during playback, SSG-EG flag on OP2 seems to be ignored - instrument sounds like it doesn't have SSG-EG parameter defined
[bugssgeg.zip](https://github.com/rerrahkr/BambooTracker/files/5058310/bugssgeg.zip) - module that demonstates problem

**Comment by rerrahkr** [comment]
> [bugssgeg.zip](https://github.com/rerrahkr/BambooTracker/files/5058310/bugssgeg.zip) - module that demonstates problem

[ssgeg.zip](https://github.com/rerrahkr/BambooTracker/files/5061334/ssgeg.zip) - Playing .s98 exported from the module on the real hardware (G.I.M.I.C), triggers on the SSG-EG are inaccurate, that it indicates Nuked-OPN Mod closes to the hardware behavior.

**Comment by freq-mod** [comment]
So Nuked-OPN is actually correct if I understood correctly? Very weird...

**Comment by rerrahkr** [comment]
I think that MAME emulation may be too close to YM2608 specifications, not the real behaviors.
Since there seems to be several errors on the real chip like #187, I think such a bug is the "correct" behavior.

**Comment by freq-mod** [comment]
Oh, I see. Thanks for claryfying
