### ISSUE TITLE
[Nuked OPN-Mod] - distortion noise on FM tones with long release rates

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#255]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

## Bug Description
When FM sound decays, some faint noise can be heard (under certain conditions, it can be very prominent) It is likely a leftover from Nuked-OPN2 - apparently a small distortion caused by the 9-bit PCM output that was post-converted into 16-bits.
How does it relate to real YM2608, I don't know, would it be possible to check whether such noise occurs on real chip as well?
It might be similiar case to #187.

## How to reproduce
_duh_
1. Create an FM instrument. Preferably, ALG=7, TL=0 for all operators and RR=1/2/3
2. Play a note

**Comment by rerrahkr** [comment]
Thanks for your report, 

[gimic.zip](https://github.com/rerrahkr/BambooTracker/files/5063826/gimic.zip)
zip contains btm, s98 and wav recording GIMIC output. The real chip also be noisy in key-attack: this noise distortion caused by phase resetting is a hardware-derived phenomenon, so the emulation seems to be fine.

**Comment by freq-mod** [comment]
Key-attack click is fine, but decay/release noise distortion is what made me curious - 
[distortion.zip](https://github.com/rerrahkr/BambooTracker/files/5064277/distortion.zip) - contains .btm, s98 and wav of Nuked output, noise can be heard after key-off (0:04 mark of wav)

**Comment by rerrahkr** [comment]
It seems that such a small noise does not occur in gimic. At the moment I don't know if it's because of bit conversion or the phase interference.

**Comment by freq-mod** [comment]
@nukeykt in context of this modified Nuked emulator, what can produce this quantization noise?

**Comment by nukeykt** [comment]
How much operator output bits do you drop? Ym3438 drops 5 bits and 2608 should drop only one IIRC

**Comment by freq-mod** [comment]
It's probable this wasn't changed when making Nuked-OPN...
