### ISSUE TITLE
[Windows] - MSVC builds crash on launch if quit when maximized

### ISSUE THREAD

**Issue by nyanpasu64** [rerrahkr/BambooTracker#256]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

When I build master on Windows 64 MSVC, if BambooTracker was shutdown when maximized, I get a crash when the app starts, at line:

https://github.com/rerrahkr/BambooTracker/blob/master/BambooTracker/gui/order_list_editor/order_list_panel.cpp#L610

songStyle_.trackAttribs has 16 items on MinGW, but 0 items on MSVC. (BambooTracker won't build on Windows clang/clang++, I didn't try clang-cl.)

The problem is that on MSVC, with a maximized BambooTracker window, `OrderListPanel::paintEvent()` is called without `OrderListPanel::onSongLoaded()` being called first.

## How to reproduce

1. On 0.4.3 or 0.4.4, maximize BambooTracker and close the window.
1. Build master or 0.4.4 on MSVC, then start it.

## System Information

- **Operating System**: Windows 10 x64
- **BambooTracker Version**: 26a8fdd24083081c39a1d700646f7d5d31bc6a81 master
- **Build Type**: MSVC, both Debug and Profile

**Comment by rerrahkr** [comment]
Sorry for the late reply and thank you for your report. I haven't checked the initialization order in detail yet, but I'd like to deal with it by putting dummy data in songStyle_.

**Comment by rerrahkr** [comment]
I fixed it at 8a242edab829706b8b853ea443312f05c714eac4.
