### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Exporting to WAV/VGM/S98 no longer works reliably.

### ISSUE THREAD

**Issue by Zexxerd** [rerrahkr/BambooTracker#258]
> #### Checklist
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [?] This bug hasn't already been fixed in the latest development build.

---

## Bug Description
(Tested on Mac)
In v0.4.4, after confirming any export, the program will often keep trying to export the module to a WAV/VGM/S98 file without actually saving anything. Sometimes, this causes the program to freeze when trying to quit.
## How to reproduce
1. Open a module.
2. Try to export it.
3. Watch.

## System Information

- **Operating System**: MacOS Mojave Version 10.14.6
- **BambooTracker Version**: v0.4.4
- **Build Type**: Official

#Edit: some wording

**Comment by rerrahkr** [comment]
Thanks for your report. I tested these file export on Windows and macOS, and found that this was happened on only macOS.
It was not synchronized between the export progressbar and the wave view.
I don't know what the cause is yet, so I'll check it out a little more closely.

**Comment by rerrahkr** [comment]
I fixed `0Dxx` detection in exporting at 0a5f88372277395f0ccec8b548f28c220e01ac12. Does the bugfixed dev-build work well on your workspace?

**Comment by Zexxerd** [comment]
how do I get or make the dev-build?

**Comment by OPNA2608** [comment]
Check the project page, section `Downloads` -> `macOS` -> `GitHub Builds` -> *`Development builds:`*. You'll want to pick the option labeled `Environment: APPVEYOR_JOB_NAME=for macOS (Modern)`, then click on the `Artifacts  1` tab.

**Comment by Zexxerd** [comment]
Yes, the bug-fixed build works perfectly. The dev-build seems a bit slow, though.

**Comment by OPNA2608** [comment]
That's normal, development/debug builds are expected to be slower than release builds.
