### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Unable to Copy and paste in the ssg channels while in a ym2203 layout(3fm,3ssg)

### ISSUE THREAD

**Issue by YoshiLightStar** [rerrahkr/BambooTracker#259]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

Unable to copy and paste in the ssg channels while using hide channels in a ym2203 style(3fm,3ssg)

## How to reproduce

1.Use Hide channels to only have 3 fm and 3 ssg
2.Type notes in ssg
3.Try copy and pasting in the ssg it should bring up the error 
"vector::_M_range_check: __n (which is 16) >= this->size() (which is 16)

## System Information

- **Operating System**: Windows 7 7601
- **BambooTracker Version**: v0.4.4 and lastest devbuild
- **Build Type**: Offical

**Comment by rerrahkr** [comment]
Thanks for your report. I fixed it at b8f57e1f5a999312474b5933b508abcf1774fe17.
