### ISSUE TITLE
"Mute/Solo Track" uses keyboard caret location, not mouse click location

### ISSUE THREAD

**Issue by jimbo1qaz** [rerrahkr/BambooTracker#26]
In 0CC/FT, right-clicking channel headers gives options to toggle/solo channel. (So does right-clicking the pattern itself, though the menu is different.)

In Bamboo:
- Right-clicking the pattern has the same menu as the header.
- "Mute/Solo Track" affects the channel under keyboard caret, which (unlike text editors) does not move to the mouse location. It should affect the channel under mouse cursor.
- When I "Solo Track" twice on different tracks (keyboard caret), the second time it unmutes all instead of soloing my new track.
- (bug or not?) 0CC "toggles solo" when double-clicking a channel header quite quickly (not slowly). Bamboo doesn't handle that case.

----

Bamboo has "mute track" (less useful than left-clicking) while 0CC has "toggle track" (identical to left-clicking). Neither tracker opens right-click menu when I press the keyboard Menu key, making the menu item useless (except 0CC but not Bamboo tells you the corresponding keyboard shortcut).

- I think Bamboo should display shortcut text for each menu action. it aids discoverability (https://news.ycombinator.com/item?id=18584381)
- Also, Bamboo should underline menu items by prepending & to letters. &Action becomes _A_ction and I can open the menu, then press A to activate that quickly from the keyboard. I feel it's faster than using a mouse. (I noticed the main menu already has underlines.)

**Comment by rerrahkr** [comment]
Since "Mute track" is the same as 0CC-FT "toggle track", I changed its name bddcf2bc4d709e94e6bf2765472713db0cd67365.

**Comment by rerrahkr** [comment]
Other issues were fixed in [v0.1.3](https://github.com/rerrahkr/BambooTracker/tree/v0.1.3).
