### ISSUE TITLE
[Windows|macOS|Linux|BSD] - silk icon set not DFSG compliant

### ISSUE THREAD

**Issue by alexmyczko** [rerrahkr/BambooTracker#260]
Hi 

The Silk Icon set is CC-BY-SA 2.5, which is not DFSG compliant, free software:
https://wiki.debian.org/DFSGLicenses#Creative_Commons_Attribution_Share-Alike_.28CC-BY-SA.29_v3.0

Is there a chance to find something else, that is DFSG compliant?

Best,

**Comment by rerrahkr** [comment]
Thanks for your report. I checked [the author's site](http://www.famfamfam.com/lab/icons/silk/) and there are a line:

> The icons can also be used under Creative Commons Attribution 3.0 License (Hi Debian folks!)

There seems to be no problem with the license. I'll update licenses/list.md to reflect this.

**Comment by rerrahkr** [comment]
> I'll update licenses/list.md to reflect this.

Done at 349f557cb1e807f0e692f5762fd3e367c2f16761.

**Comment by alexmyczko** [comment]
thanks, i hope there will be another release before https://release.debian.org/bullseye/freeze_policy.html
