### ISSUE TITLE
[macOS|Linux|BSD] - Localized manpages get installed to wrong directory

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#264]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

We currently install the manpages like so:

`$PWD/../BambooTracker*.1 -> $PREFIX/share/man/man1/`

Which usually dumps all manpages into one directory.

`/usr/share/man/man1/BambooTracker.1`
`/usr/share/man/man1/BambooTracker.fr.1`

According to [these specs for manpages](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html#idm236091757632), they should be moved into language-specific subdirectories:

`/usr/share/man/en/man1/BambooTracker.1`
`/usr/share/man/fr/man1/BambooTracker.1`

You can assign this issue to me and I'll get around to fixing this eventually. Unless someone else's quicker ofc. :sweat_smile: 

## How to reproduce

See [BambooTracker/BambooTracker.pro](https://github.com/rerrahkr/BambooTracker/blob/ce9eb30e88b292cf08c65302b14d8718e26c734c/BambooTracker/BambooTracker.pro#L603-L605).

## System Information

- **Operating System**: NixOS 20.03 (Markhor) x86_64
- **BambooTracker Version**: v0.4.4
- **Build Type**: Via package manager

**Comment by rerrahkr** [comment]
Thanks for your report. It is difficult to check installation of mans in my workspace, so could you fix it?

**Comment by OPNA2608** [comment]
I'll get around to fixing this at some point, yeah. Just wanted to have a tracking issue so i don't forget about it.
