### ISSUE TITLE
[bug] BambooTracker exits abruptly when updating a song's type. (Tested on: Mac OS)

### ISSUE THREAD

**Issue by Zexxerd** [rerrahkr/BambooTracker#267]
This happens when using "Update" to change a song's type in Module Properties.

**Comment by rerrahkr** [comment]
Thanks for your report. Sorry I can't use macOS right now, so it will take some time to check it.

**Comment by rerrahkr** [comment]
I changed updating method of song type at 4d404d3c01a485ef895b819203b9dfa0859013c4, does it work well?

**Comment by Zexxerd** [comment]
Yes, it works.
