### ISSUE TITLE
[Windows] - New Order Value Bug

### ISSUE THREAD

**Issue by Toonlink8101** [rerrahkr/BambooTracker#269]
> #### Checklist
> 
> 
> 
> - [ x] I am reporting exactly 1 bug with this issue.
> - [ x] This bug hasn't already been reported.
> - [ x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

When inserting an order after decreasing pattern length, the new order has a value of "FF" instead of the next unused value. This is easily reproducible by opening a new module, decreasing the pattern length by one, and then inserting an order.

![image](https://user-images.githubusercontent.com/73187589/96616025-aae72900-12c7-11eb-9e4b-5276a7f9a544.png)

## System Information

- **Operating System**: Windows 10
- **BambooTracker Version**: v0.4.4

**Comment by rerrahkr** [comment]
Thanks for your report. I fix it at 9db2d29513a0908c186640f5afc3492da32b2c09.
