### ISSUE TITLE
Enhancement: icon for BambooTracker

### ISSUE THREAD

**Issue by Decidetto** [rerrahkr/BambooTracker#27]
I have created an icon for BambooTracker that I would like to propose.
It's drawn in a pixel-art style, using only colours from the 12-bit master palette of the PC-98.
The 16x16 version is unique, while all other sizes are integer upscales of the 32x32 version.

I have attached a preview image and the .ico file in a ZIP archive.
![bambootracker ico-preview](https://user-images.githubusercontent.com/5384177/50011621-dfe40f80-ffbc-11e8-908d-cde4674164e3.png)
[BambooTracker icon.zip](https://github.com/rerrahkr/BambooTracker/files/2680583/BambooTracker.icon.zip)

**Comment by rerrahkr** [comment]
Wow, nice icon! Thanks @Decidetto!
I will use it from the next release :)

**Comment by alexmyczko** [comment]
if you make it BambooTracker.png it could be used together with the BambooTracker.desktop file (usable for GNOME or KDE)

**Comment by Decidetto** [comment]
@alexmyczko Of all sizes (16x16, 32x32, 64, 128, 256)?

**Comment by alexmyczko** [comment]
nah, 256x256 is just fine. svg is possible too, but png is just as fine.

**Comment by Decidetto** [comment]
Since they were drawn as raster graphics, I can only offer PNGs.
Here is the base icon as a 256×256 png:
![bambootracker256](https://user-images.githubusercontent.com/5384177/50047074-eb176800-00ae-11e9-8849-339d02441ec4.png)
And the tiny 16×16 version, which is unique:
![bambootracker16](https://user-images.githubusercontent.com/5384177/50047080-fec2ce80-00ae-11e9-9c29-27927e0be4ba.png)
Do make sure that the 256×256 version is used for all resolutions but 16×16.

**Comment by ehaupt** [comment]
> Since they were drawn as raster graphics, I can only offer PNGs.
> Here is the base icon as a 256×256 png:
> ![bambootracker256](https://user-images.githubusercontent.com/5384177/50047074-eb176800-00ae-11e9-8849-339d02441ec4.png)
> And the tiny 16×16 version, which is unique:
> ![bambootracker16](https://user-images.githubusercontent.com/5384177/50047080-fec2ce80-00ae-11e9-9c29-27927e0be4ba.png)
> Do make sure that the 256×256 version is used for all resolutions but 16×16.

Would it be possible to include this file as _BambooTracker.png_ in the icon directory? The FreeBSD port I am working on is currently fetching the file separately. The port is using the file for the very same purpose as @alexmyczko described.
