### ISSUE TITLE
[MacOS] - Incorrect Default Audio API

### ISSUE THREAD

**Issue by N-SPC700** [rerrahkr/BambooTracker#270]
## Bug Description

Audio defaults to JACK, even on MacOS systems not using JACK.

## How to reproduce

On a macOS system without a BambooTracker.ini, and a test release based on current master, BT picks JACK as the default on startup and an error window about audio initialization appears. No JACK device could be detected so initialization fails. if no previous API and/or device has been saved, like on a 1st time launch, BT should silently try the APIs in the preferred order. e.g. JACK -> no devices -> CoreAudio -> first/primary device.

## System Information
- **Operating System**: MacOS Mojave 10.14.5
- **BambooTracker Version**: `unstable-1c9a1ceb8339f6d132e5d7faef775cbc3ca269f8`
- **Build Type**: on travis CI, @OPNA2608's release testing

**Comment by OPNA2608** [comment]
To clarify, this was a build from a branch of mine that's based on 1c9a1ceb8339f6d132e5d7faef775cbc3ca269f8, built like a regular release as a test. This same behaviour can be replicated on the above commit & on Linux with JACK support enabled but no running JACK backend.

![grafik](https://user-images.githubusercontent.com/23431373/96708537-a7bc6d80-1399-11eb-9e1c-d5b48b3a8f0f.png)

It seems to decide to only use the first API RtAudio was told to support. I think upon launching, roughly the following should happen instead:

```
function audioInit()
  lastApi = Configuration.get ("Sound", "soundAPI")
  if lastApi != null then
    device = Configuration.get ("Sound", "soundDevice") or RtAudio.getAPI(lastApi).getDefaultDevice()
    setAudioConfiguration (lastApi, device)
  end

  rtaudio = null;
  # lists APIs according to RtAudio's order of preference, e.g. JACK -> Pulse -> ALSA
  for api in RtAudio.listAPIs() do
    device = api.getDefaultDevice()
    if device == null then
      stderr.write ("No default device for {api}, skipping...\n")
      continue
    end
    stderr.write ("Probing {api} - {device} ")
    try
      rtaudio = new RtAudio(api, device)
    catch
      stderr.write ("failed.\n")
      continue
    end
    stderr.write ("succeeded.\n")
    break
  end
  if rtaudio == null then
    errorWindow("Failed to detect usable audio settings. Please check the Sound configuration in the settings!")
  else
    setAudioConfiguration (rtaudio)
  end
end
```

**Comment by rerrahkr** [comment]
Thanks for your reports.
Checking the audio API on launch shares a process for detecting initialization failures such as #265, so it only tries one API available on the system. On the first launch, one of the available APIs will be selected according to the priority in RtAudio.
If you get an error, you can set the appropriate API in Configuration and it will be initialized accordingly from the next time onwards, so I don't think it is necessary to fix it.
But is it better to try multiple APIs only on the first boot until the audio stream is successfully initialized?

**Comment by OPNA2608** [comment]
> I don't think it is necessary to fix it.
> But is it better to try multiple APIs only on the first boot until the audio stream is successfully initialized?

I think yes. In terms of a new user's UX (user experience), I think it'd be preferable if the very first thing they saw wasn't an error message.
