### ISSUE TITLE
[Windows] - FM3ch Expanded labeling and muting bug

### ISSUE THREAD

**Issue by Toonlink8101** [rerrahkr/BambooTracker#272]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

When updating a module from "Standard" to "FM3ch Expanded," the labels are incorrect and the muting toggles of the second and third operators don't function as expected.

This is easily replicated by creating a new module, updating to FM3ch Expanded, and attempting to individually mute/unmute operators 2 and 3 of a 7th algorithm instrument.

![image](https://user-images.githubusercontent.com/73187589/97056306-4984bb80-154e-11eb-847a-abdf8457d8ee.png)

## System Information

- **Operating System**: Windows
- **BambooTracker Version**: v0.4.4

**Comment by rerrahkr** [comment]
Thanks for your report. This incorrect swapping is fixed in the next module open, so the song type change causes this display bug.
I didn't notice this bug, but I fixed baggy code related to the song type change in #267, so that the latest dev-builds seem to have fixed this bug.
