### ISSUE TITLE
[Linux (maybe more?)] - "_Map_base::at", "Recursive repaint detected", visual glitches & SIGSEGV on launch

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#276]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

On launch, BambooTracker throws an error message saying
```
An unknown error occured.
_Map_base::at
```
It also prints
```
QtWidget::repaint: Recursive repaint detected
```
on the command line.

Closing the error either crashes the whole application in a SIGSEGV or (only happened afew times) gives me a very messed-up GUI to interact with.

I was able to replicate this on less exotic hardware, although much less reliably. (which is to say: exactly once)

Desktop:
![grafik](https://user-images.githubusercontent.com/23431373/97144222-5d096f80-1764-11eb-9199-919b54eae355.png)

Phone:
![grafik](https://user-images.githubusercontent.com/23431373/97144865-84ad0780-1765-11eb-87a3-32ae8cf60382.png)

This didn't happen when testing with v0.4.4. I'll try `git bisect`ing this on my phone to figure out if that's actually related to the error or just a coincidence though.

## How to reproduce

I don't know how exactly this can be reproduced. Out of afew dozen startups on my desktop, it happened *once*. On my Linux phone, it happens every time I attempt to launch BT.

It *might* have something to do with system speed? My desktop runs at 4GHz while my phone has barely 1.2GHz. The application launch also is alot slower on my phone than on my desktop, maybe that is related to the repainting failing? Just a shot in the dark.

## System Information

- **Operating System**: NixOS 20.03 (Markhor) x86_64 & postmarketOS 1.23.0 aarch64
- **BambooTracker Version**: unstable 1c9a1ceb8339f6d132e5d7faef775cbc3ca269f8 & 6ad3d608bcbb8b7ff95ae230de8946b1dc1afb1e
- **Build Type**: Official (Linux test release) & Locally (via Nixpkgs & a version override)

**Comment by rerrahkr** [comment]
Thanks for your report.
Regarding painting events, I have changed only 8a242ed (#256), but  this was to prevent a crash when launching in the maximized window.

I'm assuming that the GUI is displayed after the initialization in the module's constructor, but I don't know when to trigger the actual drawing events in Qt, so depending on the hardware, accessing uninitialized data could cause errors.

Could you check 8a242ed? If crash, this commit may be the cause.

**Comment by OPNA2608** [comment]
I tried the commit before 8a242ed, it crashes but *differently*. It terminates with SIGSEGV before being able to bring up the GUI. I'll try rebuilding it with debug symbols and getting you a GDB backtrace. After that I'll try 8a242ed itself.

This'll take a good while though as it's just a phone I'm compiling this on, and I'm concerned about making it run too hot for too long.

**Comment by OPNA2608** [comment]
<details>
  <summary>GDB stacktrace @ 8f41e7e. Seems to be the exact same problem as #256.</summary>

![grafik](https://user-images.githubusercontent.com/23431373/97273447-a70d5680-1833-11eb-805f-475fc8d5eedd.png)

</details>

8a242ed crashes as explained in the original post, so that fix is definitely the breaking change.

**Comment by rerrahkr** [comment]
What surprises me is that 8f41e7e, which is a build of the same code as v0.4.4, has a bug.
Originally, v0.4.4 should have a bug of # 256, but it doesn't. It's strange 🤔

Anyway I think the bug in this issue is the problem of module data initialization and pattern editor drawing timing.
As a first aid, I try to skip the paint event until the internal data has been initialized.
