### ISSUE TITLE
[Linux] - High sample rate on ALSA causes slow & downpitched audio

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#279]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description
Selecting the ALSA API with a sample rate of 55466Hz properly connects to the ALSA backend of the system, but plays the 55466Hz audio stream as if it was a 48000Hz one. The effect of this is that whatever is being generated & played back sounds slower & lower pitched than it's supposed to.

I'm suspecting that this might be caused by a fixed sample rate somewhere in the `emulated chip` -> `ALSA backend` chain, so 44100Hz would have the opposite effect of being faster & pitched up, though by such a tiny percentage that it's hardly noticable.

See also https://github.com/rerrahkr/BambooTracker/pull/271#issuecomment-715927147

> Then I have set the API to ALSA [with 55466Hz sample rate] but sound became distorted (slower and down few semitones in pitch).

## How to reproduce

1. Start BambooTracker
2. Go to `Configuration` -> `Sound`
3. Select ALSA API, any device that works and isn't occupied
4. Choose 55466Hz sample rate
5. `OK`
6. Load & play a module

## System Information

- **Operating System**: NixOS 20.03 (Markhor) x86_64
- **BambooTracker Version**: master 1c9a1ceb8339f6d132e5d7faef775cbc3ca269f8
- **Build Type**: any

**Comment by rerrahkr** [comment]
Thanks for your report.
RtAudio calls `snd_pcm_hw_params_set_rate_near ()` when initializing ALSA, which seems to determine the available sample rates.
It may needs to compare the actual rate with the set rate after initialization, and show a warning dialog if they are different.
