### ISSUE TITLE
Problem when building 0.13 release under Linux

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#28]
`gui/mainwindow.cpp: In member function ‘void MainWindow::on_instrumentListWidget_customContextMenuRequested(const QPoint&)’:
gui/mainwindow.cpp:944:8: error: ‘class QAction’ has no member named ‘setShortcutVisibleInContextMenu’; did you mean ‘setShortcutContext’?
  edit->setShortcutVisibleInContextMenu(true);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        setShortcutContext
[...]
Makefile:1639: recipe for target 'mainwindow.o' failed
make: *** [mainwindow.o] Error 1
`

make produces lots of warnings related to mainwindow.cpp and one error above. OS is Ubuntu 18.04 LTS, all dependecies installed, I think.

**Comment by rerrahkr** [comment]
Since I use Qt 5.10.1 for development, it should not be a problem when building with later version.

**Comment by papiezak** [comment]
@OPNA2608:
`build-essential is already the newest version (12.4ubuntu1).`
`libqt5multimedia5-plugins is already the newest version (5.9.5-0ubuntu1).`
`qt5-default is already the newest version (5.9.5+dfsg-0ubuntu1).`
`qtmultimedia5-dev is already the newest version (5.9.5-0ubuntu1).
`
qmake seems to create the stash file correctly, make dies when dealing with mainwindow.cpp, like I wrote in the original post.

**Comment by OPNA2608** [comment]
> `qt5-default is already the newest version (5.9.5+dfsg-0ubuntu1).`

>I use Qt 5.10.1 for development

[This property was introduced with Qt 5.10 apparently.](http://doc.qt.io/qt-5/qaction.html#shortcutVisibleInContextMenu-prop)

I'm afraid you'll either have to:
· update Ubuntu to 18.10 to get Qt 5.11 via `qt5-default`
· wait until the property gets removed/replaced with a compatible alternative:
` Before Qt 5.10, setShortcutVisibleInContextMenu seems unnecessary. I will fix it.`
· manually compile Qt5, Qt5 Multimedia and Qt5 Multimedia Plugins which is *not recommended, to say the least* or
· use a different Distribution with a more up-to-date version of Qt5

**Comment by alexmyczko** [comment]
I'll create an official debian package for this! http://methyer.ethz.ch/debian/ 
we'll need a manual page BambooTracker.1 and write a wnpp bug (RFP/ITP)

**Comment by OPNA2608** [comment]
I have a working Nix package, but I'll wait until we get a proper `v1` or at least `v0.2` release before submitting it to the nixpkgs repo.
*(that is off-topic though. i suggest opening a seperate issue about it)*

**Comment by rerrahkr** [comment]
I fixed it 8c3f2b71e782334c3fd2570c7b6532f5fc6d1073

**Comment by trebmuh** [comment]
If that can be of any help, a fresh build from https://github.com/rerrahkr/BambooTracker/commit/99b9ed33404bfd8bd87edb05d7525f6e1cf39723 is building on a Debian stable (aka "_Stretch_"). I launched it and the main GUI appeared. I didn't get further than that so far.

**Comment by papiezak** [comment]
OK looks like it was fixed and can be build even on stable Debian. Closing then.
