### ISSUE TITLE
[macOS] - "Fresh" run tries to open nonsense file

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#282]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

Reporting for @N-SPC700

## Bug Description

A "fresh" first run (`mv ~/.config/BambooTracker ~/.config/BambooTracker-bak`) of BambooTracker errors about trying to open a nonsense module called `-psn_0_...`

![grafik](https://user-images.githubusercontent.com/23431373/97960883-86ed1280-1db2-11eb-8f51-8e9416c41c0a.png)

I did some research while trying to debug this with him. Supposedly macOS uses "Apple Events" when launching an app through Finder, which calls the contained binary with its "application serial number"… or something? It supposedly does the same when using "Open with…" on a regular file & picking an app.

I know absolutely nothing about macOS. My initial response would be "we should talk to macOS to figure out what files BT was called on", but I don't know how much effort that will take without a local macOS machine to test everything on. A dirty workaround would be to ignore CLI arguments starting with `-psn_`: it'll prolly work for now but ideally it wouldn't be a long-term solution. I think this whole ordeal breaks loading modules at launch on macOS too?

## How to reproduce

1. (Re)move `~/.config/BambooTracker`
2. Launch BambooTracker.app via Finder

## System Information

- **Operating System**: Mac OS X 10.14.5
- **BambooTracker Version**: master b8cd8c88939710a143c9000d091f97b4656966c9
- **Build Type**: development build

**Comment by rerrahkr** [comment]
Thanks for report.

> 1. (Re)move `~/.config/BambooTracker`

I don't know why I can't reproduce it on my macOS mojave the way you did this...

---

I noticed I should make `QApplication` and send arguments to it before parsing a module path argument:
from https://doc.qt.io/qt-5/qapplication.html
> QApplication also deals with common command line arguments. Hence, it is usually a good idea to create it *before* any interpretation or modification of `argv` is done in the application itself.

and from https://doc.qt.io/qt-5/qapplication.html#QApplication
> **Note:** *argc* and *argv* might be changed as Qt removes command line arguments that it recognizes.

Furthermore, I searched `QApplication` source and found it handles `-psn_` when parsing arguments in its constructor (https://github.com/qt/qtbase/blob/564b59d903683b14c75b72a3e93367717f201def/src/gui/kernel/qguiapplication.cpp#L1572-L1583).
Looking at the code, it seems to be an implementation that can't be a long term solution like you mentioned, but it seems to get other benefits from `QApplication` regarding arguments.

I will fix the code once and open a new PR. For some reason it doesn't reproduce on my Macintosh, so I'm sorry to ask you many times, but could you please test it?
