### ISSUE TITLE
[macOS|Linux] - No repainting if loading module on startup fails

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#284]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

If BambooTracker is started with a module path to open and that module cannot be loaded properly, an errorbox will be displayed and the interface painting is seemingly interrupted.

![grafik](https://user-images.githubusercontent.com/23431373/98667766-2aa86680-234f-11eb-9dc7-5b62dc836e9a.png)
![grafik](https://user-images.githubusercontent.com/23431373/98667673-051b5d00-234f-11eb-8b47-30374ad5014b.png)

## How to reproduce

1. `BambooTracker This_file_does_not_exist.btm`

## System Information

- **Operating System**: Ubuntu 18.04.5 LTS
- **BambooTracker Version**: v0.4.5
- **Build Type**: Nix package manager & built locally

**Comment by rerrahkr** [comment]
Thanks for your report. I was a little surprised that the paint event problem is also happening in the order list. I'll check paint calls.

**Comment by rerrahkr** [comment]
BT is trying to temporarily disable paint events while the module is loading, but I accidentally remove unlocking process when fixing the I/O error dialog. Fixed at 32ccce580667b867d447f7e560833546a6ca04e4.
