### ISSUE TITLE
[Windows|macOS|Linux|BSD] - "WAV export" exports nothing

### ISSUE THREAD

**Issue by Zexxerd** [rerrahkr/BambooTracker#287]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

WAV export in v0.4.5 exports a 6-second, empty WAV file. (Tested on MacOS)
## How to reproduce

1. Go to File > Export > WAV
2. Export your module

## System Information

- MacOS Mojave
- v0.4.5
- Build type: Official

**Comment by rerrahkr** [comment]
Thanks for your report, but I couldn't replicate it on my macOS mojave. It may only occur on specific modules. Does the song contain `0Bxx`,` 0Cxx` or `0Dxx`? If possible, could you upload or email the module that causes the problem?

**Comment by Zexxerd** [comment]
Never mind, I tried re-exporting the song and it worked.

**Comment by Zexxerd** [comment]
Of course, if I can find a way to recreate the bug (if there is one), I'll reopen this.
