### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Note phase doesn't reset on new note trigger, attack rate of note doesn't change in VGM/S98 exports

### ISSUE THREAD

**Issue by Zexxerd** [rerrahkr/BambooTracker#292]
#### Checklist
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

Firstly, I'm doing a song that has an instrument with an attack rate that I want to change dynamically. I also need to have the note reset its phase while in the attack phase. Unfortunately, when I attempt to do this, it just keeps continuing its attack phase, so I have to switch to another channel to reset the note phase.
[Here's](https://cdn.discordapp.com/attachments/780969773802192917/780970089474162758/wilderness_expected.wav) what it's supposed to sound like. (done with two channels)
[Here's](https://cdn.discordapp.com/attachments/780969773802192917/780970125528399902/wilderness_actual.wav) what it sounds like if I don't use two channels.

Secondly, it appears that changing the attack rate of a note doesn't work in VGM/S98 exports. Actually, it doesn't seem clear if it's not changing the attack rate or if it's attack rates are different, but the note sequence escalates faster in the S98 export than in the VGM export.

[Bambootracker](https://cdn.discordapp.com/attachments/780969773802192917/780971417771442226/wilderness_bt.wav)
[VGM](https://cdn.discordapp.com/attachments/780969773802192917/780971480510365746/wilderness_vgm.wav)

## How to reproduce

#1 
1. Make an instrument with a long attack rate
2. Play a note using that instrument
3. Before the attack phase is done, play another note.

#2 
1. Do the above instructions.
2. Export to VGM/S98
3. Compare the playback.
## System Information

- **Operating System**: MacOS v10.14.6
- **BambooTracker Version**: v0.4.5, non-exclusive
- **Build Type**: Official

**Comment by rerrahkr** [comment]
It is a characteristic of the chip that the phase is not reset when the key is turned on. So in order to do what you want, you need to key off before the next key on so that the envelope is completely zero. As a feature that may help you, BambooTracker's Instrument has an "Envelope reset" that will force the envelope to zero 1 tick before the next key-on.

The difference in sound between BT and VGM or S98 is probably a matter of player emulation. Since those files are just playback logs, they have identical register writes.

**Comment by Zexxerd** [comment]
Could I suggest an effect that resets the envelope to 0 (or some other number)? (e.g. EExx)

**Comment by rerrahkr** [comment]
It may be possible to implement an effect similar to the note cut effect `0Sxx` that forces it to zero. I try it when implementing new effects.

**Comment by Zexxerd** [comment]
Yeah, like the former.
