### ISSUE TITLE
[Linux] - Unable to load instruments from  .FF bank files

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#295]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [ ] This bug hasn't already been reported.
> - [ ] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

On latest master, instrument import from .FF banks is impossible, throwing an error message:
couldn't load <path to .FF file>
`vector::_M_range_check__n (which is 25) >= this->size() (which is 25)` 

## How to reproduce

1. Select an .FF file
2. Click on any instrument to import

## System Information

- **Operating System**: Arch Linux x64
- **BambooTracker Version**: latest master, compiled from source

**Comment by rerrahkr** [comment]
Thanks for your report. It was a mistake of indexing, I fixed it at 26bee5afbb270c593f4b5c5c80d5400b41ac6655.

**Comment by freq-mod** [comment]
Thanks for the fix!
