### ISSUE TITLE
[Feature] - Improve README readability

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#297]
> #### Checklist
> 
> 
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

The README is large and messy. *Too large, too messy.* From what I can see, regular users, developers and package maintainers alike very frequently don't read it because it's too large and badly structured.

- build& configuration instructions are almost never found
- link to the wiki gets overlooked easily
- alot of the text is duplicated in the wiki and could easily just be removed

---

Some ideas for improvements:

- [x] We should check what's already in the wiki and remove the duplicate texts from the README.
  - [x] Effects list
  - [x] Shortcuts list
- [x] We should look into generating a Table of Contents for a quicker overview of the points of interest.
- [x] Maybe the order of sections could be improved a little?
  I change my opinion about the best order every time I look at it, so I consider it done for now.

Open for more feedback, ideas and/or examples, either here or on the Discord server.

**Comment by freq-mod** [comment]
Effects and shortcut lists can be removed, the same, or even more detailed things are in the wiki anyway.

**Comment by freq-mod** [comment]
Also, enitire File I/O section can be removed, for the same reasons as above.

**Comment by freq-mod** [comment]
One more nitpick - add some mentions on Arch Linux - based distributions. I know there is AUR repo, https://aur.archlinux.org/packages/bambootracker-git/, but:

>  andrewlin16 commented on 2020-11-07 20:10	

>Started getting this error while trying to make the package:

>install: cannot stat 'BambooTracker.desktop': No such file or directory

>Probably due to https://github.com/rerrahkr/BambooTracker/commit/3be2ed286ab05c3e9ada0d50daa34dff288ae2c0 which moved a bunch of data files around. Here's a patch that fixes the PKGBUILD to pull the resources from the new path: https://pastebin.com/gDn9t6gX

Also, dependencies are installed differently and have different names than in Ubuntu/Debian.

**Comment by rerrahkr** [comment]
For the effects list and shortcut list, I had written them in the README so that people can check them offline, but do you check them in the wiki? Also I have an idea to split them into separate files if necessary.

As for structure, I have a plan to use GitHub Pages to create a website for BambooTracker.
GitHub is a bit confusing for non-coders, so I'll have a website that gives a simple introduction to the application; [Klystrack](http://kometbomb.github.io/klystrack/) and [Deflemask](https://www.deflemask.com/) are good examples.
I can't make it right away, but I think this will help organize the README on GitHub.

**Comment by freq-mod** [comment]
>GitHub is a bit confusing for non-coders, so I'll have a website that gives a simple introduction to the application; Klystrack and Deflemask are good examples.

Well, that's a good idea, having a home website for a project rather than just only GH repo and Discord server :+1:

**Comment by freq-mod** [comment]
So, after #306 got merged, is there still anything to do or improve? Or it can be closed?

**Comment by OPNA2608** [comment]
I think the original points of critique are solved for now.

> I had written them in the README so that people can check them offline, but do you check them in the wiki?

I'm wondering if it may make sense to register the wiki as a git submodule<sup>1</sup> in `data/docs` and somehow auto-update the submodule & package the wiki's contents when doing a build upload. I think that should solve the possibility of redundant & outdated versions of those in-repo documents when only the wiki gets updated by users. That's outside of this issue's scope though, just throwing around the idea.

<sup>1</sup>:
![grafik](https://user-images.githubusercontent.com/23431373/107224934-6ddea800-6a18-11eb-8a46-357b722fc708.png)
