### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Drawing bug in arpeggio macro editor when window is resized

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#299]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

This glitch is very minor, since it happens only with certain conditions, or when using some window managers under Linux. I'm not completely sure if it's replicable under Windows.

![image](https://user-images.githubusercontent.com/32672779/101995247-eb13c800-3cc8-11eb-9641-f5b34ab350d9.png)

## How to reproduce

1. Create a FM  instrument
2. Resize instrument window so that, in arpeggio/pitch tab, only arpeggio or pitch macro can be seen at once
3.  Move scroll bar up and down
4. Text and macro will become distorted

## System Information

- **Operating System**: Arch Linux x64 + DWM
- **BambooTracker Version**: latest master

**Comment by rerrahkr** [comment]
Thanks for your report. I fix it at 5449f96b3345f91f0532687b7e209c38ebf0d181.

**Comment by freq-mod** [comment]
Thanks for the fix!
