### ISSUE TITLE
A few things regarding SSG

### ISSUE THREAD

**Issue by marysiamzawka** [rerrahkr/BambooTracker#3]
Hey, good job on the first release! I'm surprised by how much work did you put into the SSG portion, but in my opinion you missed (or maybe didn't implement yet, who am I to know) two thhings that would make using the SSG that much easier:

- Envelope autotuning (AutoEnv)
If you set the SSG instrument to use an envelope (saw/triangle), you can control its pitch in the pattern window. However, if you choose a tone+envelope instrument (Tri w/Saw w), only the tone pitch gets modified while the envelope pitch stays static. It would make things easier if you could add a flag that sets the envelope pitch *along* with the tone pitch (so when you play F-2, both envelope and tone pitches are F-2). Moreover, if that gets implemented, an ability to change the pitch ratios (for example ratio 1:2 would   play the tone at F-1 while the envelope is played at F-2,like in Vortex Tracker 2) would be highly appreciated.
- ~~Noise+tone/envelope combos~~
~~One thing that has been omitted was the combination of Noise with Tone or Envelope (or both). It makes for really interesting sounds.~~ It actually is there, I just couldn't manage to find it. (If anyone is still interested, set the Waveform to Tri or Saw, and set the Tone/Noise to T+N)

I haven't digged into the FM portion quite yet (because i'm a total n00b when it comes to FM), but so far i like where it's going!

**Comment by rerrahkr** [comment]
Thank you for your advice.
I want to improve SSG effect, so I will check Vortex Tracker 2.

**Comment by marysiamzawka** [comment]
0CC-FT also makes use of AutoEnv, it's hidden under the `Hxy` effect

**Comment by papiezak** [comment]
I took a look at SSG instrument editor and two things:
- Square mask selector isn't good; if I would want to set it to "C5+28", for example, it would take absurdly long time to scroll down the list to reach that choice. It might be a good idea to split it into two objects: a note list and that '0-31 selector' (envelope pitch?)
- In a discussion for Wohlstand/OPN2BankEditor#46 you stated:
>The volume resolution of hardware envelope is 32, finer than software envelope that it is 16.

And I have a question here - only eight values are permitted (Hard 0-7), why is that?
![hardware env](https://user-images.githubusercontent.com/32672779/52430800-2eb6ad00-2b07-11e9-8dae-98bcc20a0555.png)

I am a complete n00b when it comes to SSG, so I'm sorry if it's a stupid question

**Comment by rerrahkr** [comment]
> a note list and that '0-31 selector'

Thanks for your idea! I try to consider its implementation including AutoEnv.

> only eight values are permitted (Hard 0-7)

Those are types of SSG-EG, hardware envelope shape (see [this](http://nemesis.hacking-cult.org/MegaDrive/Documentation/YM2608J%20Translated.PDF) 2-5-2). Hard 0 corresponds to SSG-EG No. 0.
32 is the volume resolution of SSG-EG, but We cannot change SSG-EG volume scale. So we can only select its shape type and frequency.

**Comment by papiezak** [comment]
I see. Thanks for clarifying!

**Comment by rerrahkr** [comment]
After I used Vortex Tracker 2 and Arkos Tracker 2, it seems I should change SSG waveform editor more useful for buzzer effect. I will work on the following tasks in `fix-ssg-waveform-edit` branch.

- Rename "square mask" to "modulation"
- Add inverse sawtooth,  square-modulated inverse sawtooth
- Rename "Tri w", "Saw w" (square-masked triangle, square-masked sawtooth) to "SQM Tri", "SQM Saw" (square-modulated triangle, square-modulated sawtooth)
- Add triangle-modulated square, sawtooth-modulated square, inverse-sawtooth-modulated square
- Add modulation frequency selections by raw pitch (register value) and ratio between tone frequency and modulation frequency (like AutoEnv in VT2)
- Remove modulation frequency selection by note+pitch (it seems useless than AutoEnv)

At 51224a59a8c752b740d1a6aaebee61266c932cf8, note+pitch modulation value is converted to raw value by internal processing for backward compatibility.

**Comment by rerrahkr** [comment]
I finished adding autoenv at 72627b195a474c3617d552b5483c05be25391c9d.

**Comment by rerrahkr** [comment]
> 0CC-FT also makes use of AutoEnv, it's hidden under the `Hxy` effect

In b7f859066989bac0c4396dd52a8474ea2b45b572 and bebddb5e2a3059bae7e3db60c4a5d904dfae9c16, I added the pattern effects about autoenv: `0Hxy`, `0Ixx` and `0Jxx`. Note, these effects follow the specifications of the original FamiTracker, not 0CC.

Since the implementation of autoenv is finally over, I close this issue.
