### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Unable to paste MMLDRV text envelope data

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#300]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

I'm unable to load MMLDRV textual instrument data (at least those created by YM2608 Tone Editor), with tracker reporting that clipboard content doesn't match the MMLDRV format.

// name
@0    4   5
   31   0   0   7   0  32   0   0   0   0
   31   0   0   7   0   0   0   8   2   0
   31   0   0   7   0  32   0   7   0   0
   31   0   0   7   0   0   0   0   0   0

**Comment by rerrahkr** [comment]
This is the bug of YM2608 Tone Editor. The default MMLDRV output format is wrong: DT2 is skipped in all operators. I will fix it.
