### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Error when changing envelope release options mid-note

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#304]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

I don't know exactly how did that happen, but:
![Przechwycenie obrazu ekranu_2021-01-04_16-39-04](https://user-images.githubusercontent.com/32672779/103552171-c5cf3f80-4eab-11eb-87ad-aff30ae32d71.png)

Steps to replicate (?):
1. Create a SSG instrument
2. Play two notes at once (again, I'm not sure it must be that way)
3. Go to "envelope" tab
4. Click on "release" bar a few times
5. If it doesn't replicate, try playing note on octave 7, adding tone and noise mix, changing waveforms... it's almost random

**Comment by rerrahkr** [comment]
Thanks for your report. It is difficult to replicate it on my environment, however, I try to fix the bug of instrument sequence which may cause the out of range error and relate to this issue.

**Comment by freq-mod** [comment]
I can't replicate it anymore, so closing.
