### ISSUE TITLE
[|Linux|BSD] - Unable to build (current master, Linux)

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#305]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

BambooTacker build process errors out with 
`/usr/bin/ld: cannot find -lrtaudio`
`/usr/bin/ld: cannot find -lrtmidi`
`collect2: error: ld returned 1 exit status`

RTAudio and RtMIDI submodules were initialized and pulled.

**Comment by rerrahkr** [comment]
I'm not well known how to build project by qmake because I always do by Qt creator, but IIRC the .pro file given to qmake has changed since 7f3e5a25349a2a693e2840d66ab2d071c2179fe8:
```bash
$ qmake Project.pro   # Changed from BambooTracker.pro
```
When giving BambooTracker.pro, RtAudio and RtMidi libraries are not built that make an link error.

**Comment by freq-mod** [comment]
Ok, I see. I tried to use Project.pro, but it gave me that huge amount of errors:
https://gist.github.com/freq-mod/f94863d4a00da69acbec0bde1096a2b4

**Comment by freq-mod** [comment]
Anyways, seems like some parts of README.md, above all _Building_, will need changes then...

**Comment by freq-mod** [comment]
Also, tried building the tracker via Qt Creator, it failed as well :thinking:

**Comment by OPNA2608** [comment]
> Anyways, seems like some parts of README.md, above all _Building_, will need changes then...

Was noted in https://github.com/rerrahkr/BambooTracker/issues/263#issuecomment-752082492, I currently don't have the time to get around to that. I'll give a short summary of the ""new"" build instructions, let me know if that helps you:

#### Prerequisites:
* Qt5 (Qt development packages, Qmake)
* ALSA
##### Optional/Conditional:
* pkg-config
* PulseAudio
* JACK
* RtAudio and/or RtMidi (if non-vendored versions are preferred)

#### Build steps
```bash
# Clone the repository
git clone https://github.com/rerrahkr/BambooTracker
cd BambooTracker
mkdir build
export BT_OPTIONS="CONFIG+=release CONFIG-=debug PREFIX=$PWD/build"

# If using vendored Rt libraries, initialise the submodules
git submodule update
# and if desired, explicitly specify the desired optional APIs (PulseAudio/JACK/OSS4)
# for the configuration to fail if any of them are unavailable
export BT_OPTIONS="$BT_OPTIONS CONFIG+=use_pulse CONFIG+=use_jack"
# else specify which Rt libraries should be looked up with pkg-config
export BT_OPTIONS="$BT_OPTIONS CONFIG+=system_rtaudio CONFIG+=system_rtmidi"

# Configure (don't cd into BambooTracker!)
qmake Project.pro $BT_OPTIONS
make qmake_all # configure subprojects, suggested to do up-front

# Build & install to local prefix
make -j4 && make install

# Run
./build/bin/BambooTracker
```

It might help to reclone the repo (see above) or completely flush your configured state:
```bash
make distclean
# run qmake with your preferred settings afterwards
```

Let me know if that helps, we can debug this more quickly on Discord if you'd like. I don't use Qt Creator so I haven't tested compilation with it.

**Comment by freq-mod** [comment]
@OPNA2608 
> If using vendored Rt libraries, initialise the submodules
git submodule update

`git submodule init` must be run before update, or else build will fail. But anyway, thanks!

As for README.md, I might propose a new one in few days time...
