### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Unable to load certain .PVI bank

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#308]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---
[KGB.zip](https://github.com/rerrahkr/BambooTracker/files/5836464/KGB.zip)  - BambooTracker is unable to load the PVI file, throwing error about it being corrupted. However, FMP song players like FMPMD2000 recognize this file and can play it together with a song that uses this sample bank.

**Comment by OPNA2608** [comment]
The bank file has the magic number `PVI1`, the PVI file parser checks for `PVI2`.
https://github.com/rerrahkr/BambooTracker/blob/56305bd87dc3c9ec710f41fe84e2a089b6d65146/BambooTracker/io/pvi_io.cpp#L39-L40

From a cursory look the header looks fairly similar to what I've seen in PVI2 files. Can you hex edit the file from `PVI1` to `PVI2`, try to import it again and report what happens? If you don't have any hex editor installed you can use dd.

```sh
printf "PVI2" > KGB2.PVI
dd if=KGB.PVI of=KGB2.PVI bs=1 seek=4 skip=4
```

**Comment by freq-mod** [comment]
Yes, not it reads the file correctly, thanks.

**Comment by rerrahkr** [comment]
> Can you hex edit the file from `PVI1` to `PVI2`, try to import it again and report what happens?

It also worked well too. I don't know the details of the format, but it seems to work fine for loading samples, so I'll make BT support "PVI1" as well.
BTW there was a bug in the ADPCM preview in the latest commit, so I will also fix it.

**Comment by rerrahkr** [comment]
> BT support "PVI1"

Done at 5180729bffc8b988eafe331b265b9482d08df10e.

**Comment by OPNA2608** [comment]
> I don't know the details of the format

[It's not perfect but has some details](https://github.com/OPNA2608/libopenpmd/blob/ef45d6110e99e0eaaaf4803a02397a4954a85471/docs/pvi.txt). Noteworthy bits of the header:

- 0x0008 has a 2-byte "Delta-N" value to be used for playback (the rate field in the bottom right of the ADPCM instrument editor)
- 0x000B has a 1-byte number of instruments in the bank
