### ISSUE TITLE
[Feature] - Add Granular Sample Mangling and an FM Drum Synth, and you'll have Autechre in a Box!

### ISSUE THREAD

**Issue by kirkmarkarian** [rerrahkr/BambooTracker#309]
> #### Checklist
> 
> 
> 
> - [ ] I'm requesting exactly 1 feature with this issue.
> - [ ] This feature hasn't already been requested.
> - [ ] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

Really not a lot more to say here - just noticed it's using my fave FM synthesis, complex enough to get a TON of useful sounds out of, and a nice, clean tracker interface.  If these features were added internally (not VST/AU effects) and maybe a multi-purpose Freeverb reverb...  Hot Damn!

The drum synth would not have to be much different than the already present FM synthesis UI that's already included, just tighter preset pitch/envelope options, maybe a tab to switch to that option within the same window.  

Granular synthesis to make audio smears and ghostly sample manipulation or crackles/pops.  

A reverb to use here and there.

Most trackers choose to use the plugin architecture, but if it's all internal, just seems nicer.  The tracker already has a good sound.

**Comment by Midi-In** [comment]
This sounds like something very much out of scope of the program. Bambootracker and it's export formats target the hardware, and it would need to be extended beyond the capabilities of said hardware for these features to be implemented.

**Comment by freq-mod** [comment]
As @Midi-In wrote. if there is anything that is unsupported by Yamaha YM2608 chip or system (NEC PC-88, NEC PC-98) that uses this chip, this tracker won't have it. So, forget about reverb, YM2608 can't do this. Drum synth? Instrument editor is your friend, pitch/envelope control can't be any tighter IMO (or can they...?). Granular synth? No, it's a FM synth with square wave generator and hardware ADPCM codec. You can manipulate ADPCM samples with instrument editor, though. Plugins? As @rerrahkr wrote in #212, adding support for anything else will bloat the project.

BambooTracker is **not** a DAW mimicking some generic FM synthesis implementation. It has a specific task, creating songs for Yamaha OPNA synthesizer, be it real or emulated.

**Comment by kirkmarkarian** [comment]
Okeydokey, nevermind.  I'm doing great with Renoise.  Been wishing they'd put in an actual FM synth, granular synthesis/sample mangling.  Their reverb is smokin' hot.  In any case, glad to hear Yamaha OPL synthesis (great memories from my childhood) is doing well here!

**Comment by rerrahkr** [comment]
To be honest, I'm not sure what kind of features you're requesting, but they are probably things that would be difficult to reproduce on a PC-98.
Features that are too advanced can be difficult to play on the real chip, and are difficult to implement.

**Comment by kirkmarkarian** [comment]
> To be honest, I'm not sure what kind of features you're requesting, but they are probably things that would be difficult to reproduce on a PC-98.
> Features that are too advanced can be difficult to play on the real chip, and are difficult to implement.

That's OK, I gave up already (see last post) - seems to be not in the scope of the project.  Thanks for replying, though!
