### ISSUE TITLE
[Linux : Ubuntu 20.04.1] - Master branch building error :  "./midi/midi.hpp:33:10: fatal error: RtMidi.h: No such file or directory"

### ISSUE THREAD

**Issue by traditionalgithub** [rerrahkr/BambooTracker#310]
## Bug Description

Building error : Unable to build the master branch of  of Bamboo Tracker due to "lacking RtMidi.h" , the error message is as follows :

```
g++ -c -pipe -O2 -std=gnu++1y -Wall -W -Wall -Wextra -Werror -pedantic -pedantic-errors -D_REENTRANT -fPIC - DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Iinstrument -Imodule -I../submodules/RtAudio/src -I../submodules/RtMidi/src -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o mainwindow.o gui/mainwindow.cpp
In file included from gui/mainwindow.cpp:80:
./midi/midi.hpp:33:10: fatal error: RtMidi.h: No such file or directory
   33 | #include "RtMidi.h"
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:3081: mainwindow.o] Error 1
```
## How to reproduce

This error emerges following the regular steps of the building process described in the README.md. The only difference is that after cloning the source, the rest of the process should take place in ./BambooTracker/BambooTracker instead of /BambooTracker, or qmake does not print out the "Project MESSAGE" and the following message emerges when making :

```
cd submodules/RtAudio/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/username/Music/BambooTracker/submodules/RtAudio/RtAudio.pro CONFIG-=debug CONFIG+=release ) && make -f Makefile 
make[1]: Entering directory '/home/username/Music/BambooTracker/submodules/RtAudio'
make[1]: *** No rule to make target 'src/Rtaudio.cpp', needed by 'Rtaudio.o'.  Stop.
make[1]: Leaving directory '/home/username/Music/BambooTracker/submodules/RtAudio'
make: *** [Makefile:76: sub-submodules-RtAudio-RtAudio-pro-make_first] Error 2
```

## System Information

The system producing this error is Ubuntu 20.04.1  LTS. The out message of "qmake CONFIG-=debug CONFIG+=release" is as follows :
```
Project MESSAGE: Qt is version 5.12.8
Project MESSAGE: Configured compiler is GCC
Project MESSAGE: Compiler is version 9.3.0
```
The related package versions are as follows (which are from the default repository of Ubuntu 20.04.1 ) :

- build-essential : 12.8ubuntu1.1
- qt5-default : 5.12.8+dfsg-0ubuntu1
- qt5-qmake : 5.12.8+dfsg-0ubuntu1
- qt5-qmake-bin : 5.12.8+dfsg-0ubuntu1
- libqt5multimedia5-plugins : 5.12.8-0ubuntu1
- libqt5multimedia5 : 5.12.8-0ubuntu1
- qttools5-dev-tools : 5.12.8-0ubuntu1
- libasound2-dev : 1.2.2-2.1ubuntu2.3
- libpulse-dev : 1:13.99.1-1ubuntu3.8
- libjack-jackd2-dev : 1:13.99.1-1ubuntu3.8

**Comment by freq-mod** [comment]
I wrote about that in #306 which is yet to be merged. You must run these commands before building:
`git submodule init`
`git submodule update`

Please try now.

**Comment by OPNA2608** [comment]
The README is currently outdated and in need of a cleanup. Could you please check out the updated compile instructions in #306 and perhaps give feedback over there on what may be missing from it?

---

> … after cloning the source, the rest of the process should take place in ./BambooTracker/BambooTracker instead of /BambooTracker …

That is incorrect, you need to run qmake and make in ./BambooTracker. The real problem is
```
*** No rule to make target 'src/Rtaudio.cpp', needed by 'Rtaudio.o'.  Stop.
```
presumably because you haven't checked out the RtAudio submodule yet.

> … or qmake does not print out the "Project MESSAGE" …

<details>
  <summary>blablabla "make qmake_all" after "qmake" helps</summary>
  
That is normal because qmake lazily configures the subdirectories once they're actually touched by the make process. Had your build progressed past RtAudio, then it would've given you qmake output from RtMidi next, then from BambooTracker.

</details>

**Comment by traditionalgithub** [comment]
Yes, the build is successful following the the updated README.md. Thank you all!
