### ISSUE TITLE
[Feature] - Support for importing P86 & PZI banks

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#313]
> #### Checklist
> 
> 
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

[P86](https://github.com/OPNA2608/libopenpmd/blob/551004c9c8915774273a73b3c4c7db35bef3dbff/docs/p86.txt) and [PZI](https://github.com/OPNA2608/libopenpmd/blob/ef45d6110e99e0eaaaf4803a02397a4954a85471/docs/pzi.txt) are formats that can be used in PMD for 86PCM sample playback. Even if BT lacks support for 86PCM, being able to import such banks and convert them for use on the ADPCM channel would be great.

I've attached some examples that can be used to validate such an implementation.

[Samples.tar.gz](https://github.com/rerrahkr/BambooTracker/files/5856545/Samples.tar.gz)

**Comment by freq-mod** [comment]
If implementation of this turned out to be possible, [PPS](https://github.com/OPNA2608/libopenpmd/blob/master/docs/pps.txt) banks support containing 4-bit PCM would also be great.

**Comment by rerrahkr** [comment]
At de3d7a7346cba4bb03a5eaaf6151645c4fdc10c3, BambooTracker supports P86, PZI and PPS files by converting their samples with ADPCM. Thanks for your requests!

**Comment by freq-mod** [comment]
@rerrahkr thanks, importing works perfectly, yet I have some questions:
1. In case of some PZI banks, there is a delay between note press and sample being played while jamming during sample import. Is it because PCM => ADPCM conversion?
2. PZI samples have much worse quality, there is a lot of noise and distortion. It's because ADPCM conversion?

**Comment by rerrahkr** [comment]
Since BambooTracker needs to handle more than the 127 instruments it can hold, the selected instrument will be loaded in the bank import window the first time you press the jam key. Such gaps occur because the ADPCM instrument needs to write their samples to memory.
