### ISSUE TITLE
[Feature] - Panning Sequence

### ISSUE THREAD

**Issue by Toonlink8101** [rerrahkr/BambooTracker#314]
> #### Checklist
> 
> 
> 
> - [x ] I'm requesting exactly 1 feature with this issue.
> - [ x] This feature hasn't already been requested.
> - [x ] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

A panning sequence would be very useful for panning arpeggiation. By this, I mean that a stereo-like effect could be simulated by quickly changing the panning between left, right, and/or center. This is currently only possible when speed is set to 1, a speed which is otherwise unnecessary due to the many delayed effects. 

An example of this is found in the second pulse channel of this Gameboy Color song: [https://youtu.be/D0hXas8Jyao?t=1045](https://youtu.be/D0hXas8Jyao?t=1045)

The easiest implementation might be to add either another tab to the instrument editor or another section under the arpeggiation/pitch tab.

**Comment by rerrahkr** [comment]
Thanks for your request. I had thought about implementing that before, but put it off because I wasn't sure if there would be a demand for it.
It will be a new instrument property, so it will be a little harder to implement, but I think it can be done.

> add either another tab to the instrument editor

It will probably be implemented like this.

**Comment by rerrahkr** [comment]
I added panning sequence macro to the FM / ADPCM instrument editor in 2f8cfb505e0ad9f5433527eb81cbbefc0d6bb516.

**Comment by Toonlink8101** [comment]
Thanks for adding it in! Between this and the retrigger command, I look forward to the next release :)
