### ISSUE TITLE
[macOS|Linux|BSD] - Order list drawing bug

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#317]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

There is a bug where every 7th or so order is dispayer as a blank line, without any numbers. Every module I loaded displays this behaviour.

**Comment by freq-mod** [comment]
Reopening, problem's still here:
![Przechwycenie obrazu ekranu_2021-02-05_12-30-22](https://user-images.githubusercontent.com/32672779/107028637-bcd0d700-67a5-11eb-9855-2a5443b21b4f.png)

**Comment by rerrahkr** [comment]
I can't reproduce it on Windows 10.
In that image, the current order position is 03. Did you move there by scrolling the mouse or by playing the song?

**Comment by freq-mod** [comment]
> Did you move there by scrolling the mouse or by playing the song?

iirc by playing the song

**Comment by rerrahkr** [comment]
Can you try changing the height of the pattern editor to see if the same problem occurs? I want to know if that happens only at special heights.

**Comment by freq-mod** [comment]
Changing pattern editor size helps, but when order list jump to next order, the last one( that just appears) is blank,so I have to move pattern editor every time

**Comment by rerrahkr** [comment]
So the height doesn't matter, hmm...
From v0.4.5, I edited the order list only in a83a7ce7d10b02a39c0cb07d0f4a7c778fe64937, d1e02a843daf581cecccd97cf7243f47db19a5d6, and 1e4c118d101217aaa5bc475fd0084bcab95422ac. Other than that, I just modified includes and function names. Could you please check when such a problem will occur?

**Comment by freq-mod** [comment]
No, height does matter - if I change pattern editor size, order list is displayed fine. Sorry for misunderstanding.

Also, I spotted different thing - this bug is present only with certain Linux desktop environment, with other DE/window manager, there is no such glitch :thinking: 

Yeah, it's confusing.

**Comment by freq-mod** [comment]
In recent times, I can't replicate it any more, hopefully it's fixed for good this time.
