### ISSUE TITLE
[Feature] - Rhythm Instruments

### ISSUE THREAD

**Issue by Toonlink8101** [rerrahkr/BambooTracker#318]
> #### Checklist
> 
> 
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

This would allow instruments to be made for the rhythm channels. For some potential uses of this feature, please see the demo I have attached below. If panning sequences are introduced (#314), they would also benefit the rhythm instruments. Other sequences could include volume and retriggering; although, retriggering could be an effect instead. This retriggering effect is shown in the demo when multiple notes are strung closely together.

[Drum channel improvement.zip](https://github.com/rerrahkr/BambooTracker/files/5889400/Drum.channel.improvement.zip)

**Comment by rerrahkr** [comment]
Thanks for your request. To be honest, I don't think I'll implement it right now, as rhythm is not a priority for me. But your sample is interesting. Since rhythm has a fixed timbre, it seems to be more of an effector than an instrument.

**Comment by Toonlink8101** [comment]
Fixed via issue #249
