### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Numpad input is incomplete

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#320]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

The numpad seems to act weird. I can play some notes by pressing certain numpad numbers where the keyboard equivalent is mapped to a note (e.g. `2` on both the QWERTY part of the keyboard & the numpad -> C# being played), but it can't do anything else. It can't put those notes down and it can't be used for changing an instrument, the volume or effect settings.

## How to reproduce

1. Press 2 on the numpad to hear a C#
2. Enter edit mode
3. Try placing down a C# with numpad 2 -> C# gets played, nothing gets placed down in the pattern editor
4. Try to set the instrument to id 2 via the numpad -> C# gets played instead, nothing gets placed down in the pattern editor

## System Information

- **Operating System**: Linux NixOS 20.09 (Nightingale)
- **BambooTracker Version**: unstable-de3d7a7
- **Build Type**: Locally

**Comment by rerrahkr** [comment]
Thanks for your report. In key pressed events, BT checks that the input key has no modifiers such as Shift and Ctrl by testing <code><a href="https://doc.qt.io/qt-5/qt.html#KeyboardModifier-enum">Qt::KeyboardModifier</a></code>. Currently skipping if the pressed key has `Qt::KeypadModifier`, so I'll add new flag tests for it.

**Comment by rerrahkr** [comment]
Fixed in a83a7ce7d10b02a39c0cb07d0f4a7c778fe64937.
