### ISSUE TITLE
[Feature] - Expand instrument count limit to 256

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#322]
> #### Checklist
> 
> 
> 
> - [X] I'm requesting exactly 1 feature with this issue.
> - [X] This feature hasn't already been requested.
> - [X] This feature hasn't already been implemented in the latest development build.

Currently only 128 instruments can be loaded. That can be a problem when importing entire .wopn banks or .FF files like this:
[TOHO.FF.zip](https://github.com/rerrahkr/BambooTracker/files/5919085/TOHO.FF.zip)

If it was already requested but it is not possible, I am sorry.

**Comment by rerrahkr** [comment]
There is a problem that it requires a lot of memory, but I also question the use of 256 instruments in a module. BambooTracker's main purpose is to create songs, so I don't see the need to load a lot of unused instruments into the instrument list.

PMD FF can contain 256 instruments, but MML compiler links the instruments only needed to a MML, so not all FF files will be included in the song data. However, BambooTracker keeps all the instruments in the list in a module file, which unnecessarily increases the file size.

I think that it is better to use the bank files as a tone library if they are divided by instrument type, like the sample banks by Takeshi Abo. Even if you loaded all the instruments in the file, it would be rare to have to load 256 of them, and it will be easier to select the ideal(?) tone.
