### ISSUE TITLE
[Feature] - Implement a check that prevents loading samples that don't fit in ADPCM RAM

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#323]
> #### Checklist
> 
> 
> 
> - [X] I'm requesting exactly 1 feature with this issue.
> - [X] This feature hasn't already been requested.
> - [X] This feature hasn't already been implemented in the latest development build.

---
This feature will effectively fix a certain bug:
1. Load a sample bank containing more than 256 kB of ADPCM data, like [AOPPZ.PZI.zip](https://github.com/rerrahkr/BambooTracker/files/5920854/AOPPZ.PZI.zip)
2. Import every single sample that is in it
3. Play the sample that has "start" marker before sampleRAM limit, but "end" marker past it
4. It will loop through entire ADPCM RAM, creating a glitchy audio that play continously forever
5. Also, samples that have their "start" marker past ADPCM RAM bounds won't play at all (except short pop noise), so there is no reason to load them anyway.

**Comment by rerrahkr** [comment]
It is currently difficult to stop during importing, since the memory size required is known only when loading all ADPCM samples together after the instrument has been added to the instrument list.
I'll make an error dialog that tells the user to reduce samples if there is not enough memory.

**Comment by freq-mod** [comment]
I see. Then, error dialog was added, so closing.
