### ISSUE TITLE
[Windows|macOS|Linux|BSD] - PPS samples are imported with the wrong frequency/root key

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#330]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

## Bug Description
PPS samples are being imported with 2 times higher frequency than they should, it seems (16 kHz rather than 8), hence the root key should be one octave lower. Sample bank that shows this problem: [GAMES.PPS.zip](https://github.com/rerrahkr/BambooTracker/files/5975887/GAMES.PPS.zip)

**Comment by rerrahkr** [comment]
I checked [supposed PPS format](https://github.com/OPNA2608/libopenpmd/blob/master/docs/pps.txt) and find that there is no setting about the sample rate. Moreover comparing GAMES.PPS with [DRUMS.PPS](https://github.com/rerrahkr/BambooTracker/issues/313#issuecomment-765928015), they are set the same pitch in the files.
BambooTracker cannot detect them automatically, so after importing samples as ADPCM, configure them in the instrument editor.

**Comment by freq-mod** [comment]
Hmm, I see. So, if format doesn't specify sample rate, and Bamboo Tracker can't detect it as well, there is nothing I can demand from you.
