### ISSUE TITLE
[Feature] - YM2610B VGM export

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#335]
> #### Checklist
> 
> 
> 
> - [X] I'm requesting exactly 1 feature with this issue.
> - [X] This feature hasn't already been requested.
> - [X] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

Requested a lot on Discord server. Supposedly, 6-channel version of OPNB is very similar to the OPNA, to the point where register map is the same, the only difference is lack of the RSS in case of 2610B.

**Comment by ToughkidDev** [comment]
One more deferent thing - YM2610B supports 16 MB for the ADPCM-B channel, because of this, the sample address of the YM2610 is specified in steps of 256 bytes. As you know, YM2608 is specified in 32 bytes. 
That's All.
