### ISSUE TITLE
[Windows|macOS|Linux|BSD] - TFI/VGI operator order mixed up

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#339]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

I am 99% sure that 8e7879fd9dcc66a16135c639747dea7a7209ccb7 (and most likely 87dc56ffe4d4069cf8ee542576e28fc56ba04fe3 too) need to be reverted, see explanation in https://github.com/rerrahkr/BambooTracker/pull/290#issuecomment-782759442. The operator load order should be 1->3->2->4, otherwise the patches end up sounding different than they would in VGM Music Maker. Can anyone else verify this though testing with VGM Music Maker, BambooTracker v0.4.3 (before the "fixes") and BambooTracker v0.4.6 (after both "fixes").?

## How to reproduce

1. Import VGI file into BT
2. Instrument sounds wrong
3. Load VGI into VGM Music Maker
4. Compare sound & operator numbering between BT and VGM MM

## System Information

- **Operating System**: Linux NixOS 20.09 (Nightingale) x86_64
- **BambooTracker Version**: v0.4.6
- **Build Type**: package manager

**Comment by rerrahkr** [comment]
Thanks for your reports. I fixed them in 9112edf73bb0b1b25f505be76cdbe1e6f777a44b.
