### ISSUE TITLE
licenses / debian packaging

### ISSUE THREAD

**Issue by alexmyczko** [rerrahkr/BambooTracker#34]
Hello

It's great to have licenses/list.md

however qt is not in there as sources,  afaik, so it's just linking against it.

do you have parts of source codes of mame, vgmplay, silk icons? if so, where in the directory tree?

i need to specify them in debian/copyright, example:

https://sources.debian.org/src/protracker/2.3d.r147-1/debian/copyright/

**Comment by rerrahkr** [comment]
It is as @OPNA2608 said.
Should I also write about `emu2149. *` in the license list?

**Comment by alexmyczko** [comment]
no not necessary, it's already built on almost all: https://buildd.debian.org/status/package.php?p=bambootracker
