### ISSUE TITLE
[Windows|macOS|Linux|BSD] - ADPCM doesn't stop playing on note cut

### ISSUE THREAD

**Issue by Zexxerd** [rerrahkr/BambooTracker#340]
> #### Checklist

> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description
At the end of the Wilderness demo module, the ADPCM channel should stop playing. However, it doesn't. This appears to be because the program doesn't turn off the channel when it encounters a note cut when the current instrument playing has an empty release macro.

## How to reproduce
1. Create an ADPCM instrument that loops
2. Give it an envelope macro
3. Press a note to play it or play out a sequence that plays the instrument and then tries to turn it off with note cut. If the bug isn't fixed, it should keep playing.

## System Information

- **Operating System**: MacOS Mojave (Version 10.14.6)
- **BambooTracker Version**: v0.4.6
- **Build Type**: Official

**Comment by rerrahkr** [comment]
Thanks for your report. I fixed it in dc5e3178d1ee3f97b2179f673094bc1db39ed85d.

**Comment by Zexxerd** [comment]
I have **finally** gotten around to checking it, and it works. I'll close this now :P
