### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Arpeggio sequence is broken with FM3ch expanded mode

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#343]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

## How to reproduce

1. Create an FM instrument and set arpeggio sequence.
2. Set module type to FM3ch expanded
3. Place a note on channel 3, it can be all or some of the operators
4. Arpeggio sequence will be ignored; but only on channel 3. Rest of the channels aren't affected by this bug, arp sequences work fine on chans 1,2, 4...6.

## System Information

- **Operating System**: Arch Linux x64
- **BambooTracker Version**: newest master

**Comment by rerrahkr** [comment]
That's intended behavior. If you want to use arpeggio or pitch sequence in FM 3ch, you need to set the "Operator" in those editor correctly. To set the sequence behavior in FM 3ch applied extended mode, you need to enable Op1-4 sequence.
The reason "All" does not work for 3ch is to eliminate ambiguity in execution selection when different operator sequences are set at the same time.

**Comment by freq-mod** [comment]
I don't know if I understood you correctly, but even after setting FM3ch "Operator" checkboxes in instrument editor, it still ignores arpeggio sequence.
[arpfm3.zip](https://github.com/rerrahkr/BambooTracker/files/6142438/arpfm3.zip)

**Comment by freq-mod** [comment]
Ah, neverming, I have figured that out. Thanks for explanation!
