### ISSUE TITLE
using null output device, none available

### ISSUE THREAD

**Issue by alexmyczko** [rerrahkr/BambooTracker#35]
On Ubuntu 18.10 Linux I can build and start BambooTracker, when I load a .btm file I can't play it message in subject appears.

**Comment by OPNA2608** [comment]
Do you have all dependencies installed? This happened to me when I didn't have the `libqt5multimedia5-plugins` package installed, which is needed so Qt can interface to your system's audio driver - ALSA, JACK etc.
