### ISSUE TITLE
[Feature] - Add audio preview when importing instruments from a bank

### ISSUE THREAD

**Issue by Drillimation** [rerrahkr/BambooTracker#355]
> #### Checklist
> 
> 
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

I feature I highly recommend is to add a sound preview whenever the user is importing instruments from a bank file (.FF would be an example of what I'm talking about). Whenever a group of instruments is being imported, there should be a preview button to let the user know what a selected instrument they're importing sounds like (a C-4 note should be played).

**Comment by freq-mod** [comment]
it's already here lmao

**Comment by OPNA2608** [comment]
Import preview is already implemented like @freq-mod mentioned. Try pressing any of your note-putting keys after selecting an instrument in the dialogue. Adding a separate, additional button with a fixed note for this seems redundant.
