### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Incorrect FMP and PMD instrument data import parsing

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#358]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

I have tried to import an instrument from FMP or PMD song, and I spotted resulting instrument in BT differs from what's in MML code.

'@  0
'@ 31,  0,  0,  0,  0,  23, 0,  4, 7
'@  8, 10,  4, 10,  1,   2, 0,  4, 3
'@  8, 10,  4, 10,  1,   0, 0,  8, 7
'@  8, 10,  4, 10,  1,   0, 0,  2, 3
'@ 6, 7 gets imported as  [Instrument 0.bti.zip](https://github.com/rerrahkr/BambooTracker/files/6369239/Instrument.0.bti.zip)
Please note AR3 - in imported instruments its value is 31, when it should be 8.

- **BambooTracker Version**fresh master
- **Build Type**: built locally

**Comment by rerrahkr** [comment]
Thanks for your report. I fixed it at 780241d0be45e2f12751ca0a95dbe39f2d15a2d9.

**Comment by freq-mod** [comment]
Now it works correctly, thanks!
