### ISSUE TITLE
[Windows] - Create/Rename/Delete Instrument Crash

### ISSUE THREAD

**Issue by RaijinXBlade** [rerrahkr/BambooTracker#361]
> #### Checklist
> 
> 
> 
> - [ ] I am reporting exactly 1 bug with this issue.
> - [ ] This bug hasn't already been reported.
> - [ ] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

Simply create a new instrument, click to rename it, then immediately click to delete it, and it will crash the tracker.

## How to reproduce

1. Create new instrument.
2. Click rename instrument.
3. Immediately click remove instrument.

## System Information

- **Operating System**: Win10 x64 20h2
- **BambooTracker Version**: 0.4.6
- **Build Type**: Official

**Comment by freq-mod** [comment]
duplicate of #360

**Comment by RaijinXBlade** [comment]
Oh. That's the person that told me to make a report. Oh well, I'll close this.
