### ISSUE TITLE
Audio output does not redirect to earphones when connected via bluetooth

### ISSUE THREAD

**Issue by Zexxerd** [rerrahkr/BambooTracker#364]
> #### Checklist
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [?] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

I don't know if it's supposed to do this, but when I connect my earphones to my computer, the audio keeps playing out of the computer when I play the song. I see the option in the preferences menu to change it to "ffff: (earphone device)", but when I do that, it gives me the following error:
`Could not open the audio stream. Please change the sound settings in Configuration.`
`RtApiCore::probeDeviceOpen: system error (kAudioHardwareIllegalOperationError) setting sample rate for device (1).`
## How to reproduce

1. Connect bluetooth earphones while using BambooTracker
2. Play the current song.
3. Try changing the audio output device to the earphones in Preferences

## System Information

- **Operating System**: MacOS Mojave (Version 10.14.6)
- **BambooTracker Version**: v0.4.6
- **Build Type**: Official

**Comment by OPNA2608** [comment]
There is no support for automatically switching output devices. I don't think the audio output library we use has support for automatically detecting newly added devices and issuing our code a notification or callback to act upon it. You will have to manually change the device. There is also no built-in way to detect when your device of choice gets disconnected so be wary of that.

Regarding your error, have you tried the different sample rate options? The error indicates that your headset does not support whatever sample rate you had configured.

The response for an unsupported sample rate is OS & audio API specific:
- Some refuse to connect and give an error
- Some accept seemingly any sample rate and may do up-/downsampling internally
- Some accept the connection but replace your requested sample rate with their own one.

CoreAudio (which is what macOS uses) seems to be in the first group by the looks of it. Try 48000Hz or 44100Hz.

**Comment by Zexxerd** [comment]
I tried changing the sample rate to 48000Hz and it works, but now I can't change my computer's volume to change the volume of the output (i.e. there are only 2 volume states, on and off). I have to change the master volume in Preferences to do so.

**Comment by Zexxerd** [comment]
Never mind, I rebooted BambooTracker and changing the computer volume works as expected. I'll consider this issue closed.
