### ISSUE TITLE
[Feature] - Load more than one instrument file

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#366]
> #### Checklist
> 
> 
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

I'm currently trying to sort & organise hundreds of TFI files via BambooTracker. While doing so I noticed that `Load From File…` can only load one file at a time, making this whole process a *pain*.

I think it would be very helpful if one could select & load multiple TFI instrument files at once.

**Comment by rerrahkr** [comment]
Thanks for your request. I modified instrument loading in e151734ff0ecd52c756ab44bee430c563e1d4c8f.

**Comment by OPNA2608** [comment]
Thanks!
