### ISSUE TITLE
[Feature] - Offer wildcard and "all supported formats" extensions in file dialogues

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#367]
> #### Checklist
> 
> 
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

Many applications that offer loading & saving via file dialogues let you use an "All supported formats" and a wildcard (`*`) option as the extension filter. The former would filter for every extension that the application supports (e.g. `*.bti`, `*.dmp`, `*.tfi` etc for `Load From File…`) and the latter would essentially do no file filtering at all. The wildcard can be very useful when you're dealing with alot of files without proper extensions.

I think both of those options would be very helpful additions to most dialogues.

**Comment by rerrahkr** [comment]
Thanks for your request. I added these filters to file dialogues in e7c28a3a5f6a5607672e99aef1dd8f7cfd7540da.

**Comment by OPNA2608** [comment]
Thanks!
