### ISSUE TITLE
YM2608 implementation in Bamboo is one octave too high in pitch

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#40]
Let's compare Deflemask's YM2612 and Bamboo Tracker outputs:
Bamboo: https://instaud.io/359e (F#3, effect 02xx)
Deflemask: https://instaud.io/359f (the same)

As you can hear, OPN2 core in Deflemask goes much lower than Bamboo's OPNA, while they should sound pretty much the same. It seems that in Bamboo Ym2608 is one octave higher than it should be (C-0 is C-1, C-1 is C-2 and so on). Therefore there is no lowest octave. Some drums such as kicks or snares from PC-98 games are impossible to replicate here.

**Comment by rerrahkr** [comment]
Since I set FM octave to match SSG octave, it needs to lower FM octave.

I think to revise module format to v1.0.2 when changing the octave. Before module v1.0.2, compatibility will be maintained by preprocessing octave adjustment at loading.

**Comment by rerrahkr** [comment]
I fixed in 526e46e59dfe7b3730c3470521bc90bf1a256668.
