### ISSUE TITLE
Unable to build in Ubuntu 18.10

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#46]
Yet another compilation problem - this time something is **very** wrong with SCCI, as it produces a lenghthy list of errors in scci.h:
https://gist.github.com/papiezak/5df54cea1d5d66ff480b641b2e875bd0 

Ubuntu 18.10, all dependencies installed. There were no build problems before cf99e95

**Comment by rerrahkr** [comment]
As `__stdcall` is used only on windows, I need to add a define in scci.h:
```c++
#ifndef WIN32
#define __stdcall
#endif
```

**Comment by papiezak** [comment]
fixed in #47
