### ISSUE TITLE
Stuttery drawing of Pattern Editor

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#49]
I'm experiencing a noticable stuttering of the Pattern Editor when playing a song in Follow Mode with any Buffer length >3ms.

[Here is a .WEBM showcasing this problem.](https://cdn.discordapp.com/attachments/410831172181164044/529843973343150100/PatternEditorStutter.webm)

(This is on Linux, NixOS 18.09, running the freshly compiled release v0.1.4)

**Comment by rerrahkr** [comment]
Thanks for your report.
Due to the simultaneous updating of sound buffers and the pattern editor, it may occur.
I think that it is possible to avoid it by dividing these processes.

**Comment by alexmyczko** [comment]
I can see the same here (debian or ubuntu)

**Comment by rerrahkr** [comment]
It doens not happen on my Windows 10.
Is the sound correctly playing even at 3ms?

**Comment by OPNA2608** [comment]
[Actual playback](https://github.com/rerrahkr/BambooTracker/files/2730516/recordings.tar.gz) is fine from what I can hear, with only minimal differences between 1ms and 500ms.

**Comment by OPNA2608** [comment]
I think this issue has improved alot with the merging of #152. Though still noticeable at higher buffer lengths, I consider it closed for now (yet possibly still improvable!) as the main symptom (<3ms being required for usage) has been fixed. :slightly_smiling_face:
