### ISSUE TITLE
Add png icon to use with .desktop file

### ISSUE THREAD

**Issue by ehaupt** [rerrahkr/BambooTracker#51]
Would it be possible to include [this](https://github.com/rerrahkr/BambooTracker/issues/27) file as BambooTracker.png in the icon directory?

I've created a [FreeBSD port](https://svnweb.freebsd.org/ports/head/audio/bambootracker/) that is currently fetching the file separately to use with the .desktop file.

**Comment by rerrahkr** [comment]
Thanks for your request.
I added icon pngs in f4514328335fb8ece7a482c8a818b7f348d05caf.

**Comment by ehaupt** [comment]
Thank you very much. That simplifies the porting effort.
