### ISSUE TITLE
Sample songs

### ISSUE THREAD

**Issue by ehaupt** [rerrahkr/BambooTracker#53]
Are there any sample songs available? I've only found:

http://cherry.dhcp.phys.ethz.ch/majfant2quieter.btm

**Comment by rerrahkr** [comment]
It is not for now. Is it better to recruit sample songs?

**Comment by ehaupt** [comment]
It was more out of personal interest to test various functions. It might be helpful for new users to have a set of sample files available. But it's no big priority. Just a thought.

**Comment by rerrahkr** [comment]
I added 2 demo modules at a8d69432ef0924a80083f9cad8de5e720c35ce61. And I will continue recruiting demos.
