### ISSUE TITLE
[bug] octave up/down keys don't work

### ISSUE THREAD

**Issue by galap-1** [rerrahkr/BambooTracker#55]
I don't know if this is a bug or just things not being implemented yet, but 

only main board / works. Number row * (Shift+8) does not, and neither does numpad / or numpad *.

**Comment by rerrahkr** [comment]
Thanks for your report, I will check it.
As a solution, you can assign any key in the configuration.

**Comment by rerrahkr** [comment]
I changed default octave up/down keys to numpad * and numpad / in 7cf7165d9b3a78fbdee8074d5b695b559614177a.
