### ISSUE TITLE
[Request] Instrument Editor - Paste from plain text instrument format

### ISSUE THREAD

**Issue by pedipanol** [rerrahkr/BambooTracker#57]
Considering there's a lot of plain text instrument formats, like OPM, FMDrive and MML formats, I think it would be nice to have a way to support them and I think pasting from clipboard would be the easiest one. So I was thinking of a thing like Right Click -> Paste From... -> (List of formats)

OPM and MML formats such as PMD, FMP and MUCOM88 would probably be the easiest to implement since the FM instrument settings are in a similar order despite there being differences between them.

So here are some examples of the same instrument in different formats:

**BambooTracker** clipboard instrument definition (spacing added for definition):
```
            FB ALG
FM_ENVELOPE: 0,  5,
AR DR SR RR SL TL KS ML DT SSGEG
31,22,12, 6, 6, 0, 1, 0, 1,-1,
31,17,12, 9, 6, 4, 1, 6, 5,-1,
31, 8, 2, 9, 5, 4, 1, 0, 7,-1,
31,31, 5,12, 0, 0, 1, 0, 3,-1,
```
**VOPM**
```
@:0 CH1
//  LFRQ AMD PMD WF NFRQ
LFO: 199  64  64  2    0
// PAN FL CON AMS PMS SLOT NE
CH: 64  0   5   0   0  127  0
//  AR D1R D2R RR D1L  TL KS MUL DT1 DT2 AMS-EN
M1: 31  22  12  6   6   0  1   0   1   0      1
C1: 31  17  12  9   6   4  1   6   5   0      1
M2: 31   8   2  9   5   4  1   0   7   0      1
C2: 31  31   5 12   0   0  1   0   3   0      1
```
**PMD**
```
;   ALG FB
@ 0   5  0
; AR DR SR RR SL  TL KS ML DT AMON
  31 22 12  6  6   0  1  0  1    1
  31 17 12  9  6   4  1  6  5    1
  31  8  2  9  5   4  1  0  7    1
  31 31  5 12  0   0  1  0  3    1
```
**FMP**
```
'@ 0 A
   AR DR SR RR SL  TL KS ML DT AMON
'@ 31,22,12, 6, 6,  0, 1, 0, 1, 1
'@ 31,17,12, 9, 6,  4, 1, 6, 5, 1
'@ 31, 8, 2, 9, 5,  4, 1, 0, 7, 1
'@ 31,31, 5,12, 0,  0, 1, 0, 3, 1
  AL FB
'@ 5, 0
```
**MUCOM88**
```
  @ 0:{
; FB  AL
   0,  5
;  AR  DR  SR  RR SL TL KS ML DT
  31, 22, 12,  6, 6, 0, 1, 0, 1
  31, 17, 12,  9, 6, 4, 1, 6, 5
  31,  8,  2,  9, 5, 4, 1, 0, 7
  31, 31,  5, 12, 0, 0, 1, 0, 3,"??????"}
```

The common thing is that only BambooTracker supports SSGEG on the instrument definition, but it doesn't support AMON/AMS-EN, in OPM/PMD/FMP it should put a "-1" instead of the AMON definition. Since MUCOM88 doesn't use this as well, it should just add a -1 after the end of each line.

**Comment by Decidetto** [comment]
I think this would be a very valuable feature. Most of my instrument patches are in OPM and PMD-MML formats and it would allow for a very painless switch to BambooTracker! I imagine lots of other people are in a similar situation.

**Comment by rerrahkr** [comment]
I added plain text paste from FMP, FMP7, MMLDRV, MUCOM88, MXDRV, NRTDRV(only VOICE_MODE=0), PMD and VOPM for next release.
Since this function only read digits from the text in the order of appearance, it is necessary to remove unused digits contained in a tone name, comments, etc.
