### ISSUE TITLE
Cannot open .BTM after reopening BambooTracker

### ISSUE THREAD

**Issue by djtuBIG-MaliceX** [rerrahkr/BambooTracker#59]
Hi,

Was working on something for a couple hours. Not sure what happened but all of a sudden I am no longer able to reopen my .BTM file as it appears with an error:
![image](https://user-images.githubusercontent.com/3403183/51801701-834f6200-2295-11e9-9562-b566c347fbca.png)

I have attached the relevant .BTM file in the following zip.
[djtBMX_BTM_bug.zip](https://github.com/rerrahkr/BambooTracker/files/2800086/djtBMX_BTM_bug.zip)

Not sure what could suddenly cause this but I suspect it might have something to do with deleting and adding instruments?

Thanks,
-MaliceX

**Comment by djtuBIG-MaliceX** [comment]
I may have yes. Though I just add another instrument afterwards which then fills the index gap.
It certainly sounds repeatable if the instrument list is suddenly mapping to a default value 0xFF presuming it's a default constant.  Happy to investigate a repeatable test case.

Also thanks for fixing the .BTM

**Comment by rerrahkr** [comment]
Although I didn't know why it happens, in 758c350bbf8f9b36db49e1caa8f9cef547bc0108, I removed code which set a instrument number to -1 (0xFF). -1 was a flag as "this instrument is not registered with instrument list". I divided the flag and the instrument number, so I think it would not occur to set wrong instrument number.
