### ISSUE TITLE
Effect 0Bxx doesn't work when exporting to S98

### ISSUE THREAD

**Issue by scarletbullgon** [rerrahkr/BambooTracker#60]
Basically, the effect used to jump into an order doesn't seem to function properly when the module is exported to S98. It works fine when exported to VGM, however.

I'll be attaching the .btm module here, along with the .s98 and .vgm exports:
[Bambootracker 0Bxx Bug Modules.zip](https://github.com/rerrahkr/BambooTracker/files/2837902/Bambootracker.0Bxx.Bug.Modules.zip)

**Comment by rerrahkr** [comment]
Thanks for your report.
I fix it at 09b28d35e9a08e79099a2c0d3106e13e29220118.
I also fix VGM export bug that was cut long key on accidentally at 01f35d77f99b145be21991e69c3cce1fd4239eb5.
