### ISSUE TITLE
Mixer settings not saved properly.

### ISSUE THREAD

**Issue by ImATrackMan** [rerrahkr/BambooTracker#66]
When changing mixing settings, they're not saved properly. SSG always resets to 0dB when reopening the tracker. FM resets itself to +9 for values above +9, +6 for values between +3 and +6, and 0dB for values below +3dB.

**Comment by OPNA2608** [comment]
Working on it.

For SSG volume not saving properly, an oversight while copy-pasting the new Mixer settings has to be blamed.
https://github.com/rerrahkr/BambooTracker/blob/b315fb027f3c8c3fb5f3c609f8f35c070b70858a/BambooTracker/gui/configuration_handler.cpp#L170-L171

**Comment by rerrahkr** [comment]
I merged #67. Thanks @ImATrackMan for report and @OPNA2608 for fixing!
