### ISSUE TITLE
Using non-channel-type instrument crashes tracker.

### ISSUE THREAD

**Issue by ImATrackMan** [rerrahkr/BambooTracker#69]
When editing either SSG or FM, using the instrument in a channel of a different type (for example, typing a note in SSG with an FM instrument selected by accident) crashes the tracker immediately.

**Comment by rerrahkr** [comment]
Thanks for report.
Since working on at b315fb027f3c8c3fb5f3c609f8f35c070b70858a, it will be fixed in the next release.
