### ISSUE TITLE
Permit piano keyboard keys to be rebindable

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#70]
The keybinds for adding notes, as the README mentions, are:
> There are two rows of a piano keyboard:
> ```
> Current octave+1
>  2 3  5 6 7  9
> Q W ER T Y UI O
> 
> Current octave
>  S D  G H J  L
> Z X CV B N M, .
> ```

This works fine on a QWERTY keyboard.

Using a non-QWERTY however, like the [German QWERTZ](https://en.wikipedia.org/wiki/QWERTZ), [French AZERTY](https://en.wikipedia.org/wiki/AZERTY) or, well, the [Russian JCUKEN using Cyrillic script](https://en.wikipedia.org/wiki/JCUKEN) can either take some getting used to or might just not work at all. (I can only speak for myself, using a QWERTZ keyboard.)

I propose that, at least, these keys should be rebindable. They can stay the default, I highly doubt that the majority of users will be using a non-QWERTY layout, but the user should be able to change the mapping and save it how they see fit. The groupbox for changing the keys to change the current octave etc. could be moved into the same settings window tab as well.

Perhaps offering some presets for different layouts as well would be the icing on the cake.

**Comment by rerrahkr** [comment]
Thanks for your request. I will try to add keyboard presets since it is easier to implement.

**Comment by rerrahkr** [comment]
I offered QWERTY, QWERTZ and AZERTY layouts at 616612cb42b80194ef4c041c84e80199f0bded17.

**Comment by rerrahkr** [comment]
I fixed not changing layout when entering notes at 3e62c6507583d877778b1c36bcbe0baf954c47d6.
