### ISSUE TITLE
Option "Show row numbers in hex" broken

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#71]
> Display order numbers and the order count on the status bar in hexadecimal.

Unsetting the "Show row number in hex" option only affects the _currently selected order_ in the _order list._

It doesn't affect
- the status bar display
- the numbering of all orders in the order list that aren't the currently selected order

A screenshot (working on German i18n, but the bug's replicable without it)
![grafik](https://user-images.githubusercontent.com/23431373/53641141-598bb100-3c2e-11e9-8448-1a5039ebeb6c.png)

System:
- Ubuntu 18.04.2 LTS x86_64
- Commit https://github.com/rerrahkr/BambooTracker/commit/4be0b10df509762ed068939de25c9d4a61df8e81 (behind the Appveyor commit, but I doubt it had any effect either)

**Comment by rerrahkr** [comment]
Thanks for report. I have just fixed it at 7f11f64.
