### ISSUE TITLE
FM envelopes not set properly when loading an .ins instrument file.

### ISSUE THREAD

**Issue by scarletbullgon** [rerrahkr/BambooTracker#73]
This is a bit hard to explain, but to put it shortly, some envelopes values are set in the wrong order when a new instrument is loaded as an .ins file, which often results on really bizarre sounds.

![envelope](https://user-images.githubusercontent.com/47397401/53755410-3b73ba00-3e95-11e9-9acd-7e0e562a989b.PNG)
This screenshot shows the envelopes of a bass drum instrument. One window shows the incorrect settings, and the other showing how it should be. To "fix" this problem, I had to load the mentioned instrument through DefleMask, save it as a .dmp file, and then load said file to BambooTracker in order to get the correct settings.

I'm not sure if this problem is also present when other instrument file types are loaded, but yeah.

Here's another attachment, it has a .btm file to show the sound of both the incorrect and correct bass drums. It also has the bass drum instrument, as both .ins and .dmp files:
[BambooTracker FMEnvelopeBug.zip](https://github.com/rerrahkr/BambooTracker/files/2927829/BambooTracker.FMEnvelopeBug.zip)

**Comment by rerrahkr** [comment]
Thanks for your report. Since I mistook the order of reading DR and SR, I fix it at 1c3ae72269624e704924f8c3897c0e1c5c0ab04e.
