### ISSUE TITLE
Dependencies and Compile Instructions

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#8]
I'd like to compile this on my own, to see how well compiling on Linux goes.

Could we possibly get a list of required libraries/programs and compile instructions?

**Comment by OPNA2608** [comment]
I think I have it figured out actually. This works for me on Ubuntu 18.04:

### Dependencies
> make
> Qt5 (including qmake)
> Qt5 Multimedia
> Qt5 Multimedia plugins
>
on Ubuntu 18.04:
```sh
sudo apt-get install \
  build-essential \
  qt5-default qtmultimedia5-dev libqt5multimedia5-plugins
```

### Compilation
```sh
cd BambooTracker
qmake
make
```

I haven't played around with it much so far, but it seems to at least compile and start fine on my work PC. It would be nice if you could add them to the readme too :)

**Comment by rerrahkr** [comment]
Thanks for your information!
I will add them to readme.
