### ISSUE TITLE
Crash to desktop when toggling tracks on/off using mouse

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#81]
1. Open a song (it can be any demo song)
2. Double click on some FM channel to solo it
3. Click on FM1 channel
4. It hangs for a while and crashes silently to desktop

**Comment by OPNA2608** [comment]
Can't replicate, v0.1.6 on Linux (NixOS 18.09).
![BT_CrashToDesktop](https://user-images.githubusercontent.com/23431373/54491022-50037980-48bb-11e9-8081-987957fcf42e.gif)

**Comment by papiezak** [comment]
Weird. I'm running Windows 10 Enterprise LTSC
![bug](https://user-images.githubusercontent.com/32672779/54491274-6dd1de00-48bd-11e9-8ae9-233454e3f16d.gif)

**Comment by rerrahkr** [comment]
I had a mistake about static_cast at 73944502f26cf59b300101ea79f3d119a44c8d5a, so I fixed at 629e4fb2d560150bcb45acfb9a9a5870a832d353.

**Comment by papiezak** [comment]
Thanks for the quick fix!
