### ISSUE TITLE
Initial Window Size Too Large

### ISSUE THREAD

**Issue by KamuiKazuma** [rerrahkr/BambooTracker#82]
Upon first starting BambooTracker v0.1.6 the window extends past the top and bottom of the screen on displays with a vertical resolution of 768px or less (some laptops). The issue is easily fixed, and doesn't crop up when restarting the tracker. This is a minor thing, but fixing it would make it easier for users to start immediately.

**Comment by rerrahkr** [comment]
Thanks for your request.
I will change window size to 900x700 at next release.
