### ISSUE TITLE
Incorrect audio output for FM channel 3

### ISSUE THREAD

**Issue by jimbo1qaz** [rerrahkr/BambooTracker#84]
Regression caused by 804b7cd8eec605d373fbe3095a8d0af95672f7e2 .

This commit seems to change and break the sound output of existing .btm file [sd3winter-dev.zip](https://github.com/rerrahkr/BambooTracker/files/3001669/sd3winter-dev.zip). (Is there some oddity with my instrument 5 that causes this issue?)

**Comment by OPNA2608** [comment]
Can confirm.

Top is https://github.com/rerrahkr/BambooTracker/commit/e887448a10a37732ec218b529f6b84b63d9266a4, bottom is current master https://github.com/rerrahkr/BambooTracker/commit/4c8a535c07d5aa36a87709cba91afd489ab13468.
![grafik](https://user-images.githubusercontent.com/23431373/54901647-6a4ee000-4ed7-11e9-8dbf-51e0c57917e0.png)

**Comment by rerrahkr** [comment]
Thanks for reports. I mistook register offset in setting pitch data, so I fixed it at 2eaa2f8e966c62d34c560e6eb5b3d1ea6cd48801.

**Comment by jimbo1qaz** [comment]
Seems to be fixed in master. Thanks, I wasn't sure if it was a bug or an issue with my module.
