### ISSUE TITLE
Crash when changing pattern size during playback

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#86]
I know it's obvious why this crash happens, but anyway:
1. Create an instrument
2. Lay a note
3. Play a "song"
4. Now, double click on "pattern size" and change default value (64) to something like single-digit.
It may not work on the 1st try, but on 2nd, 3rd or so it's guaranteed to crash to desktop.
Proof: 
![bug](https://user-images.githubusercontent.com/32672779/54936791-7f516080-4f23-11e9-8e2c-71a17f97fbf7.gif)

**Comment by rerrahkr** [comment]
Thanks for your report, I fixed it at 6ba887e20ebd54cd5d40a424354911f2bce8e8a1. In this commit, I also changed spinbox behavior to emit value change event when finishing text editing.

**Comment by papiezak** [comment]
Thanks for the fix!
