### ISSUE TITLE
SIGSEGV with buggy FM envelope input editor, value mapping display misalignment

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#87]
I've noticed two bugs within the Configuration->Input tab:

---

#### 1) Name -> Specification association
While renaming a new or any of the existing FM envelope format specifications, if the currently entered name is equal to an existing specification's name, the currently edited specification as well as the one it shared its name with for any amount of time will be associated with each other: They share the same editable list of text -> FM operator mappings and deleting one of them will also delete the other.

Example: I want to add an alternate specification of the PMD format [as described here](https://pigu-a.github.io/pmddocs/pmdmml.htm#3-1) and call it PMD-DT2. (because it adds a secondary Detune value to each operator specification)

1) Have a FM envelope text specification called "PMD".
2) Create a new FM envelope text specification.
3) Edit the name from "Set …" to "PMD-DT2".

While typing, as soon as the textbox contains the string "PMD", PMD-DT2 will be linked to PMD.

- If you try to edit PMD-DT2, it'll have the same content as PMD. A SIGSEGV is achievable here by changing a value, then pressing OK and selecting PMD. (valgrind trace below)
- If you save, PMD-DT2 will replace PMD.
- If you delete PMD-DT2, PMD will be deleted as well. (and vice versa)

[Here is the valgrind log. It has alot of noise at the start, the SIGSEGV happens at line 1064.](https://github.com/rerrahkr/BambooTracker/files/3008358/BambooTracker.log)

#### 2) Bugged mapping display
When adding a value while value number 0 or no value (when pressing Edit followed by Add without highlighting any existing value) is selected, the values will be misaligned. This is only a temporary visual bug, as closing the window and pressing Edit again will fix this.

![grafik](https://user-images.githubusercontent.com/23431373/55000847-ad8e7900-4fd3-11e9-901d-a330fd8b3557.png)

**Comment by rerrahkr** [comment]
Thanks for reports. I will fix them.

**Comment by rerrahkr** [comment]
I fix to allow the same name envelope sets at f9018c8c68e020b67974429e91492f3671674d76, and value type alignment at 4b6e56b7f50e4e0274db2b4e27c36975574a8038.

**Comment by OPNA2608** [comment]
I can confirm that same name envelope sets work fine now, however the value type alignment, with enough additions, still bugs out.
![grafik](https://user-images.githubusercontent.com/23431373/55612673-06ef6880-5789-11e9-8c30-272ec06cc8d6.png)
