### ISSUE TITLE
Provide versioned specification documents

### ISSUE THREAD

**Issue by jpcima** [rerrahkr/BambooTracker#91]
Hello. Do you mind archiving different finalized versions of file specifications as distinct documents?
This will be easier, and less confusing, than examining a commit history.

There was a request for BambooTracker instrument importing, and I would like to add the support, for old files as well as current and future. https://github.com/Wohlstand/OPN2BankEditor/issues/71

**Comment by rerrahkr** [comment]
Thanks for your request. I will try to make a new directory `specs` and archive old and current specifications.

**Comment by rerrahkr** [comment]
I added at bb98a73a59a34310882794d7b94d5025da5bd81b.

**Comment by jpcima** [comment]
It's very nice, thank you.
