### ISSUE TITLE
Improve SSG-EG emulation

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#93]
Kinda similar to #77 - it may be not the OPNA emulation problem, but anyway...
SSG-EG sounds weird - totally different than on YM2612 trackers/utilities, which is weird, since YM2612 is based directly on YM2608's FM block and there should be no difference in SSG-EG timbre...

https://instaud.io/3vIA - SSG-EG instrument recorded using BambooTracker
https://instaud.io/3vIC - the same instrument, recorded using OPN2 Bank Editor, with "Nuked OPN2" emulator, one of the most accurate soundchip emulators ever

The difference between two recordings are huge - 2608's SSG-EG sounds **very** weak compared to 2612. 
[ssgeg.zip](https://github.com/rerrahkr/BambooTracker/files/3045354/ssgeg.zip) - zip file with instrument and emu recordings in question

**Comment by rerrahkr** [comment]
Thanks for your report. I checked the instrument on real chip (BambooTracker -> SCCI -> c86ctl ->G.I.M.I.C).
[real.zip](https://github.com/rerrahkr/BambooTracker/files/3048122/real.zip)
This sound is similar to Nuked OPN2, so it seems that MAME emulation is wrong.

**Comment by papiezak** [comment]
Well, that interesting.
I recall @jpcima tried to correct SSG-EG emulation on Neko Project 2 OPNA emulation core using Nuked OPN2 code, the result was a bizarre cross between two 😆  Maybe with some tweaks, MAME can be improved.
Thanks for checking on a real chip anyway.

**Comment by jpcima** [comment]
>This sound is similar to Nuked OPN2, so it seems that MAME emulation is wrong.

Interesting, then it means Nuke.YKT had the correct intuition on this.

First thing, I'll be interested to compare MAME's independent YM2612 core, vs MAME generic FM code (which generates various YM* chips, one being YM2608). In our experience, these two are generating the SSG-EG differently.

Also it could be examined how much work it takes to bolt some features onto Nuked-OPN2, to make it into a semi-accurate OPNA-ish that Bamboo Tracker can use.

>I recall @jpcima tried to correct SSG-EG emulation on Neko Project 2 OPNA emulation core using Nuked OPN2 code, the result was a bizarre cross between two

It's not a really accurate statement, the SSG-EG work introduced was not Nuked's but mine.
I just had the EG curve match, in approximation, what Nuked EG would output.
In reality, it has nowhere the actual cycle-accuracy like Nuked has.

**Comment by papiezak** [comment]
>It's not a really accurate statement, the SSG-EG work introduced was not Nuked's but mine.
I just had the EG curve match, in approximation, what Nuked EG would output.
In reality, it has nowhere the actual cycle-accuracy like Nuked has.

You're right, I misunderstood what you have done. Sorry about that.

>Also it could be examined how much work it takes to bolt some features onto Nuked-OPN2, to make it into a semi-accurate OPNA-ish that Bamboo Tracker can use.

Well, OPN2 differs slightly from OPNA - DAC works differently, even on ASIC there is a liitle distortion I think, also YM2612 clips waveforms if they're too loud - (Wohlstand/libOPNMIDI#73) while YM2608 doesn't. One would have to compose an entire rhythm rom and accurate (AD)PCM and PSG emulation into Nuked.

**Comment by jpcima** [comment]
Ok I'll try to plug in a Nuked emulator for testing. It can't be too difficult to make this I think, we'll see.
The SSG code is already externalized from MAME anyway and is good for reuse.

**Comment by jpcima** [comment]
I just pushed a branch `nuked` at my repository. See https://github.com/jpcima/BambooTracker/tree/nuked
It supports just the OPN2 subset at present time.

SSG-EG can be checked outright on the demo song "Underwater Ruins" on the first instrument.
The timbre difference will be immediately heard.

**Comment by papiezak** [comment]
Nuked OPNA is somewhat done, yet:
> I'll be interested to compare MAME's independent YM2612 core, vs MAME generic FM code (which generates various YM* chips, one being YM2608). In our experience, these two are generating the SSG-EG differently.

So do you plan on upgrading MAME `fm.c` emulator with data from MAME OPN2 core? If yes, I will leave this issue open?

**Comment by papiezak** [comment]
Nuked OPNA is somewhat done, yet:
> I'll be interested to compare MAME's independent YM2612 core, vs MAME generic FM code (which generates various YM* chips, one being YM2608). In our experience, these two are generating the SSG-EG differently.

So do you plan on upgrading MAME `fm.c` emulator with data from MAME OPN2 core? If yes, I will leave this issue open?

**Comment by jpcima** [comment]
I'll report the bug details to MAME developers for them to fix.
Probably the same as decade old issue: https://mametesters.org/view.php?id=1066

**Comment by jpcima** [comment]
Experiment: this branch [mame-ssgeg](https://github.com/jpcima/BambooTracker/tree/mame-ssgeg) is a quick copy&paste of MAME YM2612 envelope generator including improvement by Nemesis.
It appeared to fix the EG behavior. The timbre would still need work, but it's a great step.

**Comment by papiezak** [comment]
Took a quick look at it now - the timbre is slightly off, even when compared to MAME 2612, but it's not that noticeable any more. At first I thought it had something to do with AR (as I was convinced that BambooTracker forces AR=31 when SSG-EG flag is on) but it's not like it.

Aside from that, it kinda fixes the issue, thanks!

**Comment by freq-mod** [comment]
As FM core in MAME is getting rewritten, envelope generator will likely be fixed. And Nuked OPN-Mod does it's job anyway, so closing.
