### ISSUE TITLE
YM2203 and YM2419 vgm/s98 export

### ISSUE THREAD

**Issue by pedipanol** [rerrahkr/BambooTracker#98]
I'm aware the purpose of the tracker is to solely to emulate the OPNA soundchip. But I think it would be nice to have the ability to export vgm/s98 files in this format.

From what I heard the register writes are basically the same throughout these soundchips, since the OPNA is a derivative of YM2203 and the SSG is a variant of the YM2419, so I imagine it wouldn't be difficult.

I know djtuBIG-MaliceX made a SSG to AY converter, and I believe this is the source code but I don't know if it would be useful https://github.com/djtuBIG-MaliceX/my-random-tools/tree/master/vgm-file-related/vgm_ayconv

The purpose of me requesting this is just so songs that only use the YM2203 channels or just SSG are properly saved in a format that doesn't use other channels. Ideally it would be if Bambootracker would allow to switch soundchips on the module itself but I think that's too much to ask all things considered.

**Comment by jpcima** [comment]
It's an easy conversion indeed, and also I have been interested in having such a feature myself.
Lately I did work some work in this direction, outside of BambooTracker and based on vgm; it will be practical to add such a thing in the exporter directly.

I thought of adding a set of export options.
- FM to OPNA/OPN2/OPN (OPM?)
- SSG to internal or external YM2149

The YM2203, specifically, should have clock at 3993600 to preserve the timbres.
(has clock divisor of 72, as observed from MAME)

**Comment by cyberic99** [comment]
Yeah, OPM with 8 FM channels would be awesome!

**Comment by pedipanol** [comment]
@cyberic99 Implementing OPM into the S98/VGM export would already require more attention (which is why @jpcima added a ? on the option), while OPN soundchips and the YM2419 being from the same family are almost directly compatible between each other, so the only potential problem on the export would be the garbage additional data and the clock setting.

The OPM soundchip operates in a different way (additional channels, additional instrument data, no SSG-EG, no FM3Extend, noise mode on channel 8, different hardware LFO settings, etc.), so implementing it into the tracker would require a totally new sound emulation core. Unlike my suggestion of stripping down OPNA exclusive channels, since that would still use the OPNA emulation core.

Even if it would be viable to add it I don't think it should be done yet, because I think it would be better for the tracker to perfect the use of the OPNA before trying a totally different soundchip such as the OPM.

**Comment by cyberic99** [comment]
@pedipanol thanks for your explanations.
I didn't know about the noise mode.

Yes, I can understand it will require more work and could be a rather long-term goal.

**Comment by jpcima** [comment]
The purpose, at least in my case, is to export the music work to different hardware.
For OPM, it takes a translation of the register language, and also the tuning system is different; furthermore, it's a possibility the timbre may sound a bit off due to clocking.
If someone truly finds usefulness in this, I'll examine the possibility.

**Comment by pedipanol** [comment]
By the way, since the enabling FM3extend works like famitracker's expansion chips, I wanna request to use that same section to have an option to set Bambootracker to YM2203 mode (hiding FM 4-6 and Rhythm, with a FM3extend option as welll), and for SSG-only, that way people can make modules focused on those VGM export targets without the trouble of having all the additional channels those chips doesn't have

**Comment by jpcima** [comment]
>set Bambootracker to YM2203 mode (hiding FM 4-6 and Rhythm, with a FM3extend option as welll), and for SSG-only

+ability of setting a different clock speed would also be nice, in that perspective.
Then it may mimic a target which use incompatible clock (eg. Megadrive YM2612)

**Comment by rerrahkr** [comment]
Now I have almost implemented the basic features of YM2608, I return to implementing YM2203 mode and SSG only mode.
I have two plans for implementation:

1. Add OPN mode and SSG only mode to song type of the module property. This controls tracks used by defining new song formats corresponding to each mode.
2. Hide any tracks by the visible mask. A song uses the conventional song type, but by hiding the unused tracks, it will not be possible to edit them.

For 1, it requires to revise the module format and modify the playback process, but anyone can open a module with only valid tracks.
For 2, only the display process needs to be changed, but states of track visibility are not saved in a module.
I think that it is not necessary to add the information depending on the export target to a module because the chip selection is only set in vgm/s98 export, so I think 2 is better.

**Comment by rerrahkr** [comment]
I added track visibility control at 1f3939dc8ad777b14f3304cb4a303d01d02bfe74.
In "View"→"Hide Tracks", you can select hiding tracks by checkboxes: when you turn off FM4-6, rhythms and ADPCM, it is displayed like YM2203 mode.
Note this is only a feature to hide tracks, so any notes entered on that track will be played.

**Comment by freq-mod** [comment]
It's a nice feature, but would it be possible possible to add option to automatically mute the tracks that are being hidden as well?

**Comment by freq-mod** [comment]
>Note this is only a feature to hide tracks, so any notes entered on that track will be played.

Would it be possible to add a configuration option for automatic muting hidden tracks?

**Comment by rerrahkr** [comment]
> a configuration option for automatic muting hidden tracks

I added it at 3147b52e236afb949227704cb6844e9aef5597b7.

**Comment by freq-mod** [comment]
There is a problem - if I, for example,  disable all channels except ADPCM (so that only ADPCM track is visible) I can't create any other new instrument than a FM one, even when clicking and highlighting that track.

**Comment by rerrahkr** [comment]
I forgot to detect the current track after hiding tracks, I fixed it at 0416b11c9d27485f51c9a6ac7718db0725589310.

**Comment by freq-mod** [comment]
One last nitpick from me - imagine we have a song that uses only SSG and we would like to export it to YM2149 or AY-3-8910 VGM. Then, it is still needed to select FM chip target, which is pointless in such a situation. 
So, ability to select "None" in FM target section of VGM export dialog can be a good addition.

**Comment by rerrahkr** [comment]
> "None" in FM target section

I added at 602fbbc5c77984d1a6f8b4831035c1b87a33d210.

By the way, I also did some research on export to YM2610, but decided not to add it because the register map is different from YM2608.

**Comment by rerrahkr** [comment]
> I added track visibility control

Now the track visibility state is reset when it is closed. Should BambooTracker restore this on startup?
I will add the selection to change this behavior in the configuration, but I cannot decide the default behavior. Which is more useful?

**Comment by rerrahkr** [comment]
> I will add the selection to change this behavior in the configuration

Added at 8db6b8f116df32064c4059f3d6f1c4c5bf4c6254. I finally set the track visibility restoration disabled as default.

**Comment by rerrahkr** [comment]
I have implemented requests here, so I close this issue.
